### PR TITLE
🔧  combine AZURE_STANDARD_JSON_B64 and AZURE_VMSS_JSON_B64 into AZURE_JSON_B64

### PR DESCRIPTION
**Pull request by chewong**
**What this PR does / why we need it**:

Address https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/746#discussion_r449294779.

/assign @CecileRobertMichon 
/test pull-cluster-api-provider-azure-capi-e2e
/test pull-cluster-api-provider-azure-conformance-v1alpha3
/test pull-cluster-api-provider-azure-conformance-machine-pool-v1alpha3

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
does that we can't use `standard` vmType?

**Comment by CecileRobertMichon** [comment]
@nader-ziada we shouldn't need the standard vmType for Standard LB it works for both VMs and VMSS, see https://github.com/kubernetes-sigs/cloud-provider-azure/issues/338#issuecomment-642076028 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/695

(of course a user could always modify the template to use the standard vmType if they really wanted to).

**Comment by nader-ziada** [comment]
> @nader-ziada we shouldn't need the standard vmType for Standard LB it works for both VMs and VMSS, see [kubernetes-sigs/cloud-provider-azure#338 (comment)](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/338#issuecomment-642076028) and #695
> 
> (of course a user could always modify the template to use the standard vmType if they really wanted to).

ok thanks for the explanation

**Pull request merged**
