### PR TITLE
ci: enabling containerd log collection on windows for more cluster templates

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

 

 
**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds containerd log collection pods to `cluster-template-prow` which is used as the default cluster template by `ci-entrypoint.sh`
This will allow us to collection containerd logs in more test passes like azuredisk / azurefile test passes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

/assign @CecileRobertMichon @jsturtevant @mboersma

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@marosset do we need to fix https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_logcollector.go#L244 for containerd separately?

**Comment by marosset** [comment]
> @marosset do we need to fix https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_logcollector.go#L244 for containerd separately?

Yes, that will need to be a separate fix. 
This PR runs a pod that logs containerd events to stdout so we can actually get the logs.

For azure_logcollector we will want to change the behavior to query running containers and other things on the node to not use docker.exe and also look for CNI/kubelet/etc log files in the correct place.
I can work on that next.

**Comment by marosset** [comment]
I need to move the resource-set resources in the kustomize templates too.

**Comment by marosset** [comment]
/unhold
The ci-entrypoint.sh starts contianerd logging by default on Windows nodes 
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2253/pull-cluster-api-provider-azure-ci-entrypoint/1517269979815219200/artifacts/workload-cluster/capz-g3vm-xwc68/pods/kube-system_containerd-logger-sc8jv/pod-describe.txt

**Comment by jsturtevant** [comment]
/lgtm

The HA job in the pull-cluster-api-provider-azure-e2 uses this template and I am seeing the logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2253/pull-cluster-api-provider-azure-e2e/1517269979609698304/artifacts/clusters/capz-e2e-fal404-ha/kube-system/containerd-logger-mx7lf/ 🥳 

Unfortunately, the machine pool jobs don't get this update since they don't inherit from the base template here.  We can update that in a separate PR.

Since this modified the templates to be safe will run:
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

**Comment by marosset** [comment]
/assign @CecileRobertMichon @devigned 
For review / approval

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
