### PR TITLE
Convert identities service to SDKv2

### LINKED ISSUE #3409: Integrate azure-sdk-for-go v2
/kind feature

This is an umbrella issue to track the overall progress of converting services not covered by ASO (see #3402) to use Azure's SDK for Go version 2. 

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3569
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3473
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3441
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3442
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3861
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3890
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3913
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3881
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3443
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3889
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3921
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3926
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3928
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3922
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3941
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3924
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3934
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3930
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3929
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3923
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3925
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3940
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3917
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3927
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3984
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3920
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3919
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3942
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3993
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3891
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3992
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3918
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3985
```

This list comes primarily from Azure/azure-service-operator#2237. This issue replaces #2670.

### LINKED ISSUE #3930: Update identities service to SDK v2

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Converts the identities service to azure-sdk-for-go version 2.

**Which issue(s) this PR fixes**:

Fixes #3930

**Special notes for your reviewer**:

This is a simple, non-async service that only supports `Get` and `GetClientID`.

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
@mboersma there's a conflict on this one

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
