### PR TITLE
💎 Refactor network interfaces scope to interface

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Follow up from #716, this PR applies the same pattern to network interfaces.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially addresses #110 , #627 and #609

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
💎 Refactor network interfaces scope to interface
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
adding the api-diff for future reference
```
sigs.k8s.io/cluster-api-provider-azure/cloud/services/networkinterfaces
  Incompatible changes:
  - (*Service).Delete: changed from func(context.Context, interface{}) error to func(context.Context) error
  - (*Service).Reconcile: changed from func(context.Context, interface{}) error to func(context.Context) error
  - NewService: changed from func(*sigs.k8s.io/cluster-api-provider-azure/cloud/scope.ClusterScope, *sigs.k8s.io/cluster-api-provider-azure/cloud/scope.MachineScope) *Service to func(NICScope) *Service
  - Service.MachineScope: removed
  - Service.Scope: changed from *sigs.k8s.io/cluster-api-provider-azure/cloud/scope.ClusterScope to NICScope
  - Spec: removed
  Compatible changes:
  - NICScope: added
sigs.k8s.io/cluster-api-provider-azure/cloud/services/networkinterfaces/mock_networkinterfaces
  Compatible changes:
  - MockNICScope: added
  - MockNICScopeMockRecorder: added
  - NewMockNICScope: added
sigs.k8s.io/cluster-api-provider-azure/controllers
  Incompatible changes:
  - DefaultBootstrapTokenTTL: removed
sigs.k8s.io/cluster-api-provider-azure/cloud
  Incompatible changes:
  - ClusterDescriber.ControlPlaneSubnet: added
  - ClusterDescriber.NodeSubnet: added
  - ClusterDescriber.Vnet: added
  Compatible changes:
  - NICSpec: added
sigs.k8s.io/cluster-api-provider-azure/cloud/services/publicips
  Incompatible changes:
  - ClusterDescriber.ControlPlaneSubnet: added
  - ClusterDescriber.NodeSubnet: added
  - ClusterDescriber.Vnet: added
sigs.k8s.io/cluster-api-provider-azure/cloud/services/publicips/mock_publicips
  Compatible changes:
  - (*MockPublicIPScope).ControlPlaneSubnet: added
  - (*MockPublicIPScope).NodeSubnet: added
  - (*MockPublicIPScope).Vnet: added
  - (*MockPublicIPScopeMockRecorder).ControlPlaneSubnet: added
  - (*MockPublicIPScopeMockRecorder).NodeSubnet: added
  - (*MockPublicIPScopeMockRecorder).Vnet: added
sigs.k8s.io/cluster-api-provider-azure/cloud/scope
  Compatible changes:
  - (*MachineScope).ControlPlaneSubnet: added
  - (*MachineScope).NICSpecs: added
  - (*MachineScope).NodeSubnet: added
  - (*MachineScope).Subnet: added
  - (*MachineScope).Vnet: added

```

**Comment by nader-ziada** [comment]
code looks good and following the same pattern extensively reviewed in #718 

/lgtm

**Comment by nader-ziada** [comment]
@CecileRobertMichon did you just have to rebase or did you make changes?

**Comment by CecileRobertMichon** [comment]
rebase

**Comment by CecileRobertMichon** [comment]
looks like I messed up the rebase in the test file... let me fix it

**Comment by nader-ziada** [comment]
went through the latest changes of adding the log with scope, looks good

/lgtm

**Comment by CecileRobertMichon** [comment]
@nader-ziada reabsed and squashed

I think this is ready now

/approve

**Comment by CecileRobertMichon** [comment]
test failure seems like a flake
```
STEP: bootstrapping test environment
Timeout [60.000 seconds]
[BeforeSuite] BeforeSuite 
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/controllers/suite_test.go:48
  Timed out
```

/retest

**Comment by nader-ziada** [comment]
> test failure seems like a flake
> 
> ```
> STEP: bootstrapping test environment
> Timeout [60.000 seconds]
> [BeforeSuite] BeforeSuite 
> /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/controllers/suite_test.go:48
>   Timed out
> ```
> 
> /retest



> test failure seems like a flake

this flake has been happening 50% of the time recently, briefly looked into it, but not sure yet what the problem is

**Pull request merged**
