### PR TITLE
update .pre-commit config

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- This PR updates .pre-commit config. @nojnhuh had pointed out once that verify job already runs the list of checks I'd configured in `.pre-commit`. We can remove them.
  - remove _lint checks_ since we have a new linter job running on each PR.
  - remove _spellchecks_, _boilerplate-code checks_, _tiltfile checks_, _modules check_ and _codespell check_ since we already had a verify job running on each PR.
- This PR also updates some versions of the pre-commit hooks.
- Pre-commit is now faster :) 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update pre-commit hooks
```

### CODE REVIEW

**Comment by nawazkh** [comment]
> the value of a pre-commit is to force me to run local tests rather than just push my code to GitHub and see what happens.

Good point. 

Speaking with the team overtime, I deduced that some folks don't use pre-commit because it slowed down their workflow.
Especially `lint` that took a really long time. 
Removing the redundant `make verify-` jobs speeds up the `pre-commit` workflow. 
It also encourages adoption since pre-commit runs important hooks like [gitleaks](https://github.com/gitleaks/gitleaks?tab=readme-ov-file#pre-commit).

On the flip side, yes, we will not run the verify jobs (`verify-boilerplate`, `verify-modules`, `verify-gen`, `verify-shellcheck`, `verify-conversions`, `verify-tiltfile`, `verify-codespell`)  _in our local_. That gets handled by `pull-cluster-api-provider-azure-verify` job.

To me, I would wanna know about errors from `gitleaks`, `end-of-file-fixer` and `trailing-whitespace` before code gets into GitHub. So pre-commit is acting as the first line of defense before code gets out of my local. 
And I want to run `verify-boilerplate`, `verify-modules`, `verify-gen`, `verify-shellcheck`, `verify-conversions`, `verify-tiltfile`, `verify-codespell` on every code change(handled at PR via job).

That being said, I am happy to revert my changes and just update the pre-commit hook's versions. 
Since this really boils down to our preference of developing and commiting code, I dont really have a strong preference. 
I am inclined on whichever approach that leads to higher adoption of pre-commit. :)

**Comment by mboersma** [comment]
> I am inclined on whichever approach that leads to higher adoption of pre-commit

I agree with that. 👍🏻 

From my point of view, this just means I will need to remember to run `make lint verify` before committing. But if more of the team prefers a faster, less comprehensive pre-commit, that works for me.

**Review by mboersma — APPROVED** [review]
/lgtm
/assign @jackfrancis

**Pull request merged**
