### PR TITLE
Update Azure dependencies

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What this PR does / why we need it**:
Update Azure dependencies

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Azure SDK APIs bump:
- `network` --> 2019-04-01 (includes Azure Bastion API)
- `resources` --> 2019-05-01

**Release note**:

```release-note
Update Azure dependencies
- github.com/Azure/azure-sdk-for-go v31.1.0
- github.com/Azure/go-autorest/autorest v0.5.0
- github.com/Azure/go-autorest/autorest/azure/auth v0.1.0
- github.com/Azure/go-autorest/autorest/to v0.2.0
- github.com/Azure/go-autorest/autorest/validation v0.1.0
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Opened an issue upstream for this dependency failure: https://github.com/Azure/go-autorest/issues/413

**Comment by tamalsaha** [comment]
FWIW, I am also stuck on this issue and added my findings here: https://github.com/Azure/go-autorest/issues/413#issuecomment-511108424

**Pull request merged**
