### PR TITLE
don't reduce replicas if ext. managed MachinePool

### LINKED ISSUE #3244: MachinePool reduces replicas when externally managed
/kind bug

**What steps did you take and what happened:**
Adjusting the replica count of a VMSS when having an externally managed MachinePool (by e.g. `cluster-autoscaler`) should only be done by the external scaler and not by the MachinePool controller. 
We discovered today it can happen that the MachinePool controller tries to match the number of AzureMachinePoolMachines with the replicas and tries to reduce the replica count.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/96fccea407457f0b0c382ed48d7d338ccd33a5fb/azure/scope/machinepool.go#L346-L364

This conflicts with the autoscaler since too many (or the wrong) instances get deleted. 

I'm investigating whether we need to skip doing reduce in this code block or something else is off. 

**What did you expect to happen:**
No adjustment of replicas by the MachinePool controller.

**Anything else you would like to add:**
I'll be contributing a possible fix for this soon. 

**Environment:**

- cluster-api-provider-azure version: main (~1.8.0)
- Kubernetes version: (use `kubectl version`): 1.24.11
- OS (e.g. from `/etc/os-release`): windows/linux hybrid

### PR DESCRIPTION
**Pull request by mweibel**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When MachinePool is externally managed, the AzureMachinePoolController reconciles after each reconciliation loop also the AzureMachinePoolMachines. At this point the `MachinePool.spec.Replicas` might not yet be up to date when the external scaler has right before, or during the reconcile loop, scaled down the VMSS by deleting a VMSSVM. At this point the controller notices an over-provision count > 0 and decides to delete another VMSSVM which often is not the same as the autoscaler is deleting. 

In general if an external autoscaler is in place for a MachinePool, we should avoid deleting any machines since the autoscaler is taking care of that. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3244

**Special notes for your reviewer**:
I considered permitting to delete failed machines by doing the externally managed replicas check later but decided it's better to leave this fully up to the autoscaler.
The added unit tests don't cover all of the Deletion possibilities so might want to be extended later on. I think it's good enough for now to have the two checks I added for the difference in behaviour we introduce with this change. 

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:
```release-note
fixes scaling down behavior when MachinePool is externally managed
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/assign @mboersma

**Comment by mweibel** [comment]
FYI @mboersma @CecileRobertMichon tests passed here but LGTM has been removed since I rebased on top of latest main.

**Comment by jackfrancis** [comment]
@mweibel thank you so much for this fix! Let me know if you need help manually cherry-picking into `release-1.7`, I'd be happy to do so but didn't want to step on your toes.

**Pull request merged**
