### PR TITLE
skip applying addons to aks flavor

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- `tilt` will skip installing the below artifacts for _AKS_ flavored template
  - `calico`
  - `cloud-provider-azure`
- Also updates Kubernetes_version at Tilt to `v1.25.6`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
- Fixes the aks tilt template issue being discussed over https://kubernetes.slack.com/archives/CEX9HENG7/p1683828885344989

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
Tried this locally and everything is working great! Thanks @nawazkh!

/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Pull request merged**
