### PR TITLE
[backport-release-0.4] do not include customData in AzureMachinePool hash calculation

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
cherry-pick of #1197 in release-0.4

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Do not include VMSS customData in the hash tag calculation to correct a reconcile cycle caused when the bootstrap token refreshes.
```

### CODE REVIEW

**Review by devigned — APPROVED** [review]
/lgtm

Thank you, @nader-ziada!

**Comment by nader-ziada** [comment]
different failure that I don't think is related to this PR

/test pull-cluster-api-provider-azure-e2e-release-0-4

**Pull request merged**
