### PR TITLE
[WIP]Using controller runtime envtest instead of fetch_ext

### PR DESCRIPTION
**Pull request by Darshnadas**
According to issue #1990 added the changes in the makefile and deleted the fetch_ext.sh script.

 
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@Darshnadas thanks for the PR! Please rebase, there is a merge conflict

**Comment by Darshnadas** [comment]
hi @CecileRobertMichon Sure!

**Comment by Darshnadas** [comment]
I have done the rebase, please give a review.

**Comment by CecileRobertMichon** [comment]
@Darshnadas could you please amend the commit to make it more descriptive (what you wrote for PR title would work) and mark the release note as "NONE"?

**Comment by Darshnadas** [comment]
Sure @CecileRobertMichon

**Comment by Darshnadas** [comment]
@CecileRobertMichon I did a rebase, can you please review it?

**Comment by CecileRobertMichon** [comment]
@Darshnadas I still see a merge conflict for the Makefile 

Also, can you please make sure that running `make test` works after this change?

**Comment by Darshnadas** [comment]
Hi @CecileRobertMichon I did run `make test` the errors I got was timeout so I am not sure as to how fix this as it took quite some time to run

**Comment by shysank** [comment]
@Darshnadas There is still a merge conflict, unfortunately. Can you try rebasing again?

**Comment by Darshnadas** [comment]
Okay @CecileRobertMichon

**Comment by jackfrancis** [comment]
@Darshnadas  @CecileRobertMichon @nawazkh let me know if we should re-open this. As a lot has changed since Feb in this surface area, I wonder if this PR has been superceded by work since then.

**Comment by CecileRobertMichon** [comment]
superseded by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2374

**Pull request closed without merging**
