### PR TITLE
limit dependabot PRs to 5

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- This PR explicitly limits the total number of PRs created by dependabot to `5` for each of the packages `/go.mod` and `/gitHub-actions`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm
Thanks for looking into this!

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
