### PR TITLE
Replaced Windows with Windows + WSL2

### LINKED ISSUE #1608: Replacing Windows with Windows + WSL2 for clarification
/kind documentation

Currently the docs mention setting up of the project in Windows OS, but for better results it is suggested the project is set up in a nix environment.

**Describe the solution you'd like**
Modifying the docs and mentioning the setting up of the project in Windows + WSL2 instead Windows. This would provide clarification that the files should be checked out to wsl file system for obtaining better results.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1608 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sayantani11** [comment]
@CecileRobertMichon I don't know if the install make section was kept empty for some valid reason but I tried writing the commands there as well, if it creates problem I can remove it as well.

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/assign @jsturtevant

**Review by jsturtevant — COMMENTED** [review]
minor comment otherwise lgtm.  Thanks for your contribution!

**Comment by CecileRobertMichon** [comment]
@sayantani11 can you please squash the commits?

**Comment by sayantani11** [comment]
@CecileRobertMichon I actually tried but there's some problem with this branch, and I am unable to. If we don't squash the commits, will that be a problem?

**Comment by jsturtevant** [comment]
We can use the following to squash on merge:

/label tide/merge-method-squash

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

In general, I try to avoid using tide/merge-method-squash because it omits the pr from release notes but in this case there is no release note so should be fine

**Pull request merged**
