### PR TITLE
Support running serial/slow Windows jobs

### LINKED ISSUE #1858: Add support to run Windows Serial/Slow jobs
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We currently have a job to run the [main windows tests](https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master). We need to add support to run the [serial/slow tests like done for aks-engine](https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-serial-slow-master)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/sig windows

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
We currently have a job to run the main windows tests. We need to add support to run the serial/slow tests like done for [aks-engine](https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-dockershim-serial-slow-master)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes  #1858

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
created https://github.com/kubernetes/test-infra/pull/24426 for testing

also should run 
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

**Comment by jsturtevant** [comment]
The HPA tests failed due to missing the metric server (required for HPA).  We had https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1125 has some discussion on adding it

We can add the metric server as part of the CRS for the e2e tests.  @CecileRobertMichon we've discuss CRS in the past. Do you have any reservations here?

**Comment by CecileRobertMichon** [comment]
> We can add the metric server as part of the CRS for the e2e tests

SGTM

**Comment by jsturtevant** [comment]
I've temporarily added the commits from #1903 to run in CI

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

**Comment by jsturtevant** [comment]
progress!  several of the HPA tests are now passing. 4 are failing now:

- 2 are failing due to a missing feature flag that we have enabled in the aks-engine test (`HPAContainerMetrics`)
- 2 are failing due to other reasons (looking now)

**Comment by jsturtevant** [comment]
Summary of the other two failures:

`Kubernetes e2e suite: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) ReplicationController light Should scale from 2 pods to 1 pod [Slow]` failed due to `calico-ipam` not being found

```
E1209 20:53:05.742832    3836 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"08bd274f8faa130937b8fa01c736ba9e1d13296e8a35e9c11c7f2989946293f0\": failed to find plugin \"calico-ipam\" in path [C:/opt/cni/bin]" pod="horizontal-pod-autoscaling-651/rc-light-6lbk7"
E1209 20:53:05.755089    3836 kuberuntime_manager.go:832] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"08bd274f8faa130937b8fa01c736ba9e1d13296e8a35e9c11c7f2989946293f0\": failed to find plugin \"calico-ipam\" in path [C:/opt/cni/bin]" pod="horizontal-pod-autoscaling-651/rc-light-6lbk7"
E1209 20:53:05.772432    3836 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"rc-light-6lbk7_horizontal-pod-autoscaling-651(3b77cf3a-80ca-456e-b2a3-284b695b6fa0)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"rc-light-6lbk7_horizontal-pod-autoscaling-651(3b77cf3a-80ca-456e-b2a3-284b695b6fa0)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"08bd274f8faa130937b8fa01c736ba9e1d13296e8a35e9c11c7f2989946293f0\\\": failed to find plugin \\\"calico-ipam\\\" in path [C:/opt/cni/bin]\"" pod="horizontal-pod-autoscaling-651/rc-light-6lbk7" podUID=3b77cf3a-80ca-456e-b2a3-284b695b6fa0
```

`Kubernetes e2e suite: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5` failed due to what looks like a containerd crash `ListPodSandbox with filter from runtime service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF`:

```
I1209 20:50:49.569151    4936 reconciler.go:216] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-59k2v\" (UniqueName: \"kubernetes.io/projected/9f50e3bf-c799-4755-94fc-c5b2f2438a49-kube-api-access-59k2v\") pod \"test-deployment-8758bfc76-987d7\" (UID: \"9f50e3bf-c799-4755-94fc-c5b2f2438a49\") " pod="horizontal-pod-autoscaling-7464/test-deployment-8758bfc76-987d7"
I1209 20:50:55.896995    4936 fake_cpu_manager.go:51] "AddContainer" pod="horizontal-pod-autoscaling-7464/test-deployment-8758bfc76-987d7" containerName="test-deployment" containerID="3e44e183cc3b3c24a43c3de393110631d903cb056ed68870d668ff61eda7d25c"
I1209 20:50:55.896995    4936 fake_memory_manager.go:50] "Add container" pod="horizontal-pod-autoscaling-7464/test-deployment-8758bfc76-987d7" containerName="test-deployment" containerID="3e44e183cc3b3c24a43c3de393110631d903cb056ed68870d668ff61eda7d25c"
I1209 20:50:55.896995    4936 fake_topology_manager.go:58] "AddContainer" pod="horizontal-pod-autoscaling-7464/test-deployment-8758bfc76-987d7" containerName="test-deployment" containerID="3e44e183cc3b3c24a43c3de393110631d903cb056ed68870d668ff61eda7d25c"
E1209 20:50:57.805928    4936 remote_runtime.go:365] "ListPodSandbox with filter from runtime service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" filter="&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},}"
E1209 20:50:57.816705    4936 kuberuntime_sandbox.go:285] "Failed to list pod sandboxes" err="rpc error: code = Unavailable desc = error reading from server: EOF"
I1209 20:50:57.809744    4936 dynamic_cafile_content.go:170] "Shutting down controller" name="client-ca-bundle::c:\\etc\\kubernetes\\pki\\ca.crt"
```

**Comment by jsturtevant** [comment]
I think the route cause of the failure is a reboot due to a upgrade.  They should be disabled: https://github.com/kubernetes-sigs/image-builder/blob/5d61101b5ed8841f9c3579ff1322635441064b25/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L32-L38 but looks like they are not

```
12/9/2021 8:52:14 PM   6005 Information      The Event log service was started.                                        
12/9/2021 8:51:58 PM   6006 Information      The Event log service was stopped.                                        
12/9/2021 8:51:57 PM   1074 Information      The process C:\Windows\servicing\TrustedInstaller.exe (capz-conf-jbqf4)   
                                             has initiated the restart of computer capz-conf-jbqf4 on behalf of user   
                                             NT AUTHORITY\SYSTEM for the following reason: Operating System: Upgrade   
                                             (Planned)                                                                 
                                              Reason Code: 0x80020003                                                  
                                              Shutdown Type: restart       
```

**Comment by jsturtevant** [comment]
confirmed we are also disabling this via arm and we are:  https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1a2aeeafcc5983ea5fd6cb7a25b93ec043a2322d/azure/services/virtualmachines/spec.go#L261-L263

**Comment by CecileRobertMichon** [comment]
so it's doing updates even though we disabled them via ARM??

**Comment by jsturtevant** [comment]
yes, I believe the issue is we are setting the registry key as a string in https://github.com/kubernetes-sigs/image-builder/blob/5d61101b5ed8841f9c3579ff1322635441064b25/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L32-L38 and not a DWORD (thanks @marosset for looking at it with me)

**Comment by jsturtevant** [comment]
added feature flag and temp fix for auto updates:

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

**Comment by jsturtevant** [comment]
serial jobs passed, with all the updates!  I am working on a fix in image builder, this might help the other jobs related to windows as well.

I will rebase and remove the added metric server commits once #1903 merges and clean up the few fixes but is ready for a general review

/assign @CecileRobertMichon @mboersma

**Review by mboersma — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
