### PR TITLE
🌱 Uplift go version to v1.19.0

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Uplifts go version to v1.19.0 and it is part of the #2773

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
`make verify` & `make verify-conversions` and `make verify-modules` targets have been run and are passing locally with go version 1.19.3 installed on the Linux machine.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
I don't think this is strictly required, but I noticed that https://github.com/onsi/gomega/releases/tag/v1.20.1 is the first version of gomega that has been tested against go 1.19, so it might make sense to try to rev gomega to 1.20 (1.20.2 is the current latest) as part of this PR. Thoughts?

**Review by mboersma — COMMENTED** [review]
/lgtm

Tested locally with Go 1.19.3.

**Comment by jackfrancis** [comment]
@furkatgofurov7 ah yes, makes perfect sense

/approve

**Pull request merged**
