### PR TITLE
update nvidia gpu operator to 1.10.1

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

This PR updates the nvidia gpu-operator implementation to use 1.10.1.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

It appears that the GPG key to download apt packages that ships with 1.9.1 has expired:

```
Checking NVIDIA driver packages...

Updating the package cache...

W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC

E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is no longer signed.
```

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
Fixes #2275

**Comment by mboersma** [comment]
/lgtm

```log
[1mSTEP[0m: creating a Kubernetes client to the workload cluster
[1mSTEP[0m: Waiting for a node to have an "nvidia.com/gpu" allocatable resource
[1mSTEP[0m: running a CUDA vector calculation job
May  2 19:18:52.360: INFO: starting to create CUDA vector calculation job
[1mSTEP[0m: waiting for job default/cuda-vector-add to be complete
May  2 19:18:52.433: INFO: waiting for job default/cuda-vector-add to be complete
May  2 19:19:22.672: INFO: job default/cuda-vector-add is complete, took 30.238585123s
```

**Comment by jackfrancis** [comment]
@jsturtevant if you'd like an all-green test run on your PR(s) a rebase on top of this change should do the trick

**Comment by jackfrancis** [comment]
@CecileRobertMichon can we agree to skip GPU tests for v1alpha4 going forward (it is already skipped on v1alpha3)?

Because we aren't testing any core capz functionality + the amount of manual work it would take to update the GPU ClusterResourceSet implementation in the `release-0.5` branch it seems updating the test-infra spec to skip the GPU job is the most practical path forward.

Until we take some action the v1alpha4 periodic job will be broken:

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-v1alpha4

cc @mboersma @Jont828

**Comment by Jont828** [comment]
Sure thing Jack, sounds good to me

**Pull request merged**
