### PR TITLE
[release-1.1] update capi references to v1.0.4, v0.4.7, v0.3.25

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

This PR updates the release-1.1 branch to refer to new v1.0, v0.4, and v0.3 releases of capi, enabling us to continue testing the 1.1 release branch of capz

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
both tests had one failure which looked like LB flakes
/retest

**Pull request merged**
