### PR TITLE
error early in tilt on errors in flavor commands

### LINKED ISSUE #3135: Tilt cluster flavor command shows as passed even if it failed
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
1. Spin up Tilt with `make tilt-up`
2. Modify a flavor's cluster template to fail webhook validation
3. The command shows as passed once calico comes up

**What did you expect to happen:**
The command fails immediately when an error occurs while creating a cluster.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 1.7
- Kubernetes version: (use `kubectl version`): 1.26.1
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**

**What this PR does / why we need it**: The command run by tilt to deploy a flavor template is comprised of many individual shell commands, though only the last one determines the overall exit status. When any one of them fails, tilt should stop and report the failure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3135

**Special notes for your reviewer**:

- Follow-up from #3231

- [ ] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by willie-yao** [comment]
@nojnhuh I just tested this change with an erroneous template that causes a webhook error. However, the Tilt command is still hanging despite the error. Is this PR aiming to catch webhook errors when creating a cluster?

The error for reference. Tilt is still showing `updating` for the cluster creation.
```
[Spec.SystemAssignedIdentityRole.DefinitionID: Invalid value: "": the definitionID field cannot be empty, Spec.SystemAssignedIdentityRole.Scope: Invalid value: "": the scope field cannot be empty
```

**Comment by nojnhuh** [comment]
@willie-yao I think that was because commands on the left side of `&&` aren't short-circuited by `sh -e`, so I changed that to `;` and I think it's working as expected now.

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
