### PR TITLE
Change branch from master to main in few files

### LINKED ISSUE #1820: Change branch from master to main in few files
/kind documentation

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Following https://cs.k8s.io/?q=cluster-api%2Fblob%2Fmaster&i=nope&files=&excludeFiles=&repos= two files in the CAPZ repo:
.github/ISSUE_TEMPLATE/proposal.md
docs/book/src/topics/windows.md
requires renaming of the branch to main.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind other

**What this PR does / why we need it**:
Changes branch from master to main in few files

**Which issue(s) this PR fixes** 
Fixes #1820 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by mboersma** [comment]
Thanks @Evalle!

**Pull request merged**
