### PR TITLE
[release-1.7] Always run AKS E2E get+update as transaction

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

This is a manual cherry-pick of #3058 to release-1.7.

I'm seeing this flake in periodic tests for this branch. E.g.:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-aks-v1beta1/1617580985807802368

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
/retest

flake addressed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3084

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Pull request merged**
