### PR TITLE
Minor edits to "SSH access to nodes" doc

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Fixes a couple typos and inconsistencies, quotes a `jq` command that wouldn't work for me otherwise (in zsh), and adds markdown language hinting to some blocks.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
The GH link checker thinks this is a dead link: 
https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/
Works for me...? I'll investigate.

**Comment by jackfrancis** [comment]
> The GH link checker thinks this is a dead link:
> https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/
> Works for me...? I'll investigate.

Just got a flake for a totally different URL (and got one yesterday too)

Methinks the gh link checker is not resilient enough...

**Comment by mboersma** [comment]
> Methinks the gh link checker is not resilient enough...

Maybe not. Also maybe I just lack permissions, but I don't see a way to re-run it in case this was a transient error.

**Comment by CecileRobertMichon** [comment]
prow recently made changes to allow rerunning GH actions through the retest command ^

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
