### PR TITLE
Update getting started troubleshooting to use capz

### PR DESCRIPTION
**Pull request by DavidLangworthy**
This corrects a minor doc bug.  Updating from "azure-provider" to "capz" in troubleshooting.

**Release note**:
NONE

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

@DavidLangworthy can you please squash the commits?

**Comment by cpanato** [comment]
@DavidLangworthy can you plase add the section in the PR description, i think in this case you can just add `NONE` but doing that will make the bot to remove the need for a release note
```
**Release note**:
<!--  Write your release note:
1. Enter your extended release note in the below block. If the PR requires additional action from users switching to the new release, include the string "action required".
2. If no release note is required, just write "NONE".
-->
```
 ```release-note

 ```

**Comment by DavidLangworthy** [comment]
Thanks. I'll take care of both of these.

**Comment by DavidLangworthy** [comment]
I'm going to abandon this PR.  I used the github editor without creating a branch and I can't figure out how to get it squashed and rebased properly. Sorry.

**Pull request closed without merging**
