### PR TITLE
fix NodeTaints and NodeLabels return type for AzureManagedMachinePools

### LINKED ISSUE #4116: AzureManagedMachinePool oscillates, when trying to reconcile, between running and provisioned when removing nodeLabel or taints fields.
/kind bug

AzureManagedMachinePool oscillates between "ready: True" and "ready: False" with the message "agentpools creating or updating" when deleting nodeLabels or Taints fields.

**What steps did you take and what happened:**

To reproduce the error, it is necessary to have an AzureManagedMachinePool resource, with the nodeLabels or taints fields filled in. For example:

**AzureManagedMachinePool**
```console
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  creationTimestamp: "2023-10-11T13:40:24Z"
  finalizers:
  - azurecluster.infrastructure.cluster.x-k8s.io
  generation: 3
  labels:
    azuremanagedmachinepool.infrastructure.cluster.x-k8s.io/agentpoolmode: System
    cluster.x-k8s.io/cluster-name: lrecio-azure
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: luiswn1-mp-0
  namespace: cluster-lrecio-azure
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachinePool
    name: luiswn1-mp-0
    uid: 0b9e28fc-ea9c-45c6-a418-d0aa02e6a977
  resourceVersion: "85055"
  uid: 3a38bd01-ec78-4380-b983-9f7343752c20
spec:
  availabilityZones:
  - "1"
  linuxOSConfig:
    sysctls:
      vmMaxMapCount: 262144
  mode: System
  name: luiswn1mp0
  nodeLabels:
    backup: "false"
  osDiskType: Managed
  osType: Linux
  providerIDList:
  - azure:///subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachineScaleSets/XXXX/virtualMachines/0
  scaleSetPriority: Regular
  sku: Standard_D8_v3
  subnetName: lrecio-azure
status:
  conditions:
  - lastTransitionTime: "2023-10-11T13:54:06Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-10-11T13:54:06Z"
    status: "True"
    type: AgentPoolsReady
  ready: true
  replicas: 1
```
On the other hand, not only it fails to reconcile, but it also fails to remove labels or taints.

**What did you expect to happen:**

It should reconcile the AzureManagedMachinePool resource, as these are mutable fields and may have no value, and remove both labels and taints, depending on the field removed.

**Anything else you would like to add:**

After increasing the level of verbosity, I think the most interesting capz logs are these, which are repeated over and over again.

```console
I1011 14:20:27.429742       1 azuremanagedmachinepool_controller.go:249] controllers.AzureManagedMachinePoolReconciler.reconcileNormal "msg"="Reconciling AzureManagedMachinePool" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:27.429823       1 azuremanagedmachinepool_reconciler.go:107] controllers.azureManagedMachinePoolService.Reconcile "msg"="reconciling managed machine pool" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:28.251166       1 async.go:122] async.Service.CreateOrUpdateResource "msg"="successfully got existing resource" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "resource"="luiswn1mp0" "resourceGroup"="lrecio-azure" "service"="agentpools" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:28.251412       1 spec.go:253] agentpools.Service.Parameters "msg"="found a diff between the desired spec and the existing agentpool" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "difference"="  containerservice.AgentPool{\n  \tResponse: {},\n  \tManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{\n  \t\t... // 27 identical fields\n  \t\tSpotMaxPrice:              nil,\n  \t\tTags:                      nil,\n- \t\tNodeLabels:                nil,\n+ \t\tNodeLabels:                map[string]*string{\"backup\": &\"false\"},\n  \t\tNodeTaints:                nil,\n  \t\tProximityPlacementGroupID: nil,\n  \t\t... // 7 identical fields\n  \t},\n  \tID:   nil,\n  \tName: nil,\n  \tType: nil,\n  }\n" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:28.251457       1 async.go:140] async.Service.CreateOrUpdateResource "msg"="updating resource" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "resource"="luiswn1mp0" "resourceGroup"="lrecio-azure" "service"="agentpools" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:33.153389       1 azuremanagedmachinepool_controller.go:282] controllers.AzureManagedMachinePoolReconciler.reconcileNormal "msg"="requeuing due to transient transient failure" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "error"="failed to reconcile machine pool luiswn1mp0: operation type PUT on Azure resource lrecio-azure/luiswn1mp0 is not done. Object will be requeued after 15s" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"
I1011 14:20:33.167824       1 reconciler.go:115] controllers.reconciler.Reconcile "msg"="successful" "AzureManagedMachinePool"={"name":"luiswn1-mp-0","namespace":"cluster-lrecio-azure"} "controller"="azuremanagedmachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureManagedMachinePool" "name"="luiswn1-mp-0" "namespace"="cluster-lrecio-azure" "reconcileID"="1273add4-d35c-47bc-af2a-d4c13eea1163" "request"="cluster-lrecio-azure/luiswn1-mp-0" "x-ms-correlation-request-id"="cc46bd5e-295f-461d-954f-2f10ea0a88b0"

```

**Environment:**

- cluster-api-provider-azure version: 1.11.3
- Kubernetes version: (use `kubectl version`): v1.27.1

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- CAPZ will send out the below return types to AKS API so that the AKS API clears-out `NodeLabels` and `NodeTaints` respectively.
  - an empty Map when the `NodeLabels` are deleted.
  - an empty pointer array when the `NodeTaints` are deleted.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4116 

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
fix NodeTaints and NodeLabels return type for AzureManagedMachinePools
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
Does this address #4116?

**Review by nojnhuh — COMMENTED** [review]
I think this is correct. Could you please fix up this PR to be more descriptive and add tests? e2e tests might also need to be updated.

**Comment by nawazkh** [comment]
Thanks, Jon!
I am trying to reproduce this, will fix up the description and add tests after that. 
I think Jack has an improvement to build upon: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4124

**Comment by nawazkh** [comment]
Converted to draft so that I don't trigger any more tests on an in progress PR.

**Comment by nojnhuh** [comment]
@nawazkh When this PR is ready for review please mark it as such in the project board.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by nojnhuh** [comment]
@nawazkh Are we sure this bug affects 1.10? Or do we know that this isn't related to the SDK v2 migration?

**Comment by nawazkh** [comment]
> Are we sure this bug affects 1.10? Or do we know that this isn't related to the SDK v2 migration?

Confirming. Will update in a bit.

**Comment by nawazkh** [comment]
I see the endless reconciliation on `release-1.10` as well. I believe we need this fix on `release-1.10`. 
The cluster is still up in my sub, I see the below in my diff. 
```
 containerservice.AgentPool{
  	Response: {},
  	ManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{
  		... // 27 identical fields
  		SpotMaxPrice:              nil,
  		Tags:                      nil,
- 		NodeLabels:                nil,
+ 		NodeLabels:                map[string]*string{"test": &"test"},
  		NodeTaints:                nil,
  		ProximityPlacementGroupID: nil,
  		... // 7 identical fields
  	},
  	ID:   nil,
  	Name: nil,
  	Type: nil,
  }
```

**Comment by nawazkh** [comment]
I should be able to cherry-pick onto release-1.10 branch now that https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4127 has merged. 

/cherry-pick release-1.10

**Pull request merged**
