### PR TITLE
Improve release process

### PR DESCRIPTION
**Pull request by dtzar**
Signed-off-by: David Tesar <david.tesar@microsoft.com>

**What type of PR is this?**
Helps improve the flow of the release process steps including making it more clear how an outside contributor could help with this process if desired.

/kind documentation

**What this PR does / why we need it**:

```release-note
Improve release process docs
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

Thanks @dtzar, I think this does clarify the order of operations among other things. 👍🏻

**Comment by dtzar** [comment]
I would like some feedback from @mboersma and @jackfrancis on the post-release steps.  

Specifically:
1. Are there any steps there we think should be release-blocking?
2. Is there a more optimal or combined order of operations?

**Comment by jackfrancis** [comment]
/lgtm
/approve

I have some follow-up thoughts but this is a material improvement, let's land this, thanks @dtzar!

**Pull request merged**
