### PR TITLE
upgrade to golangci-lint v1.44.2

### LINKED ISSUE #2144: Upgrade to golangci-lint v1.44.2
/kind feature

**Describe the solution you'd like**
Hey folks,

just fyi there is a new version of golangci-lint, in case you want to update.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

 

 
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- upgrade to golangci-lint v1.44.2
- Fix related issues
```
exp/controllers/azuremanagedmachinepool_reconciler_test.go:39:71: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
                        Err:      errors.Wrap(NewAgentPoolVMSSNotFoundError("foo", "baz"), "boom!"),
                                                                                           ^
azure/services/loadbalancers/client.go:88:111: response body must be closed (bodyclose)
                err = autorest.NewErrorWithError(err, "network.LoadBalancersClient", "CreateOrUpdate", createFuture.Response(), "Failure sending request")
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2144 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade to golangci-lint v1.44.2
```

### CODE REVIEW

**Comment by sbueringer** [comment]
I'll leave the review for the CAPZ folks as I'm not really familiar with CAPZ.

**Comment by mboersma** [comment]
@Prajyot-Parab, looks like you need to run `make generate` and commit the changes it makes. (You can run `make verify` locally to ensure that it is passing.)

**Comment by CecileRobertMichon** [comment]
`make verify` is broken on main since last night because of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2147, should be unrelated to this PR. Will report back once we merge an update.

**Comment by CecileRobertMichon** [comment]
@mboersma this should be good now

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
