### PR TITLE
Add labels for Tilt resources

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**: Add labels for Tilt resources

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Jont828** [comment]
Worked on this with @mboersma, there's an 'uncategorized' resource that we couldn't apply a label to. Should we leave it as is, or is there a way to handle that?

**Comment by mboersma** [comment]
Here's what tilt's web UI looks like after the changes in this PR:

tilt-labels

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

perhaps we can deal with the "uncategorized" resources by categorizing them into resources and adding them to a group later

**Comment by Jont828** [comment]
I can open an issue to add the uncategorized CRDs to a label later on. Is this PR good to be merged?

**Review by devigned — APPROVED** [review]
/lgtm
/approve

Great developer experience improvement. Thank you, @Jont828!

**Pull request merged**
