### PR TITLE
add transient error handling to AMMP delete

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug
/area managedclusters

**What this PR does / why we need it**: This PR adds logic to handle transient errors in the AzureManagedMachinePool controller like in other controllers. Without this, transient errors (including "operation not done") cause a resource to get requeued as if any other error occurred, which is likely more frequent than necessary.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Possibly related to the flake described in #3970

**Special notes for your reviewer**:

- [X] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
Fixed a bug causing transient errors in AzureManagedMachinePool reconciliation to requeue too aggressively
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
Role assignments issue should be ok now
/retest

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Pull request merged**
