### PR TITLE
Update GPU test job image

### LINKED ISSUE #1341: Update GPU test job image
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_gpu.go#L79

We should change the image to `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.1-ubuntu18.04`. We're currently using the the v0.1 image which is very old.

See also https://github.com/Azure/aks-engine/pull/4376/files#diff-ca8d461afa879854958f8325480cb2c8d76bed23e334a937680613a53328fc85R13

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind other

**What this PR does / why we need it**:
- Updates GPU test job image

**Which issue(s) this PR fixes**
Fixes #1341

**Release note**:
```release-note
"NONE"
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
to check the GPU tests that don't run as part of the PR e2e job

/test pull-cluster-api-provider-azure-e2e-full

**Comment by CecileRobertMichon** [comment]
GPU test looks good. Test failure is due to #1328 

/lgtm
/approve

**Pull request merged**
