### PR TITLE
add markdown linter changes

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
- add markdown linter changes
- also updates one of the code blocks in the md file which wasnt rendering right in CAPZ book

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Below link is broken: 
- FILE: ./docs/book/src/topics/failure-domains.md
  - https://docs.microsoft.com/en-us/azure/availability-zones/az-overview → Status: 404

I am not sure of a valid substitute link for this.

**Comment by mboersma** [comment]
https://learn.microsoft.com/azure/reliability/availability-zones-overview seems to work for me here... 

Also, when we link to our docs we should leave the `/en-us` part out of the URL. It can then redirect to docs in your local language, if available. (I know you didn't write the URL in the first place, just pointing it out.)

What markdown linter did you run? Is this just a single pass to clean things up, or something we should integrate into CI?

**Comment by nawazkh** [comment]
> https://learn.microsoft.com/azure/reliability/availability-zones-overview seems to work for me here, maybe use that?

Oh, it works for me too! The URL was 404 yesterday when I tried. I will update the broken link.

> Also, when we link to our docs we should leave the `/en-us` part out of the URL. It can then redirect to docs in your local language, if available. (I know you didn't write the URL in the first place, just pointing it out.)

Interesting, I did not know azure docs handled locale in this way. Thanks for pointing it out! 

> What markdown linter did you run? Is this just a single pass to clean things up, or something we should integrate into CI?

I was correcting the highlights shown by `vscode-markdownlint` in my local env, it was just a single pass. 
The author of vscode-markdownlinter did point out a cli interface to lint markdown files. Project link for reference: https://github.com/DavidAnson/markdownlint-cli2

The real reason to land on this page is that we seem to have missed the [start of a code block ( ``` ) in the documentation](https://capz.sigs.k8s.io/topics/managedcluster.html#deploy-with-clusterctl)
Screenshot 2022-11-10 144340

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
