### PR TITLE
drop Local only env var

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- This PR drops the env variable `LOCAL_ONLY` from the test scripts. We dont seem to be using it anymore, so cleaning it up.
- By dropping `LOCAL_ONLY` I have defaulted `USE_LOCAL_KIND_REGISTRY` to `true` as it would be behaved with `LOCAL_ONLY` being present.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Drop LOCAL_ONLY env var from the test scripts.
```

### CODE REVIEW

**Review by jsturtevant — COMMENTED** [review]
/lgtm

**Comment by jackfrancis** [comment]
/lgtm
/approve

should we remove all of the references and comments in test-infra jobs?

**Pull request merged**
