### PR TITLE
Update controller tools to v0.8.0 and conversion gen to v1.23.1

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Attempt to fix the verify job that broke after https://github.com/kubernetes/test-infra/pull/24815/files merged.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update controller tools to v0.8.0 and conversion gen to v1.23.1
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
lgtm

🤞🏻

**Review by jackfrancis — APPROVED** [review]
lgtm

**Pull request merged**
