### PR TITLE
🌱 update to capi dependency to v0.3.7

### PR DESCRIPTION
**Pull request by devigned**
**What this PR does / why we need it**:
Move from CAPI v0.3.7-rc.1 to v0.3.7.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade the CAPI dependency to v0.3.7
```

### CODE REVIEW

**Comment by devigned** [comment]
/hold

Updating references elsewhere.

**Comment by nader-ziada** [comment]
also lets run the capi tests

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by CecileRobertMichon** [comment]
/hold

for capi e2e

**Comment by nader-ziada** [comment]
capi e2e passed 

/hold cancel

**Pull request merged**
