### PR TITLE
Add sonasingh46 to reviewers

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adding @sonasingh46 to CAPZ reviewers as a result of his significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+sonasingh46+is%3Aclosed) to the project both as an author and as a reviewer. Thank you for everything you've done for CAPZ so far @sonasingh46!

/assign @alexeldeib @CecileRobertMichon @devigned @jackfrancis 

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/lgtm

+1

**Comment by CecileRobertMichon** [comment]
Let's start a lazy consensus until Thursday office hours?

**Review by devigned — APPROVED** [review]
/lgtm

Yay! Thank you, @sonasingh46!

**Pull request merged**
