### PR TITLE
Add mboersma to cluster-api-azure-reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: @mboersma has made significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+mboersma+is%3Aclosed) to the project both as an author and as a reviewer, this PR adds him as a reviewer in OWNERs. Thank you for all your contributions so far @mboersma! 🥳 

/assign @nader-ziada @devigned @alexeldeib @shysank 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
lgtm

**Comment by shysank** [comment]
lgtm

**Comment by devigned** [comment]
lgtm

**Comment by mboersma** [comment]
😄 Thanks everyone! I'm here for the long haul, and I'll start helping more with reviews.

**Comment by CecileRobertMichon** [comment]
Welcome @mboersma 🎉

When you get a chance please open PRs to add yourself the following OWNERS files:

https://github.com/kubernetes/k8s.io/blob/cb153ca944c0511206e5b26cf44dacf993f17c01/k8s.gcr.io/images/k8s-staging-cluster-api-azure/OWNERS
https://github.com/kubernetes/test-infra/blob/f8a90c0f33ec96557a56c4137a54effeaa71dcb1/config/jobs/kubernetes-sigs/cluster-api-provider-azure/OWNERS
https://github.com/kubernetes/org/blob/d34a80cdb4179a33aaeca0b79ccbdf3038c7aad8/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L109

**Comment by mboersma** [comment]
Thanks! Here are the OWNERS updates:
  - https://github.com/kubernetes/k8s.io/pull/2568
  - https://github.com/kubernetes/test-infra/pull/23282
  - https://github.com/kubernetes/org/pull/2899

**Pull request merged**
