### PR TITLE
Remove failure domains dead link in docs

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**: v1alpha3 docs were removed from CAPI book in https://github.com/kubernetes-sigs/cluster-api/pull/6018. Removing links and entire sentence about failure domains support since it's no longer "new" and all API versions currently supported support it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Remove failure domains dead link in docs
```

### CODE REVIEW

**Review by sonasingh46 — APPROVED** [review]

**Review by mboersma — APPROVED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
