### PR TITLE
clarify template patch name that injects windows replica count

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This is a boring PR that clarifies a kustomize patch file name to better describe what it does.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
prow flake?
/retest

**Review by mboersma — APPROVED** [review]
/lgtm
/retest-required

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve
/hold for test to pass

**Pull request merged**
