### PR TITLE
[WIP] Remove GitHub-actions caches every Tuesday midnight.

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- Cleanup GitHub action caches every Tuesday midnight

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Can any of the maintainers test this by manually running this workflow?
Expected output: Cleanups Actions -> Caches. We have about 13.6Gb of Caches that should get reduced.
Note that, caches older than 30 days will be deleted.

**Comment by willie-yao** [comment]
@nawazkh I'd love to run this but I'm not sure if I can run a workflow from your fork on GitHub actions. Do you know if there's a way for me to do this?

**Comment by nawazkh** [comment]
> @nawazkh I'd love to run this but I'm not sure if I can run a workflow from your fork on GitHub actions. Do you know if there's a way for me to do this?

You might want to run the below script from your local and see if a cache gets deleted. 
```bash
export MAX_CACHE_AGE_DAYS=30
```

```bash
#!/bin/bash

echo "Fetching list of caches..."
# List caches

caches=$(gh actions-cache list --json id,createdAt)
echo "Caches found: $(echo "$caches" | jq '. | length')"
# Get current time
current_time=$(date +%s)
# Loop through all caches and delete those older than MAX_CACHE_AGE_DAYS
for cache_id in $(echo "$caches" | jq -r '.[] | select((('"$current_time"' - (.createdAt | fromdateiso8601 | mktime)) / 86400) > '"$MAX_CACHE_AGE_DAYS"') | .id'); do
 echo "Deleting cache with ID: $cache_id"
 gh actions-cache delete $cache_id --confirm
 echo "Deleted cache $cache_id"
 exit 0
done
```

^ this shell script is a copy paste from the PR. Notice that I added an `exit 0` to exit after one cache deletion. 
I cannot run it since I do not have the permissions play with CAPZ caches.

**Comment by willie-yao** [comment]
I got this error when running the command:
```
Fetching list of caches...
Caches found: 22
jq: error (at <stdin>:1): date "2024-10-07T21:39:13.0633333Z" does not match format "%Y-%m-%dT%H:%M:%SZ"
```

**Comment by nawazkh** [comment]
I was looking at the cache, and noticed that the older caches(more than 22 days) get auto deleted. 
We might not need this solution after all. 

Thank you for checking the code nonetheless @willie-yao ! 

/close

**Pull request closed without merging**
