### PR TITLE
Update CAPI components to v0.4.0-beta.0

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: After #1421 merged and updates go modules to use the latest CAPI tag, this updates other places in the code to use the newly released artifacts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
images should be there now

/retest

**Comment by CecileRobertMichon** [comment]
/retest

quota limits

**Pull request merged**
