### PR TITLE
test: enable using custom flavor for conformance test

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

 

 
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
- Enables configuring custom flavor for conformance tests using CONFORMANCE_FLAVOR
- Added dual-stack ginkgo v2 kubetest config

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-conformance
/test pull-cluster-api-provider-azure-conformance-with-ci-artifacts
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

to make sure this isn't affecting any existing conformance jobs ^

**Comment by CecileRobertMichon** [comment]
I believe `pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts` is broken since yesterday due to unrelated reasons (bad VHD image), @marosset @mboersma are working on mitigation, you can ignore the test result for that one for now.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/assign @mboersma

**Review by mboersma — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
