### PR TITLE
Change prow creds parsing to allow no new lines

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Currently, the parsing of prow creds only works if the credential file separates each key/value with a new line which isn't always true for yaml files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
with test.toml file:

```
[Creds]
ClientID = "123456-789"
ClientSecret = "my=fake=password@$@)?"
TenantID = "$(TENANT_ID)"
SubscriptionID = "$(SUBSCRIPTION_ID)"
StorageAccountName = "$(STORAGE_ACCOUNT_NAME)"
StorageAccountKey = "$(STORAGE_ACCOUNT_KEY)"
```

```
$ export AZURE_SUBSCRIPTION_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'SubscriptionID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_TENANT_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'TenantID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_CLIENT_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'ClientID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_CLIENT_SECRET="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'ClientSecret[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"

$ echo $AZURE_SUBSCRIPTION_ID 
$(SUBSCRIPTION_ID)

$ echo $AZURE_TENANT_ID
$(TENANT_ID)

$ echo $AZURE_CLIENT_ID
123456-789

$ echo $AZURE_CLIENT_SECRET
my=fake=password@$@)?
```

with test.toml file:

```
[Creds]
ClientID = "123456-789" ClientSecret = "my=fake=password@$@)?" TenantID = "$(TENANT_ID)" SubscriptionID = "$(SUBSCRIPTION_ID)" StorageAccountName = "$(STORAGE_ACCOUNT_NAME)" StorageAccountKey = "$(STORAGE_ACCOUNT_KEY)"
```

```
$ export AZURE_SUBSCRIPTION_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'SubscriptionID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_TENANT_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'TenantID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_CLIENT_ID="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'ClientID[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"
$ export AZURE_CLIENT_SECRET="$(cat ${AZURE_CREDENTIALS} | grep -E -o 'ClientSecret[[:blank:]]*=[[:blank:]]*"[^[:space:]"]+"' | cut -d '"' -f 2)"

$ echo $AZURE_SUBSCRIPTION_ID 
$(SUBSCRIPTION_ID)

$ echo $AZURE_TENANT_ID
$(TENANT_ID)

$ echo $AZURE_CLIENT_ID
123456-789

$ echo $AZURE_CLIENT_SECRET
my=fake=password@$@)?
```

**Comment by alexeldeib** [comment]
pending tests

/lgtm

**Comment by vincepri** [comment]
LGTM

**Pull request merged**
