### PR TITLE
[WIP] Deploy aks clusters using major and minor versions

### LINKED ISSUE #4117: Support for AKS cluster deployment with Major.Minor version.
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Support deploying AKS clusters using capz, with just major.minor version 
eg version: 1.26.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by LochanRn**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Allows deployment of AKS clusters using major and minor version, with the new sdk version, we can now deploy AKS clusters by just using major and minor version, patch version with which the cluster will be the highest available version corresponding to that major.minor. 
Eg: v1.26 can be used to deploy v1.26.6 version AKS. (6 is the highest patch currently available for 1.26)
The same is supported with the latest SDK
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4@v4.3.0#ManagedClusterProperties

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4117, #4111

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [X] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dtzar** [comment]
@LochanRn was there something else you were going to add to this PR before review?

**Comment by LochanRn** [comment]
> @LochanRn was there something else you were going to add to this PR before review?

@dtzar This will not work until we fix this even in capi, version is also referenced from machinepool object  
https://github.com/kubernetes-sigs/cluster-api/blob/b1b6896968686ac9fc21c0c1ef51ff5ac1e8031e/internal/webhooks/machine.go#L163

**Comment by dtzar** [comment]
Thanks for the info @LochanRn.  Is there an open issue in CAPI to address this?

**Comment by LochanRn** [comment]
@dtzar  Raised an issue https://github.com/kubernetes-sigs/cluster-api/issues/9721

**Comment by nojnhuh** [comment]
@LochanRn I'm going to close this for now since we have the CAPI issue filed and that's waiting to get some traction. Once that's resolved, feel free to reopen this PR.

/close

**Pull request closed without merging**
