### PR TITLE
Revert "update default custom cloud provider config for managed identity"

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This reverts #5023 as the custom cloud config in this repo now matches the old default in the cloud-provider repo.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — COMMENTED** [review]
/lgtm
/approve

yay

**Comment by nojnhuh** [comment]
public IP quota

/retest

**Pull request merged**
