### PR TITLE
Add errorlint to the golangci linters

### LINKED ISSUE #1087: Add errorlint to the golangci linters
/kind feature

**Describe the solution you'd like**
Add errorlint to the .golangci.yml and fix up any of the issues caused by the new linter rules.

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds `errorlint` to the golangci linters.

**Which issue(s) this PR fixes**:
Fixes #1087 

**Special notes for your reviewer**:

`NONE`

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

#1123 should help with the flakes...

**Comment by furkatgofurov7** [comment]
@devigned @CecileRobertMichon this seems to be ready to go in, PTAL. Thanks!

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
Failed with `timeout`, re-triggering CI to see if that helps. 

/retest

**Comment by furkatgofurov7** [comment]
hmm strange, it already passed windows test before having `lgtm/approve`, but while re-checking all tests, it is failing..

**Comment by CecileRobertMichon** [comment]
@furkatgofurov7 we're having issues with transient e2e failures in all PRs right now, thanks for your patience getting this passing CI... we're discussing the issues in Slack.

/retest

**Review by devigned — APPROVED** [review]

**Comment by nader-ziada** [comment]
lets try this again after #1131 

/retest

**Pull request merged**
