### PR TITLE
Fetch Calico Helm chart from new URL

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Tigera changed the location of the Calico chart from https://projectcalico.docs.tigera.io/charts to https://docs.tigera.io/calico/charts.

**Which issue(s) this PR fixes**:

See also #3142.

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
See projectcalico/calico#7300.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Review by marosset — APPROVED** [review]
/lgtm

**Pull request merged**
