### PR TITLE
Improve api server LB probe

### PR DESCRIPTION
**Pull request by kahun**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
The apiserver can fail if a control plane is starting o regenerating and the service is up but not ready yet.

**TODOs**:
- [X] squashed commits
- [ ] includes documentation
- [X] adds unit tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@jackfrancis do you have any thoughts on this one?

overall LGTM but I wonder if there could be any downsides

**Comment by jackfrancis** [comment]
@kahun the purpose of this change is to prefer a non-Running apiserver Pod to transient non-2xx responses that occur because TCP 6443 connection is active but the web server is not yet bootstrapped and responding to the `/healthz` URL path?

**Comment by kahun** [comment]
> @kahun the purpose of this change is to prefer a non-Running apiserver Pod to transient non-2xx responses that occur because TCP 6443 connection is active but the web server is not yet bootstrapped and responding to the `/healthz` URL path?

During a control plane failure or an upgrade process, when a new control plane is being initialized and the TCP 6443 port is already active but the web server is not ready yet, one out of three calls to the k8s API server will fail. This change ensures that the apiserver pod is made available in the load balancer only when it is completely ready.

**Pull request merged**
