### PR TITLE
Add jackfrancis to maintainers

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

@jackfrancis has made significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+jackfrancis+is%3Aclosed) to the project both as an author and as a reviewer for the past 2 years. This PR officially adds him to the CAPZ maintainers in OWNER_ALIASES.
Thanks for everything that you do @jackfrancis! Cluster API and CAPZ are much better with you here.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
:humbled:

**Comment by CecileRobertMichon** [comment]
/lgtm

well deserved!

**Comment by alexeldeib** [comment]
/lgtm

always a pleasure, Jack :)

**Pull request merged**
