### PR TITLE
missing context wrapping

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR addresses positively identified instances where we're not wrapping context objects w/ our logger as is the normal pattern.

@nojnhuh points out [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3128/files#r1091116305) that we're sort of induced by our linter to create such opportunities.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
I opted not to classify this as a bug, but I could go either way. If we decide to call this a but we'll want to cherry-pick back two releases.

**Comment by nojnhuh** [comment]
> I opted not to classify this as a bug, but I could go either way.

I think the impact here is low enough that the overhead of backporting probably isn't worth it. We can of course always backport this later if we find that would be beneficial.

/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
