### PR TITLE
Change version skew listing to a link to CAPI docs

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

 

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

The README currently includes a list of supported Kubernetes versions which needs to be manually updated every few months, and also may lead readers to believe that the CAPZ project can provide support for older versions of Kubernetes which are unsupported by CAPI and deprecated in k/k itself. To remove this potential confusion, I propose linking to the CAPI docs for the canonical Kubernetes version support policy.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
