### PR TITLE
Revert "fix error pulling cloud provider images in e2e"

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: This PR reverts #2763 to use the latest images for cloud-provider-azure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
This change requires https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2686 to be merged first.
/hold

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
