### PR TITLE
Update to compute API 2021-11-01 

### PR DESCRIPTION
**Pull request by invidian**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Extracting changes which should be easier to merge from #2277.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by mboersma** [comment]
/cherry-pick release-1.2

According to the proposal at #2295, CAPZ should try to backport fixes to the last two releases. This is a prerequisite to cherry-picking #2357.

**Pull request merged**
