### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by justaugustus**
**What this PR does / why we need it**:
I wanted to take some time to update our OWNERS to recognize a few contributors who have been active in the project over the last quarter or so:
- Add @awesomenix as approver
- Add @CecileRobertMichon as reviewer
- Add @vincepri as reviewer

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
There's nothing particularly controversial here, but I'll hold a little for comments.
/hold
/assign @soggiest @awesomenix 
/priority important-soon
/kind cleanup
/milestone baseline

**Comment by CecileRobertMichon** [comment]
cc @craiglpeters @ritazh

**Comment by justaugustus** [comment]
Welcome! :)
/pony party
/hold cancel

**Pull request merged**
