### PR TITLE
Revert "⏪ reverted userAssignedIdenties logic based on PR #2214"

### PR DESCRIPTION
**Pull request by mboersma**
This reverts commit 48768e459880f295f1fdd77c1c044024ffde11ec.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Reverts a simplification to userAssignedIdentities lookup, since it appears that fixed code is no longer in cloud-provider-azure.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Restore ClientID lookup for user-assigned IDs
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

this is fixing a user facing a bug, IMO it should have a release note

**Comment by mboersma** [comment]
/hold cancel

> it should have a release note

Agreed, I updated the release note blurb in the description.

**Pull request merged**
