### PR TITLE
Bump CAPZ versions in provider upgrade tests

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates the versions of CAPZ used in provider upgrade tests to current patches. This is a release chore that we've missed with the last two patch releases. :-|

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@mboersma did we just overlook the documented instructions for this post- (or pre- ?) release step, or does this reflect that the documentation needs clarifying?

**Comment by jackfrancis** [comment]
PS Thank you for tracking this!

**Comment by jackfrancis** [comment]
wow I totally didn't mean to close this, human error is clearly the dominant theme in this PR...

**Comment by mboersma** [comment]
> did we just overlook the documented instructions ...?

Yes, we do document in "Post-Release Steps" that "[Update clusterctl API version upgrade tests](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/developers/releasing.md#update-clusterctl-api-version-upgrade-tests)" is part of release chores.
But the [CAPZ book](https://capz.sigs.k8s.io/developers/releasing) is hosting an earlier version of this page that doesn't have these instructions. This is one case where it seems important to use the doc in `main`. (In my defense, since I did at least one of these releases and missed this step.)

**Comment by mboersma** [comment]
ping @jackfrancis @nojnhuh PTAL

**Comment by jackfrancis** [comment]
/hold

for workload-upgrade test

**Comment by mboersma** [comment]
/hold cancel

workload-upgrade test passed 👍🏻

**Pull request merged**
