### PR TITLE
feat: use force delete when deleting VMs

### LINKED ISSUE #1045: Enable Force Delete of Azure VMs
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Leverage the new forceDeletion option for VMs https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/delete which skips grateful deletion and improves latency

/assign

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR adds the "force delete" functionality to all VM delete operations. This is an appropriate configuration given that cluster-api delete operations don't require "graceful deletion" under the hood (ensure disks shut down before vms shut down, etc).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1045

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
use force delete when deleting VMs
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
🎉 

let's hold until we've got confirmation that 

1) the feature is GA in all regions and it's safe to enable
2) this results in a decrease of VM deletion durations

/hold

**Comment by jackfrancis** [comment]
After ~35 data points delete operations are not regressing from current performance, and no failures have been observed.

**Pull request merged**
