### PR TITLE
Set MachinePool feature flag to true

### PR DESCRIPTION
**Pull request by dkoshkin**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Now that CAPI has enabled the `MachinePool` feature by default and CAPZ is using latest CAPI version with this change, we should do the same here.
See [CAPI PR](https://github.com/kubernetes-sigs/cluster-api/pull/10141/commits#diff-8d4b80dac52bef6a87376c16699a47555f567a9c7b68408965e37b68dedee6cbR25).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Set MachinePool feature flag to true
```

### CODE REVIEW

**Comment by mboersma** [comment]
/release-note-edit ```release-note Set MachinePool feature flag to true```

**Comment by mboersma** [comment]
/release-note-edit ```release-note Set MachinePool feature flag to true ```

**Comment by dkoshkin** [comment]
Oops, updated the release note :)

**Comment by mboersma** [comment]
Thanks! I was just trying to get the `prow` bot to do it, but for some reason the `release-note edit` command has never been successful for me.

**Review by willie-yao — COMMENTED** [review]
Can we add a note in the docs that this is now enabled by default? https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/topics/managedcluster.md?plain=1#L59

There are probably a few other places in the docs that need updating as well.

**Pull request closed without merging**
