### PR TITLE
disable AKSPublicIPPrefixSpec in AKS E2E

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

This PR disables AKS E2E tests around public IP scenarios, until we can debug and figure out how to test this signal more reliably.

See: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3047

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

I was going to suggest we use `Skip` instead, but this is just a `By` block so I think that would skip the entire `It` spec.

**Comment by jackfrancis** [comment]
/hold

for results from https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3050

**Comment by jackfrancis** [comment]
not needed!

**Pull request closed without merging**
