### PR TITLE
[release-1.8] Pin Calico to v3.25.1

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3369 (commit 2/2) to pin to Calico v3.25.1 as there seems to be a regression in v3.26.0 causing some tests to fail.

More details in slack thread: https://kubernetes.slack.com/archives/CEX9HENG7/p1685555851875059

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Pin Calico to v3.25.1
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
need to rebase on top of #3599 once it merges

**Review by marosset — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@CecileRobertMichon verify job shouldn't be failing in this way I don't think

**Comment by CecileRobertMichon** [comment]
> verify job shouldn't be failing in this way I don't think

no it shouldn't, might need to re-run make generate

**Comment by CecileRobertMichon** [comment]
@jackfrancis fixed

**Pull request merged**
