### PR TITLE
test: 3 control plane nodes to test conformance

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind other

**What this PR does / why we need it**:

This PR ensures we always use > 1 control plane node when running capz-driven conformance tests, as we want to engage the `kubeadm join` (and not just `kubeadm init`) behaviors when building clusters for Kubernetes version validation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
I agree that we should do this generally, although this might introduce a lot of flakes in the short term due to https://github.com/kubernetes/kubernetes/issues/99305

/hold

**Comment by CecileRobertMichon** [comment]
For some reason `pull-cluster-api-provider-azure-conformance-with-ci-artifacts` shows as succeeded even though it failed  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1329/pull-cluster-api-provider-azure-conformance-with-ci-artifacts/1384991957629014016

**Comment by jackfrancis** [comment]
no longer needed

**Pull request closed without merging**
