### PR TITLE
Add shysank to cluster-api-azure-reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind other

**What this PR does / why we need it**: Thank you for all your contributions so far @shysank! 

/hold for approvals
/assign @nader-ziada @devigned 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
/lgtm

Thanks for all the work @shysank

**Review by devigned — APPROVED** [review]
/lgtm
/approve

Yay, @shysank!

**Comment by CecileRobertMichon** [comment]
Welcome @shysank 🎉 

When you get a chance please open PRs to add yourself the following OWNERS files:
- https://github.com/kubernetes/k8s.io/blob/cb153ca944c0511206e5b26cf44dacf993f17c01/k8s.gcr.io/images/k8s-staging-cluster-api-azure/OWNERS
- https://github.com/kubernetes/test-infra/blob/f8a90c0f33ec96557a56c4137a54effeaa71dcb1/config/jobs/kubernetes-sigs/cluster-api-provider-azure/OWNERS
- https://github.com/kubernetes/org/blob/d34a80cdb4179a33aaeca0b79ccbdf3038c7aad8/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L109

**Pull request merged**
