### PR TITLE
standardize curl retries in scripts

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

This PR standardizes our usage of curl in dev and CI scripts to retry 3 times in order to overcome transient I/O errors.

See here for an example of a flake:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3075/pull-cluster-api-provider-azure-ci-entrypoint/1617649166840762368

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/retest

another flake fixed by #3075

**Review by mboersma — COMMENTED** [review]
/lgtm++

Thanks for making this more consistent!

**Comment by jackfrancis** [comment]
/retest

mon dieu that e2e job commenced 4 mins before #3075 landed in main

**Pull request merged**
