### PR TITLE
fix nil pointer for VMSS boot diagnostics

### LINKED ISSUE #3200: panic in scalesets.go: boot diagnostics
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
I upgraded from a previous version to 1.7.2. capz-controller-manager crashes because of a nil pointer.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
       panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a61c32]

goroutine 758 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x2001e60, 0x3947280})
       /usr/local/go/src/runtime/panic.go:884 +0x212
sigs.k8s.io/cluster-api-provider-azure/azure/services/scalesets.(*Service).validateSpec(0xc001867380, {0x26a7ed8?, 0xc001867500?})
       /workspace/azure/services/scalesets/scalesets.go:393 +0xab2
sigs.k8s.io/cluster-api-provider-azure/azure/services/scalesets.(*Service).Reconcile(0xc001867380, {0x26a7ed8?, 0xc001867470?})
       /workspace/azure/services/scalesets/scalesets.go:85 +0xcb
sigs.k8s.io/cluster-api-provider-azure/exp/controllers.(*azureMachinePoolService).Reconcile(0xc0018673e0, {0x26a7ed8?, 0xc0014f6180?})
       /workspace/exp/controllers/azuremachinepool_reconciler.go:68 +0x1b5
sigs.k8s.io/cluster-api-provider-azure/exp/controllers.(*AzureMachinePoolReconciler).reconcileNormal(0xc000784dc0, {0x26a7ea0?, 0xc0014bfb00?}, 0xc001ed75e0, 0xc000a77880)
       /workspace/exp/controllers/azuremachinepool_controller.go:290 +0x25e
sigs.k8s.io/cluster-api-provider-azure/exp/controllers.(*AzureMachinePoolReconciler).Reconcile(0xc000784dc0, {0x26a7ed8?, 0xc001a6b980?}, {{{0xc000896100?, 0xe?}, {0xc0008960f0?, 0x7?}}})
       /workspace/exp/controllers/azuremachinepool_controller.go:253 +0xd66
sigs.k8s.io/cluster-api-provider-azure/pkg/coalescing.(*reconciler).Reconcile(0xc0004b3400, {0x26a7ed8?, 0xc001a6b8c0?}, {{{0xc000896100?, 0x10?}, {0xc0008960f0?, 0x40dc87?}}})
       /workspace/pkg/coalescing/reconciler.go:109 +0x3ee
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x26a7e30?, {0x26a7ed8?, 0xc001a6b8c0?}, {{{0xc000896100?, 0x22200e0?}, {0xc0008960f0?, 0x404554?}}})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002c8820, {0x26a7e30, 0xc000a62100}, {0x20b6820?, 0xc000543460?})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002c8820, {0x26a7e30, 0xc000a62100})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:230 +0x333
```

**What did you expect to happen:**
No panic.

**Anything else you would like to add:**
We have nothing configured for boot diagnostics. 

**Environment:**

- cluster-api-provider-azure version: 1.7.2
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): linux

### PR DESCRIPTION
**Pull request by mweibel**
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
fixes nil pointer as described in #3200

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3200

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
fixes nil pointer when reconciling VMSS scalesets with no boot diagnostics enabled
```

### CODE REVIEW

**Review by nawazkh — COMMENTED** [review]
Good catch! 
Can we also support this change with a unit test?

Otherwise looks good to me!

**Comment by mweibel** [comment]
@nawazkh unit test added - please review again.

**Comment by nawazkh** [comment]
@mweibel Looks like the added unit test is missing some mock calls and hence failing `pull-cluster-api-provider-azure-test`.

**Pull request merged**
