### PR TITLE
Bump CAPI to v1.6.2

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI to [v1.6.2](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.2) and all that entails. Also updates `yq` in the `Makefile` to match the version in use by CAPI.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.6.2
```

### CODE REVIEW

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Comment by Jont828** [comment]
/lgtm
/approve

@mboersma Looks like your test passed!

**Comment by mboersma** [comment]
/hold

I left a commit in here called "squash." 😆

**Pull request merged**
