### PR TITLE
Increase wait-deployment timeout

### LINKED ISSUE #1284: E2E flake: Waiting for web-windows deployment times out
/kind failing-test

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:444
Timed out after 300.049s.
Deployment default/web-windows failed
Deployment:
{
  "metadata": {
    "name": "web-windows",
    "namespace": "default",
    "selfLink": "/apis/apps/v1/namespaces/default/deployments/web-windows",
    "uid": "499a0de1-1b41-4e93-b892-fd5d85b3467c",
    "resourceVersion": "2644",
    "generation": 1,
    "creationTimestamp": "2021-03-30T09:41:52Z",
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    },
    "managedFields": [
      {
        "manager": "cluster-api-e2e",
        "operation": "Update",
        "apiVersion": "apps/v1",
        "time": "2021-03-30T09:41:52Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            "f:progressDeadlineSeconds": {},
            "f:replicas": {},
            "f:revisionHistoryLimit": {},
            "f:selector": {
              "f:matchLabels": {
                ".": {},
                "f:app": {}
              }
            },
            "f:strategy": {
              "f:rollingUpdate": {
                ".": {},
                "f:maxSurge": {},
                "f:maxUnavailable": {}
              },
              "f:type": {}
            },
            "f:template": {
              "f:metadata": {
                "f:labels": {
                  ".": {},
                  "f:app": {}
                }
              },
              "f:spec": {
                "f:containers": {
                  "k:{\"name\":\"web-windows\"}": {
                    ".": {},
                    "f:image": {},
                    "f:imagePullPolicy": {},
                    "f:name": {},
                    "f:resources": {
                      ".": {},
                      "f:requests": {
                        ".": {},
                        "f:cpu": {},
                        "f:memory": {}
                      }
                    },
                    "f:terminationMessagePath": {},
                    "f:terminationMessagePolicy": {}
                  }
                },
                "f:dnsPolicy": {},
                "f:nodeSelector": {
                  ".": {},
                  "f:kubernetes.io/os": {}
                },
                "f:restartPolicy": {},
                "f:schedulerName": {},
                "f:securityContext": {},
                "f:terminationGracePeriodSeconds": {}
              }
            }
          }
        }
      },
      {
        "manager": "kube-controller-manager",
        "operation": "Update",
        "apiVersion": "apps/v1",
        "time": "2021-03-30T09:41:52Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:deployment.kubernetes.io/revision": {}
            }
          },
          "f:status": {
            "f:conditions": {
              ".": {},
              "k:{\"type\":\"Available\"}": {
                ".": {},
                "f:lastTransitionTime": {},
                "f:lastUpdateTime": {},
                "f:message": {},
                "f:reason": {},
                "f:status": {},
                "f:type": {}
              },
              "k:{\"type\":\"Progressing\"}": {
                ".": {},
                "f:lastTransitionTime": {},
                "f:lastUpdateTime": {},
                "f:message": {},
                "f:reason": {},
                "f:status": {},
                "f:type": {}
              }
            },
            "f:observedGeneration": {},
            "f:replicas": {},
            "f:unavailableReplicas": {},
            "f:updatedReplicas": {}
          }
        }
      }
    ]
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "web-windows"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "web-windows"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "web-windows",
            "image": "k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine",
            "resources": {
              "requests": {
                "cpu": "10m",
                "memory": "10M"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "nodeSelector": {
          "kubernetes.io/os": "windows"
        },
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "unavailableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "False",
        "lastUpdateTime": "2021-03-30T09:41:52Z",
        "lastTransitionTime": "2021-03-30T09:41:52Z",
        "reason": "MinimumReplicasUnavailable",
        "message": "Deployment does not have minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2021-03-30T09:41:52Z",
        "lastTransitionTime": "2021-03-30T09:41:52Z",
        "reason": "ReplicaSetUpdated",
        "message": "ReplicaSet \"web-windows-58699f5dd4\" is progressing."
      }
    ]
  }
}
LAST SEEN                      TYPE    REASON             OBJECT                  MESSAGE
2021-03-30 09:41:52 +0000 UTC  Normal  ScalingReplicaSet  deployment/web-windows  Scaled up replica set web-windows-58699f5dd4 to 1

Expected
    <bool>: false
to be true
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:93
```

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e-windows

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**: Increase the E2E deployment timeout as the web-windows deploy regularly times out and causes flakes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1284 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

for test retries

**Comment by CecileRobertMichon** [comment]
passed 1/1

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
passed 2/2

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
failed to create kind cluster with error `msg: "failed to pull image \"kindest/node:v1.19.1\"",` 

Ugly errror but unrelated to what we're testing here

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
passed 3/3 

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
passed 4/4

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
passed 5/5

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
passed 6/6

/test pull-cluster-api-provider-azure-e2e-windows

**Comment by CecileRobertMichon** [comment]
Node failed to come up, different flake

``` 
Timed out after 1200.001s.
Expected
    <int>: 0
to equal
    <int>: 1
```

/retest

**Comment by CecileRobertMichon** [comment]
Got 7 passes, 2 unrelated failure, 0 web-windows deployment timeout errors

Given the current job history (https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e-windows), I think it's safe to say this greatly reduces the flakes observed in #1284, if not completely eliminate them.

/hold cancel

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
