### PR TITLE
[release-1.11] wait for provisioning state in AKS e2e tests

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

Manual cherry-pick of #4255.

**Which issue(s) this PR fixes**:

Refs #3955

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
>   [FAILED] failed to run clusterctl init

Some kind of general failure in most of the unit tests in multiple PRs...

**Review by CecileRobertMichon — COMMENTED** [review]
/retest

**Pull request merged**
