### PR TITLE
Fix redundant import and rename instances of meta package v1 to metav1

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**: Fix redundant import of package `k8s.io/apimachinery/pkg/apis/meta/v1` in `azurecluster_default_test.go`. Also renamed the instances of v1 to metav1 for consistency with the rest of the imports.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@Jont828 please squash

lgtm

**Comment by devigned** [comment]
LB fail flake
/retest

**Comment by Jont828** [comment]
Just rebased and squashed
/retest

**Pull request merged**
