### PR TITLE
[release-1.9] fix AuthorizedIPRanges disable -> enable bug

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- Cherrypick of 7d988059d2572326ed8366eceb733c491320f64a
- Also copies over `//nolint:gocyclo` to the `Parameters()` function from [main](https://github.com/pluralsh/cluster-api-provider-azure/blob/64a02e09172a512c0f8630907be15f55ca49e0da/azure/services/managedclusters/spec.go#L270) since https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3800 was erroring out on go-cyclomexic complexity (A lot of nil checks). 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
authorized IP ranges will be set to []string then to nil upon deletion
```

### CODE REVIEW

**Comment by nawazkh** [comment]
I will squash the commits once lgtm-ed.

**Comment by nawazkh** [comment]
Squashed :) 
Unholding for final review :) 

/unhold

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
