### PR TITLE
Update CAPI to v1.4.2

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI references to use the new [v1.4.2 release](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.2).

**Which issue(s) this PR fixes**:

Closes #3510

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
I tested this with `tilt`: CAPI v1.4.2 and cert-manager v1.11.1 components all came up without errors and everything looks to be working.

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Comment by mboersma** [comment]
D'oh, never mind–release-1.8 is on CAPI v1.3.5.

**Pull request merged**
