### PR TITLE
Re-add defaulting for AzureMachineTemplate ssh key

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Re-add defaulting for AzureMachineTemplate ssh key
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

windows e2e cluster create flake

**Comment by shysank** [comment]
looks like a flake.
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by CecileRobertMichon** [comment]
```
capz-e2e: Running the Cluster API E2E tests upgrade from v1alpha3 to v1beta1, and scale workload clusters created in v1alpha3 Should create a management cluster and then upgrade all the providers
```

passed

**Comment by shysank** [comment]
Looks like another flake related to mhc. I'm fine with merging it since it's not related to this pr.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
