### PR TITLE
bump github.com/Azure/azure-service-operator/v2 from v2.4.0 to v2.5.0

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: Updates ASO to [v2.5.0](https://github.com/Azure/azure-service-operator/releases/tag/v2.5.0).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
CAPZ now depends on ASO v2.5.0.
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by nojnhuh** [comment]
squashed!
/hold cancel

**Comment by nojnhuh** [comment]
@willie-yao @CecileRobertMichon @mboersma Lost the lgtm to resolve go.mod conflicts. PTAL.

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by nojnhuh** [comment]
squashed!
/hold cancel

**Pull request merged**
