### PR TITLE
WIP: Expose AKS preview features

### LINKED ISSUE #2625: Expose AKS preview features
***Goals***
1. Determine a method for making AKS preview features consumable through CAPZ like GA AKS features

***Non-Goals/Future Work***
1. Implement every AKS preview feature
1. Guarantee the stability of AKS preview features in CAPZ beyond what AKS itself supports
1. Determine how to handle preview features of other APIs used for self-managed clusters

**User Story**

As a user I would like to configure AKS managed clusters with preview features to take advantage of the latest and greatest functionality available in AKS.

**Detailed Description**

Some AKS features are not available from Azure's stable API and can only be used from separate preview APIs. Since CAPZ currently only uses the stable AKS APIs, those preview features are not available and must be configured through some other means which introduces friction for users looking to use Cluster API for all their cluster lifecycle management. Exposing AKS preview features in CAPZ would eliminate that friction.

/kind proposal
/area managedclusters

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2625

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Expose AKS preview features
```

### CODE REVIEW

**Comment by dtzar** [comment]
@nojnhuh @willie-yao - Think we could get our ASO dep up to the 2.6.0 and also bump the version of the preview to the latest there?
https://azure.github.io/azure-service-operator/reference/containerservice/#next-release

Latest preview in 2.6.0 API is 2023-11-02-preview

It feels a bit odd/wrong that the preview API listed here is actually older than the stable one, but I realize this is the best of what you can do considering we're on 2.5.0 dep of ASO.
asocontainerservicev1preview "github.com/Azure/azure-service-operator/v2/api/containerservice/v1api20230202preview"
	asocontainerservicev1 "github.com/Azure/azure-service-operator/v2/api/containerservice/v1api20231001

**Comment by nojnhuh** [comment]
@dtzar https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4603#issuecomment-1964681663

**Comment by willie-yao** [comment]
Closed in favor of #4617 for better approach without modifying too much logic in `aso.go`

**Pull request closed without merging**
