### PR TITLE
Upgrade to calico 3.23.0 (release-1.2)

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
This PR updates calico to v3.23.0 in `release-1.2`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade calico to v3.23.0
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
/lgtm 
pending tests

**Comment by CecileRobertMichon** [comment]
IPv6 LB flake

/retest
/lgtm

**Comment by CecileRobertMichon** [comment]
@marosset looks like there might be some breakage between ipv6 and calico 3.23.0, the e2e test for ipv6 has not passed a single time, I don't think this is a flake

**Comment by marosset** [comment]
> @marosset looks like there might be some breakage between ipv6 and calico 3.23.0, the e2e test for ipv6 has not passed a single time, I don't think this is a flake

I think so too.
I was hoping to look into this today but was pairing with folks on something else.
I'll try and investigate later today or tomorrow.

**Comment by marosset** [comment]
I've been looking at the failures in `pull-cluster-api-provider-azure-e2e-v1beta` and wanted to share some updates.

I was able to build a functional ipv6 cluster from tilt from this branch and I also tried running `./scripts/ci-e2e.sh` locally with ginkgo.focus set to `\[Required\]`
When I ran `./scripts/ci-e2e.sh` locally I hit a cluster failure creation but it was for the `Creating a VMSS cluster [Required]` and not for the creating an ipv6 cluster like all of the PR jobs attempts saw.

```log
2] • Failure [2299.989 seconds]
[2] Workload cluster creation
[2] /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:44
[2]   Creating a VMSS cluster [REQUIRED]
[2]   /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:306
[2]     with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes [It]
[2]     /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:307
[2]
[2]     Timed out after 300.527s.
[2]     Job default/curl-to-ilb-job0hm1w failed
[2]     Job:
[2]     {
[2]       "metadata": {
[2]         "name": "curl-to-ilb-job0hm1w",
[2]         "namespace": "default",
[2]         "uid": "08a7f9a4-789a-41d0-9878-9d77053e4e2a",
[2]         "resourceVersion": "2400",
[2]         "generation": 1,
[2]         "creationTimestamp": "2022-05-19T21:38:00Z",
[2]         "labels": {
[2]           "controller-uid": "08a7f9a4-789a-41d0-9878-9d77053e4e2a",
[2]           "job-name": "curl-to-ilb-job0hm1w"
[2]         },
<snip>
```

I'm going to try running ci-e2e.sh again locally and only have it run the tests against the ipv6 cluster and will report back.

**Comment by marosset** [comment]
> I've been looking at the failures in `pull-cluster-api-provider-azure-e2e-v1beta` and wanted to share some updates.
> 
> I was able to build a functional ipv6 cluster from tilt from this branch and I also tried running `./scripts/ci-e2e.sh` locally with ginkgo.focus set to `\[Required\]` When I ran `./scripts/ci-e2e.sh` locally I hit a cluster failure creation but it was for the `Creating a VMSS cluster [Required]` and not for the creating an ipv6 cluster like all of the PR jobs attempts saw.
> 
> ```
> 2] • Failure [2299.989 seconds]
> [2] Workload cluster creation
> [2] /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:44
> [2]   Creating a VMSS cluster [REQUIRED]
> [2]   /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:306
> [2]     with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes [It]
> [2]     /home/marosset/src/github.com/marosset/cluster-api-provider-azure/test/e2e/azure_test.go:307
> [2]
> [2]     Timed out after 300.527s.
> [2]     Job default/curl-to-ilb-job0hm1w failed
> [2]     Job:
> [2]     {
> [2]       "metadata": {
> [2]         "name": "curl-to-ilb-job0hm1w",
> [2]         "namespace": "default",
> [2]         "uid": "08a7f9a4-789a-41d0-9878-9d77053e4e2a",
> [2]         "resourceVersion": "2400",
> [2]         "generation": 1,
> [2]         "creationTimestamp": "2022-05-19T21:38:00Z",
> [2]         "labels": {
> [2]           "controller-uid": "08a7f9a4-789a-41d0-9878-9d77053e4e2a",
> [2]           "job-name": "curl-to-ilb-job0hm1w"
> [2]         },
> <snip>
> ```
> 
> I'm going to try running ci-e2e.sh again locally and only have it run the tests against the ipv6 cluster and will report back.

I got one of the ipv6 clusters created by ci-e2e.sh in a failed state and am investigating.
I see 
```
 Warning  FailedCreatePodSandBox  34s (x221 over 48m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "098e8bff03621147dae2486cafa4002a85e77ebde8ffdd91aab21d828ca5f32f": plugin type="calico" failed (add): usePodCidr found but there is no IPv4 CIDR configured
 ```
 For coredns and calico-kube-controllers containers
 
 Continuing to look

**Comment by CecileRobertMichon** [comment]
I believe you need to cherry pick https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/6f93bbd277d1b9cf071150445eb88e6ab87fe042, Calico introduced a specific IPv6 config in https://github.com/projectcalico/calico/pull/5313/files#diff-742c8968cd6af9cdd7510f39e61fe127ce4fa98fe893beb0183837182ec09072R340

**Comment by marosset** [comment]
> I believe you need to cherry pick [6f93bbd](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/6f93bbd277d1b9cf071150445eb88e6ab87fe042), Calico introduced a specific IPv6 config in https://github.com/projectcalico/calico/pull/5313/files#diff-742c8968cd6af9cdd7510f39e61fe127ce4fa98fe893beb0183837182ec09072R340

Thanks!

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/hold

for tests

**Comment by marosset** [comment]
/hold cancel
tests are all passing!

**Pull request merged**
