### PR TITLE
Bump mockgen to v1.5.0

### LINKED ISSUE #1185: Bump mockgen to v1.5.0
Change the value of mockgen version here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Makefile#L75

See https://github.com/golang/mock/pull/405#issuecomment-782471295

/good-first-issue
/help

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind other

kind testing ? 

**What this PR does / why we need it**:
Bumps mockgen to v1.5.0 

**Which issue(s) this PR fixes** 
Fixes #1185

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
@Evalle you have to run the generate and include the generated files in this PR to make the `verify` job pass

**Comment by CecileRobertMichon** [comment]
since we're bumping the mock generation version, expect some diff in the mock files. Hopefully nothing that makes our tests fail...

**Comment by Evalle** [comment]
@CecileRobertMichon @nader-ziada thanks for pointing it out, I've add the generated files to this PR, let's see.

**Comment by nader-ziada** [comment]
I think you will have to rebase on top of #1186 to get windows_e2e test passing

**Comment by CecileRobertMichon** [comment]
/retest

These look like different errors

**Pull request merged**
