### PR TITLE
Update nvidia GPU operator to v1.9.1

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

See https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html

Updates nvidia-gpu-operator to [v1.9.1](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html#id1). Not a major update, but it validates that the `./hack/fetch-nvidia-resources.sh` script is working.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/retest 

```
docker push capzci.azurecr.io/cluster-api-azure-controller-amd64:20220127213844
The push refers to repository [capzci.azurecr.io/cluster-api-azure-controller-amd64]
ac205ff75e98: Preparing
5b1fa8e3e100: Preparing
5b1fa8e3e100: Layer already exists
ac205ff75e98: Pushed
received unexpected HTTP status: 500 Internal Server Error
make[1]: *** [Makefile:408: docker-push] Error 1
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure'
make: *** [Makefile:195: test-e2e] Error 2
```

**Comment by mboersma** [comment]
The e2e-full job failed on an unrelated test. The GPU test passed:

```
INFO: Waiting for the machine pools to be provisioned
[1mSTEP[0m: creating a Kubernetes client to the workload cluster
[1mSTEP[0m: Waiting for a node to have an "nvidia.com/gpu" allocatable resource
[1mSTEP[0m: running a CUDA vector calculation job
Jan 27 23:30:50.531: INFO: starting to create CUDA vector calculation job
[1mSTEP[0m: waiting for job default/cuda-vector-add to be complete
Jan 27 23:30:50.648: INFO: waiting for job default/cuda-vector-add to be complete
Jan 27 23:31:21.089: INFO: job default/cuda-vector-add is complete, took 30.441534891s
[1mSTEP[0m: Dumping logs from the "capz-e2e-5xdszq-gpu" workload cluster
```

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
