### PR TITLE
Add node role

### PR DESCRIPTION
**Pull request by tahsinrahman**
**What this PR does / why we need it**:
Add roles to nodes
```
NAME                       STATUS     ROLES    AGE     VERSION
az101-master               Ready      master   6m15s   v1.13.4
standard-b2ms-pool-j92hc   Ready      node     45s     v1.13.4
```

instead of
```
NAME                       STATUS     ROLES    AGE     VERSION
az101-master               Ready      master   6m15s   v1.13.4
standard-b2ms-pool-j92hc   Ready      <none>   45s     v1.13.4
```

ref: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/681

**Release note**:

```release-note
Add node roles to non-controlplane nodes
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@tahsinrahman -- thanks for this! Would you mind also supplying a redacted version of your machines.yaml? I see you're using a node pool here for the workers and would like to take a look.

/ok-to-test

**Comment by tahsinrahman** [comment]
@justaugustus sure, i created this using machineset, here's the yaml
```
kind: MachineSet
apiVersion: cluster.k8s.io/v1alpha1
metadata:
  name: standard-b2ms-pool
  creationTimestamp: '2019-04-03T14:09:46Z'
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: az101
  template:
    metadata:
      creationTimestamp: '2019-04-03T14:09:46Z'
      labels:
        cluster.k8s.io/cluster-name: az101
        node-role.kubernetes.io/node: ''
        set: node
    spec:
      providerSpec:
        value:
          kind: AzureMachineProviderSpec
          apiVersion: azureprovider/v1alpha1
          metadata:
            creationTimestamp: 
          roles:
          - Node
          location: eastus2
          vmSize: Standard_B2ms
          image:
            publisher: Canonical
            offer: UbuntuServer
            sku: 16.04-LTS
            version: latest
          osDisk:
            osType: Linux
            managedDisk:
              storageAccountType: Premium_LRS
            diskSizeGB: 30
          sshPublicKey: <pubkey>
          sshPrivateKey: <privkey>
      versions:
        kubelet: 1.13.4
```

**Comment by justaugustus** [comment]
Thanks for that! Are you adding it as part of the machines.yaml or deploying the MachineSet after the cluster has come up?

Could you please also add a release note to the PR description: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/170#issuecomment-479511672

/lgtm
/approve

**Comment by tahsinrahman** [comment]
I deployed machineset after creating cluster with a single master

**Comment by justaugustus** [comment]
Awesome! Thanks again. :)

**Pull request merged**
