### PR TITLE
Bump CAPI to v1.2.6

### PR DESCRIPTION
**Pull request by rajaskakodkar**
Signed-off-by: Rajas Kakodkar <rajaskakodkar16@gmail.com>

 

 
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Bump CAPI to v1.2.6 https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.6

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.2.6
```

### CODE REVIEW

**Review by sonasingh46 — APPROVED** [review]
/lgtm

**Comment by sonasingh46** [comment]
cc @mboersma

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
