### PR TITLE
Fix all linting issues and improve the make check workflow

### PR DESCRIPTION
**Pull request by tariq1890**
This should 
i) Fix all linting issues
ii) Validate dependencies
iii) Run GolangCI linter
iv) Make us CI ready :)

### CODE REVIEW

**Comment by justaugustus** [comment]
I love the idea of continuous code quality, but I'm going to defer to others on our policy around adding more tools to the ecosystem.

/hold
/assign @spiffxp @cblecker @BenTheElder

**Comment by BenTheElder** [comment]
I think using something like golangci is up to the github admin team, FWIW it certainly looks like less effort to enable all those linters that way given the PR contents.

for full merge-robot integration, this can be done with [prow](https://github.com/kubernetes/test-infra/tree/master/prow) jobs, but you'll likely want to create a docker image containing these linters or a script to install them and then need scripts to wrap running them and checking for failures, which is admittedly more involved.

we have some scripts for `golint` and `govet` throughout the ecosystem, but not some of the other ones.

**Comment by tariq1890** [comment]
So I see that cluster-api is planning on using golangci-lint https://github.com/kubernetes-sigs/cluster-api/pull/699/files.

The AWS cloud provider already has it - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml

**Pull request merged**
