### PR TITLE
Change AzureManagedCluster LoadBalancerSKU values to Uppercase

### PR DESCRIPTION
**Pull request by Evalle**
**What this PR does / why we need it**:
- Changes AzureManagedCluster LoadBalancerSKU values to Uppercase

**Which issue(s) this PR fixes** 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/908

**Release note**:

```release-note
Changes AzureManagedCluster LoadBalancerSKU values to Uppercase

**Action Required:**  
AzureManagedCluster LoadBalancerSKU values should be changed to Uppercase, ie. "basic" to "Basic" and "standard" to "Standard"
```

### CODE REVIEW

**Comment by Evalle** [comment]
@CecileRobertMichon fyi

**Comment by CecileRobertMichon** [comment]
/ok-to-test
/assign @alexeldeib 

@Evalle thanks for the PR! Please update the release note in the PR description and include "action required:" to indicate that it's a breaking change. Here's an example in another PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/798.

**Comment by Evalle** [comment]
@CecileRobertMichon thanks for the review. I've added `Release Notes` and `Action Required`. I hope it looks OK.

**Pull request merged**
