### PR TITLE
Disable latest stable k8s version in e2e

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: temporarily disable fetching the latest stable version until #1995 can provide a better long term fix to unblock e2e in PRs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by CecileRobertMichon** [comment]
the last one looks like a flake, looking...

/retest

**Pull request merged**
