### PR TITLE
Add mboersma to maintainers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: @mboersma has made significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+mboersma+is%3Aclosed) to the project both as an author and as a reviewer for the past 2 years, this PR officially adds him to CAPZ maintainers in OWNERs. Thank you for all your contributions so far @mboersma!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alexeldeib** [comment]
/lgtm 

one more warm welcome :)

**Comment by mboersma** [comment]
Thanks everyone! Happy to be here, happy to help, I'm in it for the long haul. 😄

**Pull request merged**
