### PR TITLE
increase wait for service timeout in e2e tests

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
- increase wait-service timeout

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
increase wait-service timeout in tests
```

### CODE REVIEW

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
/hold

the last failure was the one this PR is intending to fix...

```
Timed out after 1002.842s.
Service / failed
Service:
{
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {},
  "status": {
    "loadBalancer": {}
  }
}
LAST SEEN  TYPE  REASON  OBJECT  MESSAGE

Expected
    <bool>: false
to be true
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:196
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1127/pull-cluster-api-provider-azure-e2e-windows/1351619838321102848

**Comment by nader-ziada** [comment]
> /hold
> 
> the last failure was the one this PR is intending to fix...
> 
> ```
> Timed out after 1002.842s.
> Service / failed
> Service:
> {
>   "metadata": {
>     "creationTimestamp": null
>   },
>   "spec": {},
>   "status": {
>     "loadBalancer": {}
>   }
> }
> LAST SEEN  TYPE  REASON  OBJECT  MESSAGE
> 
> Expected
>     <bool>: false
> to be true
> /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:196
> ```
> 
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1127/pull-cluster-api-provider-azure-e2e-windows/1351619838321102848

should have timed out after `600s`, strange number there

**Comment by CecileRobertMichon** [comment]
@nader-ziada do you know the timeout was 1002s earlier? Also, is it possible the increase was not enough since we still got a repro?

**Comment by nader-ziada** [comment]
> @nader-ziada do you know the timeout was 1002s earlier? Also, is it possible the increase was not enough since we still got a repro?

the timeout was 3 mins (180s) and I increased it to 5 min (600s) so was surprised to see the 1002s

ran the tests like 5 times to confirm what happened but only that one failed with this error.

**Comment by CecileRobertMichon** [comment]
Could you try artificially failing it to make sure it works?

**Comment by nader-ziada** [comment]
> Could you try artificially failing it to make sure it works?

maybe its also somehow related to the fact that we change the image used by the windows test to the small one?

**Comment by nader-ziada** [comment]
in my local test, whenever I reduce the timeout below 5m, it fails. 
@CecileRobertMichon is there a specific experiment you are suggesting?

**Comment by CecileRobertMichon** [comment]
> the timeout was 3 mins (180s) and I increased it to 5 min (600s) so was surprised to see the 1002s

I meant make it fail by, for example, changing the image to an invalid one, and make sure the timeout was increased by your change

**Comment by nader-ziada** [comment]
when I tried using an invalid image, it did timeout afer 5 minutes as expected
```
Timed out after 300.047s.
```

I should have said `300s` above in the comment, not `600s`, still don't get where the `1000s` came from, that's over 15 minutes

**Comment by CecileRobertMichon** [comment]
/hold cancel

let's track any other occurrences of this in PR tests once it merges

**Comment by nader-ziada** [comment]
it failed again with the timeout, started to think we don't need this PR, it improved the success rate, but the flake still happens, so I vote for just closing it without merging @CecileRobertMichon @devigned wdyt?

/hold

**Comment by devigned** [comment]
> I vote for just closing it without merging 

Agreed. Seems like there's a root cause that is only partially remedied by providing more time to the test scenarios.

**Comment by nader-ziada** [comment]
The timeout increase did not eliminate the flake 

/close

**Pull request closed without merging**
