### PR TITLE
Update e2e test versions of k8s to 1.26/1.27

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates the default versions of Kubernetes under test in e2e by one minor version.

```
Jul 26 22:59:06.210: INFO: 
  Resolved KUBERNETES_VERSION (set to stable-1.26) to v1.26.7
Jul 26 22:59:06.210: INFO: 
  Resolved KUBERNETES_VERSION_UPGRADE_FROM (set to stable-1.26) to v1.26.7
Jul 26 22:59:06.210: INFO: 
  Resolved KUBERNETES_VERSION_UPGRADE_TO (set to stable-1.27) to v1.27.4
Jul 26 22:59:06.210: INFO: 
  Resolved FLATCAR_KUBERNETES_VERSION (set to stable-1.26) to v1.26.3
```

*Update*: there is an issue we have not been able to pinpoint that affects Kubernetes v1.26.7, so this pins to v1.26.6.

**Which issue(s) this PR fixes**:

Refs #3762

**Special notes for your reviewer**:

Let's not consider merging this until well after the current dust has settled. I'm mostly curious whether the recent k8s v1.26.7 causes problems for us as v1.25.12 seems to.

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Jont828** [comment]
Seems like there's a problem with the Calico install, it's saying that the deployment isn't found. I'm not sure if it's failing to install, or if the deployment is just in an error state.

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-e2e-optional

AFAIK the 1.26 latest patch is also running into #3754 but let's see ^

**Comment by mboersma** [comment]
It appears that Kubernetes v1.26.7 has the same issue as v1.25.12: see #3754. I pinned the version at v1.26.6 to see how that does in e2e.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by nawazkh** [comment]
branch name 😆

**Pull request merged**
