### PR TITLE
Revert "Install azure disk CSI driver Helm chart with CAAPH"

### PR DESCRIPTION
**Pull request by jackfrancis**
Reverts kubernetes-sigs/cluster-api-provider-azure#4109

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve
/cherry-pick release-1.12

Let's do this to unblock the CSI driver tests for now and discuss how we can re-introduce this change in a non-breaking way

**Comment by jackfrancis** [comment]
Do we want this instead? https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4334

**Comment by jackfrancis** [comment]
replaced by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4334

**Pull request closed without merging**
