### PR TITLE
add release notes for CAPZ v1.15.0

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
/hold

aAggh I'm too late

**Comment by mboersma** [comment]
/hold cancel

Nvm, looks good

**Pull request merged**
