### PR TITLE
Use kubectl installed from makefile and remove unused install script

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- This is part of a multi-part PRs.
- This PR aligns the CI and install shell scripts in the repo to use `kubectl` binary installed in _hack/tools/bin/_ directory.
- Shell scripts also check/installs missing tools in _hack/tools/bin/_ dir, via `Makefile` recipes, before using it in the shell script.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes a part of #1192 
    - `kubectl`

**Special notes for your reviewer**:
- I have tried to keep the commits logically grouped for easier review. Let me know if I can improve it further. 🙂 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
- Does not change any image version.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
`ensure-kubectl.sh` was removed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1683.  The file doesn't appear to be referenced anywhere in the code base.

**Comment by CecileRobertMichon** [comment]
> Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1192

this in PR description will close #1192. You can change it to "Fixes part of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1192" or something else so it doesn't close the issue when this PR merges since this is only part of it.

**Comment by CecileRobertMichon** [comment]
@nawazkh can you please squash the commits for a cleaner commit history? In particular, the one that was reverted can be dropped completely

**Review by mboersma — COMMENTED** [review]
Don't we also need to change `kubectl` to `$(KUBECTL)` in the Makefile to ensure we're referencing the one under hack/tools/bin?

**Comment by nawazkh** [comment]
> Don't we also need to change `kubectl` to `$(KUBECTL)` in the Makefile to ensure we're referencing the one under hack/tools/bin?

Oh yes, I believe so. Thank you for pointing it out. Updating Makefile 🏃🏼

**Comment by nawazkh** [comment]
> Don't we also need to change kubectl to $(KUBECTL) in the Makefile to ensure we're referencing the one under hack/tools/bin?

Addressed via commit 41c19da2db9ffe22d0a72bbf615ab87f234dda34

**Comment by jsturtevant** [comment]
/retitle Use kubectl installed from makefile and remove unused install script
/lgtm

**Pull request merged**
