### PR TITLE
[release-1.7] don't reduce replicas if ext. managed MachinePool

### PR DESCRIPTION
**Pull request by mweibel**
Cherry-pick of #3250

**Release note**:

```release-note
fixes scaling down behavior when MachinePool is externally managed
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

validated changes against original PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3250/files

thank you for driving this all the way over the finish line @mweibel!

**Comment by CecileRobertMichon** [comment]
looks like that worked

/lgtm

**Pull request merged**
