### PR TITLE
:runner: Update default k8s version to 1.16.7

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Updates default Kubernetes version to the latest 1.16 patch, 1.16.7.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Updated default k8s version to 1.16.7
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
Any reason to not bump to 1.17.z?

**Comment by nader-ziada** [comment]
The version used in cluster-api main repo is 1.16.2

**Comment by CecileRobertMichon** [comment]
@justaugustus cluster-api is still on 1.16, and changing from 1.16.x to 1.17.y is a bigger move which we will certainly want to make at some point but this is just a small bump to use the latest patch of the   minor release capz is currently on.

**Comment by justaugustus** [comment]
SGTM. Do we want to backport as well?
/lgtm
/approve
/hold cancel

**Comment by CecileRobertMichon** [comment]
I don't think backport of patch versions is necessary for now (we'd be doing a lot of backports) but we can definitely do one if someone has a specific need for this version or if it fixes a critical bug, and re-evaluate as the project becomes more mature. Wdyt?

**Comment by justaugustus** [comment]
Yep, yep, SGTM!

**Pull request merged**
