### PR TITLE
Add shysank to maintainers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: @shysank has developed a deep knowledge of the CAPZ codebase and has been making quality contributions both as a reviewer and as an author for over 6 months now. This PR proposes promoting Shyam to maintainer of the project. Thanks for all your contributions @shysank! 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

a week for lazy consensus

**Comment by devigned** [comment]
+1 yay!!

**Comment by nader-ziada** [comment]
+1 from me 🎉🎉

**Comment by CecileRobertMichon** [comment]
just need an lgtm label to merge this

**Pull request merged**
