### PR TITLE
Go linter check

### LINKED ISSUE #1443: Enforce comments on the codebase
Enable linters for enforcing adding a comment to exported methods.

Relevant cluster-api PRs:
kubernetes-sigs/cluster-api#4631
kubernetes-sigs/cluster-api#4669

/milestone Next
/priority backlog
/good-first-issue
/help

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**
This PR checks if the go linter enforces on adding comments on public exported functions or packages.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1443

**Special notes for your reviewer**:
The lint was ran locally and it failed when a exported function was missing comments. The result can be found in the comments.

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sayantani11** [comment]
```sh
INFO [runner] linters took 23.8855871s with stages: goanalysis_metalinter: 23.8775484s                                                                                  pkg/record/recorder.go:37: File is not `gofmt`-ed with `-s` (gofmt)                                                                                                                                                                                                                                                                             pkg/record/recorder.go:38:1: exported function `InitFromRecorder` should have comment or be unexported (golint)                                                         func InitFromRecorder(recorder record.EventRecorder) {                                                                                                                  ^                                                                                                                                                                       INFO File cache stats: 337 entries of total size 2.5MiB                                                                                                                 INFO Memory: 1200 samples, avg is 325.3MB, max is 2228.9MB                                                                                                              INFO Execution took 2m6.961668s
```

**Comment by sayantani11** [comment]
```sh
INFO [runner] linters took 23.8855871s with stages: goanalysis_metalinter: 23.8775484s
pkg/record/recorder.go:37: File is not `gofmt`-ed with `-s` (gofmt) 
pkg/record/recorder.go:38:1: exported function `InitFromRecorder` should have comment or be unexported (golint)
 func InitFromRecorder(recorder record.EventRecorder) { 
          ^
INFO File cache stats: 337 entries of total size 2.5MiB 
 INFO Memory: 1200 samples, avg is 325.3MB, max is 2228.9MB 
INFO Execution took 2m6.961668s                       
```

**Comment by shysank** [comment]
linter fails as expected https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1659/pull-cluster-api-provider-azure-test/1432391589749067776

```
pkg/record/recorder.go:37: File is not `gofmt`-ed with `-s` (gofmt)
pkg/record/recorder.go:38:1: exported function `InitFromRecorder` should have comment or be unexported (golint)
func InitFromRecorder(recorder record.EventRecorder) {
^
```

**Comment by sayantani11** [comment]
Closing the PR as the linter fails when the comments are missing.
Refers to #1443

**Pull request closed without merging**
