### PR TITLE
bump CAPI to v1.3.5

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates the cluster-api dependency to recent release v1.3.5. See https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.5

**Which issue(s) this PR fixes**:

Closes #3215

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
bump CAPI to v1.3.5
```

### CODE REVIEW

**Review by marosset — APPROVED** [review]
/lgtm

**Comment by nawazkh** [comment]
This PR should unblock other dependencies updates too! Thanks for this PR!
/lgtm++

**Comment by CecileRobertMichon** [comment]
interesting the last failure in capi e2e looks like #3108 

/retest

**Comment by mboersma** [comment]
/retest

These look like provisioning timeouts not related to this change, but let's see.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
