### PR TITLE
💎 Remove unused AzureCluster bastion status field

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Bastion VMs have never been supported or implemented in CAPZ, and this field was never used, it was brought over from CAPA types in v1alpha1. Since this is a status field, it was never settable by users and we know that no project depends on it so it should not be breaking, even though it is an API change. 

/cc @cpanato  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #165 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Remove unused AzureCluster bastion status field
```

### CODE REVIEW

**Review by devigned — APPROVED** [review]
lgtm

**Review by mboersma — APPROVED** [review]
👍

**Comment by mboersma** [comment]
> sigs.k8s.io/cluster-api-provider-azure/api/v1alpha3
>  Incompatible changes:
>  - AzureClusterStatus.Bastion: removed
> + EXIT_VALUE=1
> + set +o xtrace

D'oh.

**Review by cpanato — APPROVED** [review]
late to the party
/lgtm

**Pull request merged**
