### PR TITLE
Reuse logic in ci scripts

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

We have a lot of logic that is same across our CI scripts.  Some of it was shared but not all of it.  This consolidates so of the logic.  Most of this logic is used to ensure that PROW and related templates are set up properly.

An example of how this helps consistency would be our `ci-entrypoint.sh`:  the [docs ](https://capz.sigs.k8s.io/developers/development.html#running-custom-test-suites-on-capz-clusters) say `AZURE_SSH_PUBLIC_KEY_FILE` is used but the logic wasn't actually using it.  As well as wasn't setting the correct keys for windows: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/2a9b44c7c24758eec051abd01c64da32c8144c3e/hack/create-dev-cluster.sh#L59-L65

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Each change is in a separate commit, which makes for easier reviewing

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
thanks for the cleanup 🧹 !

/lgtm
/approve

**Pull request merged**
