### PR TITLE
ci: add ensure-tags.sh and remove upstream test from ci-entrypoint.sh

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

 

 
**What type of PR is this?**

**What this PR does / why we need it**:

/kind failing-test

Fixes failing tests in https://testgrid.k8s.io/provider-azure-master-signal#capz-azure-disk-machinepool by adding `ensure-tags.sh` to ensure tag-related environment variables are populated before deploying workload cluster. Also removing upstream test-related code from ci-entrypoint.sh since it appears that it's now handled by `make test-conformance`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/hold

pending optional conformance test success

**Comment by nader-ziada** [comment]
conformance passed, but the windows e2e failed, will give it another try

/test pull-cluster-api-provider-azure-e2e-windows

**Pull request merged**
