### PR TITLE
update pre-commit config

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- This PR will use of project's hack/tool/golang-ci instead of pre-commit's golang-ci for listing. 
- This is also removes dependency on updating pre-commit framework every time golang-ci linter is updated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
This PR will also update the output on running `git commit ...`. Developers will see something like below
```bash
Detect hardcoded secrets.................................................Passed
Test shell scripts with shellcheck...................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
pylint...............................................(no files to check)Skipped
Verify boilerplate.......................................................Passed
Verify modules...........................................................Passed
Verify shellcheck........................................................Passed
Verify tiltfile..........................................................Passed
Verify codespell.........................................................Passed
Lint codebase............................................................Passed
```

**Review by willie-yao — APPROVED** [review]
/lgtm

**Pull request merged**
