### PR TITLE
Add devigned as reviewer

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Thanks for all your contributions so far @devigned! 

/hold for reviews / discussion

/assign @justaugustus @awesomenix @juan-lee @nader-ziada @serbrech @vincepri 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by detiber** [comment]
+1 from me

**Comment by vincepri** [comment]
💯

**Comment by justaugustus** [comment]
Huge +1 for David!

/lgtm
/approve

**Comment by devigned** [comment]
😊  Thank you!

**Comment by nader-ziada** [comment]
+1

**Comment by justaugustus** [comment]
/hold cancel

@CecileRobertMichon -- We'll need to make accompanying k/org and k/k8s.io. Do you want to me to do those or would you like to take care of them?

**Pull request merged**
