### PR TITLE
Update dependencies including cluster-api to v0.4.1

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- update cluster-api to v0.4.1
- update other related dependencies 
- 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update cluster-api dependency to v0.4.1
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
tried to use 1.22.0 for e2e to see if that would help with upgrade test, but still didn't work, need to investigate further

**Comment by CecileRobertMichon** [comment]
this is failing because of #1555

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api/commit/1c39866774726af917ec2c1cac44dbaa876097a0 is in v0.4.1 though so I would expect it to fix some of it

**Comment by CecileRobertMichon** [comment]
> kubernetes-sigs/cluster-api@1c39866 is in v0.4.1 though so I would expect it to fix some of it

only the KCP upgrade jobs are failing so that's good, this is because of #1555. We're trying to upgrade from 1.19 to 1.21 right now which is not allowed.

**Comment by CecileRobertMichon** [comment]
let's merge this, I'll tackle the upgrade test in #1566 

/lgtm
/approve

**Pull request merged**
