### PR TITLE
Don't useExperimentalRetryJoin

### LINKED ISSUE #998: Test if experimentalRetryJoin still needed for K8s 1.19+
/kind feature

**Describe the solution you'd like**
In 1.19+ retry support was added to kubeadm: https://kubernetes.slack.com/archives/C8TSNPY4T/p1601486982126900.  We should test 1.19 to see if the `useExperimentalRetryJoin` is still required as was added for https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/832 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/833.

**Anything else you would like to add:**
This is related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1993 and Window support https://github.com/kubernetes-sigs/cluster-api/pull/3616#discussion_r501017446

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 1.19+
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nader-ziada**
/kind feature

 

 
**What type of PR is this?**

**What this PR does / why we need it**:
- trying out the e2e tests without using `useExperimentalRetryJoin`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #998  

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Remove the setting for using useExperimentalRetryJoin
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
/hold 
for running tests a few times

**Comment by CecileRobertMichon** [comment]
The tests have been pretty flaky _with_ the retry lately so I wouldn't be surprised if we see flakes without it too...

**Comment by nader-ziada** [comment]
/test pull-cluster-api-provider-azure-e2e

looks like it was a flake since `pull-cluster-api-provider-azure-e2e-full` passed

**Comment by CecileRobertMichon** [comment]
Let's hold until #991 merges so we can validate with the KCP flake improvements

**Comment by CecileRobertMichon** [comment]
@nader-ziada should we run a series of tests similar to what we did in #1197 before merging this to see if we get any flakes?

**Comment by nader-ziada** [comment]
Pass 1
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
capi failed for the Pass 1

Pass 2
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 2 again after rebase

/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 2 again after rebase of #1219 

/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 2 after rebase all passed

Pass 3
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 3 all passed

Pass 4
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 4 capi and windows failed 

Pass 5
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 5 capz e2e full failed 

Pass 6
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-e2e-windows
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by CecileRobertMichon** [comment]
@nader-ziada #1232 will make it easier to quickly identify which flakes are due to bootstrap errors vs. other issues

**Comment by nader-ziada** [comment]
rebased to get latest

**Comment by nader-ziada** [comment]
once the capi issue is fixed, https://github.com/kubernetes-sigs/cluster-api/pull/4367 I think should be good to go

**Comment by nader-ziada** [comment]
Pass 7 after getting fix in capi for mhc

/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 8 after rebase
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 9
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
`capi` is actually passing, its the GPU test that fails which should not be related

**Comment by nader-ziada** [comment]
Pass 10
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 10 - everything passed

Pass 11
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
Pass 12
/test pull-cluster-api-provider-azure-e2e-full
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
the last few runs, only the GPU tests failed sometimes which is not related to this

**Comment by nader-ziada** [comment]
/hold cancel

@shysank @CecileRobertMichon I think this is ready to merge now, wdyt?

**Comment by shysank** [comment]
One small clarification: `useExperimentalRetryJoin` is not needed for k8s > 1.19. I understand the part where it is removed from test templates. For other templates, is it expected for the user to know about including this setting when using k8s < 1.19?

**Comment by shysank** [comment]
lgtm with one clarification

**Comment by CecileRobertMichon** [comment]
> One small clarification: useExperimentalRetryJoin is not needed for k8s > 1.19. I understand the part where it is removed from test templates. For other templates, is it expected for the user to know about including this setting when using k8s < 1.19?

useExperimentalRetryJoin is not needed for k8s >**=** 1.19

Given that 1.18 & 1.17 would be out of the support skew for v1alpha4 (and < 1.17 won't even work - https://github.com/kubernetes-sigs/cluster-api/issues/4423#issuecomment-814114934), it should be safe to remove it from the example templates. It would be good to add a note in [the CAPI bootstrap kubeadm docs](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/tasks/kubeadm-bootstrap.md#additional-features) about turning on the retries for k8s clusters < 1.19. 

https://github.com/kubernetes-sigs/cluster-api/issues/4444 is tracking defining the policy for k8s version support.

**Pull request merged**
