### PR TITLE
[release-1.9] add machine pool wait to default e2e parameters

### PR DESCRIPTION
**Pull request by mboersma**
This is a manual cherry-pick of #3761.

/assign @nojnhuh 

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/retitle [release-1.9] add machine pool wait to default e2e parameters

**Review by nojnhuh — COMMENTED** [review]
Thank you Matt!

/lgtm
/approve

**Comment by nojnhuh** [comment]
That's the first I've tried to approve but I guess it didn't take. I wonder if it's because I'm not a "maintainer" on the release branch? Not a big deal, just trying to get a feel for how that works.

**Comment by mboersma** [comment]
> because I'm not a "maintainer" on the release branch?

Yes, I think that's it. You should be able to approve against `main` though. We could cherry-pick the `OWNERS` changes if need be.

**Comment by mboersma** [comment]
The AKS test failure is addressed by #3772.

**Pull request merged**
