### PR TITLE
Update kind-with-registry.sh

### PR DESCRIPTION
**Pull request by lzhecheng**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Specify resource group when `az storage account show`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
/lgtm
/approve

/hold
merge after ci-entrypoint test passes!

**Comment by jackfrancis** [comment]
/hold cancel

thank you @lzhecheng!

**Pull request merged**
