### PR TITLE
test managed machine pool delete in e2e

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: This PR adds new e2e test coverage testing that a MachinePool can be successfully deleted from a managed cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by willie-yao** [comment]
Is there a specific reason why we're only deleting the managed machine pool in the public ip test and not the other AKS tests? Otherwise, the deletion logic looks good to me!

**Comment by nojnhuh** [comment]
> Is there a specific reason why we're only deleting the managed machine pool in the public ip test and not the other AKS tests? Otherwise, the deletion logic looks good to me!

There's no hard requirement for that decision, I don't think. Adding the delete here does make the test a bit more "symmetrical" though since that's where it's created. And I can see value in testing deleting machine pools both with and separately from the cluster.

Going forward, I think a good rule of thumb is to introduce minimal churn while keeping each spec from having any lingering side effects that bleed into other specs. By "minimal churn" I mean doing things like reusing a cluster or machine pool that already exists if possible to keep both costs down and velocity high by doing less work overall. That would justify having the manual machine pool scaling tests reuse the machine pools created with the cluster since we can scale them back to their initial state, but have the public IP prefix test create its own machine pool in the same cluster since those public IP fields on the machine pool are immutable and we'd otherwise need to tweak one of the original machine pools which is presumably used in many other tests.

**Comment by jackfrancis** [comment]
@willie-yao @nojnhuh I love the idea of having these discrete behaviors be tested discretely, perhaps serially randomized per-test. Good thinking, let's aim for that in the future.

**Comment by CecileRobertMichon** [comment]
> @willie-yao @nojnhuh I love the idea of having these discrete behaviors be tested discretely, perhaps serially randomized per-test. Good thinking, let's aim for that in the future.

I'm late to the party but... 100%. I would love us to consider how to do this for non-aks tests too, we should get to a point where it's not one feature == one test template but rather we have test specs we can use to add/remove node pools with a specific feature on any cluster "shape".

**Pull request merged**
