### PR TITLE
Add sonasingh46 to maintainers

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

@sonasingh46 has developed a deep knowledge of the CAPZ codebase and has been making quality contributions both as an author and a reviewer for almost two years now. This PR proposes promoting Ashutosh to a maintainer of the project.

Thanks for all your contributions @sonasingh46!

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Kudos on your great work @sonasingh46!
🤜🏼 🤛🏼 <- fist bump
A glad /lgtm

**Comment by CecileRobertMichon** [comment]
Welcome @sonasingh46, and thank you for all your contributions thus far!

/lgtm
/approve

/hold for consensus

**Comment by willie-yao** [comment]
/lgtm

+1 Well deserved @sonasingh46!! Thanks for your amazing work in CAPZ 🚀

**Pull request merged**
