### PR TITLE
refactor(manager): set machinepool true as default

### PR DESCRIPTION
**Pull request by KOREAN139**
- MachinePool feature flag is true as default since CAPI v1.7.0, but capz-contoller-manager deployment still uses false as default.
- It causes error `spec: Forbidden: can be set only if the Cluster API 'MachinePool' feature flag is enabled` when user does not specify MachinePool feature flag true in capz-controller-manager.
- As CAPI v1.7.0 has been GA around six months, It should set MachinePool feature flag as true to make seamless UX.
- I left manager manifest in test as it is since it set MachinePool feature flag as true using `EXP_MACHINE_POOL`.

references
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.0 
https://github.com/kubernetes-sigs/cluster-api/pull/10141

related slack thread
https://kubernetes.slack.com/archives/CEX9HENG7/p1727200579137939

 

 
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Closes #4911

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
refactor(manager): set machinepool true as default
```

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @KOREAN139--we had #4911 but it was never updated.

Could you make a similar change to `hack/observability/opentelemetry/controller-manager-patch.yaml` and update any related docs to match? See the comment from #4911:

> Can we add a note in the docs that this is now enabled by default? https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/topics/managedcluster.md?plain=1#L59
> 
> There are probably a few other places in the docs that need updating as well.

**Comment by KOREAN139** [comment]
@mboersma Sure! I'll checked the #4911 as well, and update `hack/observability/opentelemetry/controller-manager-patch.yaml` & related docs.

**Comment by KOREAN139** [comment]
Just updated following documents.

- docs/book/src/developers/development.md
Add note that its default value is true, need to set false if user wants to disable this
- docs/book/src/managed/managedcluster.md
Add note that `MachinePool` feature flag is enabled by default
- docs/book/src/self-managed/machinepools.md
Add note that `MachinePool` feature is in Beta, and enabled by default. Add reference for this too.

Let me know if there's any documents left to update! @mboersma

**Comment by KOREAN139** [comment]
Just applied your suggestion, and squashed commits @willie-yao !

**Comment by nawazkh** [comment]
🚢 it! 
lgtm!

**Comment by willie-yao** [comment]
/lgtm
/approve

Thank you! 🚀

**Pull request merged**
