### PR TITLE
Add Name and owner tags to route tables

### LINKED ISSUE #2368: Tag managed route tables as owned
/kind feature

**Describe the solution you'd like**
Tag managed route tables as owned i.e. sigs.k8s.io_cluster-api-provider-azure_cluster__clustername_ "owned"

**Anything else you would like to add:**
Child of #2354

### PR DESCRIPTION
**Pull request by josh-ferrell**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2368 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Add Name and owner tags to route tables
```

### CODE REVIEW

**Comment by josh-ferrell** [comment]
@CecileRobertMichon @jackfrancis or @alexeldeib it would be helpful to get a 2nd set of eyes on this PR. I'm not sure if the apidiff and ci-entrypoint jobs should pass. 

I also left out the Role tag since I wasn't sure if it was applicable.

**Comment by CecileRobertMichon** [comment]
ci-entrypoint should pass, looks like the windows machines failed to come up in the last run which seems like a flake unrelated to your changes 

```
Waiting for 1 control plane machine(s), 2 worker machine(s), and 2 windows machine(s) to become Ready
NAME                              STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
capz-ih63ui-control-plane-mxrc8   Ready    control-plane,master   30m   v1.22.1   10.0.0.4      <none>        Ubuntu 20.04.3 LTS   5.8.0-1039-azure   containerd://1.5.4
capz-ih63ui-md-0-f6gwj            Ready    <none>                 28m   v1.22.1   10.1.0.6      <none>        Ubuntu 20.04.3 LTS   5.8.0-1039-azure   containerd://1.5.4
capz-ih63ui-md-0-lfs96            Ready    <none>                 28m   v1.22.1   10.1.0.5      <none>        Ubuntu 20.04.3 LTS   5.8.0-1039-azure   containerd://1.5.4
```

/retest

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by josh-ferrell** [comment]
e2e doesn't appear affected by code change but retesting just incase.

**Pull request merged**
