### PR TITLE
Bump kubebuilder tools to v1.23.3

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: My kubebuilder-tools install was corrupted and I noticed the version we were using is quite old. v1.23.3 is the same version CAPI v1.1.4 is using. Not sure if there is a more recent compatible version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Jont828** [comment]
This change seems pretty straightforward. Do you know what's going on with the test failure?

**Comment by CecileRobertMichon** [comment]
Not sure but it's the same failures we were seeing in #2374. Probably something in the new version breaks our tests, will need to investigate.

**Comment by CecileRobertMichon** [comment]
will close for now

**Pull request closed without merging**
