### PR TITLE
Use GetAtScope() to get tags when checking if a resource is managed

### LINKED ISSUE #1899: Migrate from "getting full resource to get tags" to "just getting tags at resource scope"
This is based on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1745#discussion_r741488690

For example, in this method

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1a16f42bc104b6a8f5931dcb36f7c5ca184ff4e3/azure/services/publicips/publicips.go#L142-L151

We need to replace `GET` public IP API call (`s.Client.Get`) with `GET` Tags At Scope API call with Public IP as scope to just get the tags as we want only tag data to check if Public IP is managed or not. A `GET` public IP API call is heavier with more data and hence unnecessary.

References -
- `GET` public IP API call - https://docs.microsoft.com/en-us/rest/api/virtualnetwork/public-ip-addresses/get
- `GET` Tags At Scope API call - https://docs.microsoft.com/en-us/rest/api/resources/tags/get-at-scope

cc @CecileRobertMichon

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?** 
/kind feature

**What this PR does / why we need it**: Use GetAtScope() to get tags when checking if a resource is managed so we don't need to get the entire resource.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1899 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Use GetAtScope() to get tags when checking if a resource is managed
```

### CODE REVIEW

**Comment by Jont828** [comment]
@CecileRobertMichon I think this is ready for a final pass of reviews!

**Comment by jackfrancis** [comment]
This is such an awesome, often-underappreciated change, thanks @Jont828!

/lgtm

@CecileRobertMichon do we feel confident merging this in at the end of the 1.6 dev cycle? I think the mock tests tell the story here that this is non-breaking, but wonder if want more mileage on this before we release it.

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm 

@Jont828 could you please squash?

**Pull request merged**
