### PR TITLE
✨ Enable VM boot diagnostics

### LINKED ISSUE #606: enable vm bootdiagnostics
/kind feature

**Describe the solution you'd like**

Azure VM and VMSS support a boot diagnostics feature which streams cloud init logs and boot time output into a storage account. This is incredibly useful for debugging bootstrapping failures when using cloud init, as all the logs get exfiltrated for the machine. 

Consider enabling this for AzureMachine and AzureMachinePool.

https://godoc.org/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute#DiagnosticsProfile

/help-wanted
/good-first-issue

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**:  Azure VM and VMSS support a boot diagnostics feature which streams cloud init logs and boot time output. This is incredibly useful for debugging bootstrapping failures when using cloud init, as all the logs get exfiltrated from the machine.

This PR enables that option on all VM/VMSS deployments using the managed storage account option (recommended) which means there is no need to create a storage account. In the future, we can consider enabling a custom storage account for users to provide their own storage if there is demand for that flexibility. 

Note that boot diagnostics also work on Windows VMs https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/boot-diagnostics.

Screen Shot 2020-08-26 at 5 14 10 PM

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #606

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Enabled VM boot diagnostics
```

### CODE REVIEW

**Comment by mboersma** [comment]
> using the managed storage account option (recommended) which means there is no need to create a storage account

So judging from the content of this PR, managed storage is the silent default? It sounds like good magic but I confess I'm clueless how it works and couldn't find specific info in Azure docs either.

**Comment by CecileRobertMichon** [comment]
I think it's new

Screen Shot 2020-08-27 at 10 08 02 AM

**Comment by nader-ziada** [comment]
tried creating a cluster with this branch and got a very useful log about the start of the machine in the `Boot diagnostics` sub menu on the Azure portal, its kind of too big to paste here and has keys as well

/lgtm

**Comment by CecileRobertMichon** [comment]
/approve

self-approving since 2 approvers have said lgtm :)

**Comment by CecileRobertMichon** [comment]
/retest 

kind error

**Pull request merged**
