### PR TITLE
[release-1.8] Cherry-picking 1d6c199 into release-1.8

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**

/kind cleanup 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Stop setting `WindowsHostProcessContainers` feature gate everywhere
```

Cherry pick of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3301

### CODE REVIEW

**Comment by marosset** [comment]
I'm cherry-picking this so we can also cherry-pick https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3388 so that we can use the `NODE_FEATURE_GATES` env-var in a PR job and keep that PR job on a CAPZ release instead of referencing main

**Comment by jsturtevant** [comment]
is 1.22 still used in 1.8 branch for any of the capz tests?  otherwise lgtm

**Comment by CecileRobertMichon** [comment]
> is 1.22 still used in 1.8 branch for any of the capz tests?

No: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/release-1.8/test/e2e/config/azure-dev.yaml#L152

**Pull request merged**
