### PR TITLE
Refactor and add missing test coverage for validateclustertemplatespec

### LINKED ISSUE #3371: Refactor and add missing test coverage for oneSubnetWithoutNatGateway
/kind cleanup

**Describe the solution you'd like**
Currently, azureclustertemplate_validation.go is missing unit tests in the following areas:

- validateClusterTemplateSpec() is missing tests regarding [oneSubnetWithoutNatGateway](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_validation.go#L58).
- The [code block](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_validation.go#L58-L68) containing `oneSubnetWithoutNatGateway` should be moved to its own helper function for clarity.

How to improve test coverage:

- Create a new test `TestOneSubnetWithoutNatGateway` in [azureclustertemplate_validation_test.go](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_validation_test.go)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Nilesh-chaudhary**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR adds test for https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_validation.go#L58 and move code block https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azureclustertemplate_validation.go#L58-L68  to its helper function

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3371

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

Great work @Nilesh-chaudhary! 🚀

**Review by mboersma — APPROVED** [review]
/approve

**Comment by mboersma** [comment]
This might need to be rebased on #3625 for codecov/patch to pass.

**Pull request merged**
