### PR TITLE
clean up hack/tools go.mod

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Unfortunately I approved https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2487 without noticing that the `go.mod` in `hack/tool` was not sanitized via `go mod tidy`. This PR addresses that.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

I can reproduce the same thing locally. Maybe `make modules` and `make verify-modules` should also be looking at /hack/tools?

**Comment by CecileRobertMichon** [comment]
```
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/hack/tools@v0.0.0-20220202124422-fe7656c044e1/conversion-verifier/main.go:24:2: missing go.sum entry for mod
```

looks like this change is causing make verify to fail

**Comment by mboersma** [comment]
Doing just this seems to have resolved the hack/tools import issues, at least for me locally:

```
cd hack/tools
go mod download sigs.k8s.io/cluster-api/hack/tools/conversion-verifier
```

Although it did refresh numerous packages, which hopefully doesn't present a problem for cherry-picking this change.

**Comment by CecileRobertMichon** [comment]
> Hopefully that doesn't present a problem for cherry-picking this change

why do we need this change cherry-picked?

**Comment by mboersma** [comment]
When @jackfrancis and I were looking at failed cherry-picks this morning, it seemed that upgrading Go to 1.18.3 might fix a `go mod` issue. But now I'm unclear on whether there is actually a pileup of PRs here.

That `hack/tools/go.mod` wasn't totally up-to-date is a distinct problem that this and #2547 address. Maybe cherry-picking isn't a concern.

**Comment by CecileRobertMichon** [comment]
Yeah seems like the failures in cherry-picks are unrelated, AFAIK go 1.18.3 isn't in release-1.4 and there were no failed tests there, and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2542 seems to have been fixed now that https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2544 merged

we definitely want this in main (and if v1.18.3 gets cherry-picked we'll need this to cherry-pick with it, but I don't know that we should if we don't have to).

/lgtm
/approve
/tide merge-method-squash

**Pull request merged**
