### PR TITLE
Add more linters and config from CAPI

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Adds two linters and some configuration directives from CAPI's [`.golangci.yml`](https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml) so the development experience is more consistent between the two projects.

In particular, enabling `"experimental"` for `gocritic` led to many code changes. I thought they were all good ones, but please let me know if you disagree.

**Which issue(s) this PR fixes**:

See also #2534

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

This won't pass `make lint` after #2534 merged.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
