### PR TITLE
ensure more uniqueness for CI storage accounts

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

This PR adds more uniqueness robustness around the storage accounts created during CI runs.

In response to errors like this:

```
ERROR: (StorageAccountAlreadyTaken) The storage account named oidcissuer12473 is already taken.
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
I am curious, Is this PR making the storage accounts more unique since the storage accounts do not get recycled after deletion?

I was reading more about `$RANDOM`, deduced that RANDOM is sort of pseudo Random. 

Then came across ` /dev/urandom` used in generating session IDs, encryption keys etc. 
Can we experiment with below? Maybe assign 
```bash
random_number=$(od -An -N4 -tu4 < /dev/urandom | tr -d ' ')
echo $random_number
```

**Comment by nawazkh** [comment]
> I am curious, Is this PR making the storage accounts more unique since the storage accounts do not get recycled after deletion?
> 
> I was reading more about `$RANDOM`, deduced that RANDOM is sort of pseudo Random.
> 
> Then came across ` /dev/urandom` used in generating session IDs, encryption keys etc. Can we experiment with below? Maybe assign
> 
> ```shell
> random_number=$(od -An -N4 -tu4 < /dev/urandom | tr -d ' ')
> echo $random_number
> ```

Don't wish to block this PR, I can open up another one to experiment this. 🚢

**Comment by jackfrancis** [comment]
@nawazkh happy to experiment/optimize the way we uniquely name the storage accounts

According to this documentation we have 24 chars to use, and (importantly) storage accounts aren't namespaced by resource group, so our existing naming strategy is producing collisions w/ live storage accounts.

- https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#storage-account-name

If we use a `capzcioidcissuer` prefix, we have 8 chars avail for us, does /dev/urandom support random output with a specified number of integers?

**Comment by nawazkh** [comment]
> According to this documentation we have 24 chars to use, and (importantly) storage accounts aren't namespaced by resource group, so our existing naming strategy is producing collisions w/ live storage accounts.

Thank you for the context. TIL _"storage accounts aren't namespaced by resource group"_

----

> If we use a `capzcioidcissuer` prefix, we have 8 chars avail for us, does /dev/urandom support random output with a specified number of integers?

Yes it can. We can try 
```bash
random_number=$(od -An -N4 -i /dev/urandom | tr -d ' ' | head -c 8)
```

`head -c 8` will ensure that the final result is limited to 8 digits.

**Comment by jackfrancis** [comment]
@nawazkh does it support unsigned int output so we don't get a hypen?

**Comment by nawazkh** [comment]
Yes, good catch, we can try `random_number=$(od -An -N4 -tu4 /dev/urandom | tr -d ' ' | head -c 8)` for signed integer.

**Pull request merged**
