### PR TITLE
[release-1.9] optional flatcar tests will create a loadbalancer

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug
/kind documentation
- Also a cherry-pick

**What this PR does / why we need it**:
- This is a cherry-pick PR of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3386

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
flatcar: Specify `caCertDir` location while installing “external” cloud provider for Azure
```

### CODE REVIEW

**Comment by willie-yao** [comment]
/retitle [release-1.9] optional flatcar tests will create a loadbalancer

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
