### PR TITLE
Bump CAPI to v1.2.1

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Comment by jackfrancis** [comment]
@CecileRobertMichon is the failing upgrade test blocking merge (it's not a required test so it shouldn't)... If so you should be able to rebase and I'll do the /lgtm and /approve dance again

**Comment by CecileRobertMichon** [comment]
/hold 

it's not blocking but I'd like a pass since this is changing CAPI version

/test pull-cluster-api-provider-azure-apiversion-upgrade 

No need to rebase, prow should do it's thing and rebase before running the job...

**Comment by CecileRobertMichon** [comment]
/hold cancel

apiversion upgrade test passed

**Review by mboersma — COMMENTED** [review]
/lgtm++

**Pull request merged**
