### PR TITLE
Only look at Group and Kind when checking a reference

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Only look at Group and Kind when checking a reference. Do not look at Version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Only look at Group and Kind when checking a reference
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Is this changing any user facing behaviors and/or fixing any bugs? If so can you please add a release note?

**Comment by vincepri** [comment]
I can't edit the release note, but basically this is a bug if you have a cluster with an v1alpha2 owner that hasn't been updated yet. It should be a transitory issue, given that controllers update their OwnerReferences when they get reconciled, although this logic is technically more correct than looking at the version number.

There shouldn't be any user-facing changes.

**Comment by CecileRobertMichon** [comment]
updated release note

/approve

**Pull request merged**
