### PR TITLE
[release-1.5] Cleanup remote peerings when resource group is deleted

### PR DESCRIPTION
**Pull request by jackfrancis**
This is an automated cherry-pick of #2767

/assign jackfrancis

```release-note
Cleanup remote peerings when resource group is deleted
```

### CODE REVIEW

**Review by jackfrancis — COMMENTED** [review]
/lgtm
/approve

**Comment by jackfrancis** [comment]
whoops, I can't review my own PR (forgot I manually created this cherry-pick)

/assign @mboersma

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
