### PR TITLE
Rename "asyncpoller" package to "async"

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Now that all services have converted to SDKv2, the SDKv1-based `async` framework is no longer used. This removes the old code to avoid confusion and renames `asyncpoller` to `async` to save typing.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Maybe we want to stick with `asyncpoller` and not rename in-place? I made two separate commits in case of that. Please let me know your opinions.

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
If we think this is a good idea, we might want to get this in for the v1.11 release so that we don't make future cherry-picks more difficult.

**Comment by mboersma** [comment]
/milestone v1.11

(He said hopefully.)

**Review by nojnhuh — COMMENTED** [review]
/lgtm

+1 to keeping the new one as `async` over `asyncpoller`. Less to type 🤠

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
