### PR TITLE
enable metrics scraping via prometheus

### LINKED ISSUE #1222: Enable `metrics`-scraping
/kind feature

**Describe the solution you'd like**
I created [PR 📖 document metrics scraping and enable metrics services via annotations](https://github.com/kubernetes-sigs/cluster-api/pull/4247) at CAPI and also some PRs on other infraproviders to document how to setup all the RBAC stuff together with `kube-rbac-proxy` and `prometheus` to scrape metrics from CAPI containers.

The annotation already exist at `capz` but was removed last year with [this commit](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/2cc75f4e6be222b7340139614adfc7b03f8cb612) in PR #1019 by @devigned 

Using the prometheus-operator is definitely a valid solution to bring some observability in a cluster, but imho using a "simple" `prometheus` deployment/statefulset with a very common config is also very proven in a k8s environment.

would you accept a PR, where i set some annotations on the `metrics`-service?

```yaml
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
``` 

- new PRs:
  - [CAPI](https://github.com/kubernetes-sigs/cluster-api/pull/4247)
  - [Packet](https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/231) - merged
  - [IBM Cloud](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/310) - merged
  - [DigitalOcean](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/240) - merged
- `annotation` already exist:
  - [AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/rbac/auth_proxy_service.yaml)
  - [Metal3](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/config/rbac/auth_proxy_service.yaml)
  - [GCP](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/config/rbac/auth_proxy_service.yaml)
  - [OpenStack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/rbac/auth_proxy_service.yaml)
  - [vSphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/config/rbac/auth_proxy_service.yaml)

### PR DESCRIPTION
**Pull request by bavarianbidi**
prometheus as the defacto standard for monitoring in a kubernetes
environment is generally configured to scrape metrics only if the
observed targets (pods, service, endpoints) has set proper annotations.

 

 
**What type of PR is this?**

/kind other

**What this PR does / why we need it**:
with PR [#4247](https://github.com/kubernetes-sigs/cluster-api/pull/4247) in capi we introduced some notes about monitoring/scraping metrics via prometheus. This PR will add the relevant annotations to make it work in a defacto default prometheus setup.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1222

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
metrics service got some additional annotations which can be used by prometheus for a more fine-grained scrape configuration
```

Signed-off-by: Constanti, Mario <mario.constanti@daimler.com>

> Mario Constanti [mario.constanti@daimler.com](mailto:mario.constanti@daimler.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@bavarianbidi thanks for the PR, can you please add a release note in the PR description?

**Comment by bavarianbidi** [comment]
> @bavarianbidi thanks for the PR, can you please add a release note in the PR description?

done

**Review by devigned — APPROVED** [review]
/lgtm
/approve

Thank you for the PR!

**Pull request merged**
