### PR TITLE
fix subnet test check by ignoring order

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

This PR updates a check in a unit test against a slice to ignore the order of elements since that is not deterministic because the slice is constructed by iterating over a map.

Running the test 100 times is enough to get it to fail every time for me:
```
go test ./api/v1beta1 -run TestClusterSubnetsValid/no_subnet -count 100 -failfast
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [X] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

I had to look up the Gomega docs for [`ConsistOf`](https://onsi.github.io/gomega/#consistofelement-interface) (versus [`ContainElements`](https://onsi.github.io/gomega/#containelementselement-interface)). 👍🏻

**Comment by nawazkh** [comment]
> /lgtm
> 
> I had to look up the Gomega docs for [`ConsistOf`](https://onsi.github.io/gomega/#consistofelement-interface) (versus [`ContainElements`](https://onsi.github.io/gomega/#containelementselement-interface)). 👍🏻

TIL, thanks!
Isn't `ContainElements` less stricter and beneficial here?

**Comment by mboersma** [comment]
> Isn't `ContainElements` less stricter and beneficial here?

It is stricter, because it requires all elements to be the same (not a subset). I *think* this is what is desired in this unit test.

**Pull request merged**
