### PR TITLE
test: simplify capz provider metadata.yaml

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup
/kind documentation

**What this PR does / why we need it**:

This PR simplifies the `metadata.yaml` API version contract spec file we maintain for running tests against clusters template in the capz repo. Because our convention at present is to only test one API version (currently `v1beta1`) against an "alias" capz version target that is meant to represent the next release version in the queue, we can make the `metadata.yaml` file much simpler and easier to maintain.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
retry

**Review by CecileRobertMichon — COMMENTED** [review]
/retest

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/assign @mboersma

**Review by mboersma — APPROVED** [review]
/approve

**Comment by mboersma** [comment]
@jackfrancis this is ready to merge if you want to give it a release note or `/release-note-none`.

**Pull request merged**
