### PR TITLE
Use hack/tools kubectl in Tiltfile

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Use the hack/tools kubectl binary in the Tiltfile instead of whatever version of kubectl is installed on the dev machine. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

I tried out `make tilt-up` locally and it seems fine.

**Comment by jsturtevant** [comment]
Should we update the tilt modules as well? https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/tilt_modules/cert_manager/Tiltfile

**Comment by CecileRobertMichon** [comment]
> Should we update the tilt modules as well? https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/tilt_modules/cert_manager/Tiltfile

My understanding is that the cert_manager module is copied directly from https://github.com/tilt-dev/tilt-extensions/blob/master/cert_manager/Tiltfile so not sure if we should avoid diverging from it, @mboersma thoughts?

**Comment by mboersma** [comment]
What I've seen is that removing the `tilt_modules/` directory (or a subdirectory) will force `tilt` to fetch these tilt_extensions from the source that @CecileRobertMichon pointed out. 

AFAICT we are up-to-date with the tilt_extensions version anyway, so I don't think there's anything to do here.

**Comment by jsturtevant** [comment]
sounds like it's not necessary.

/lgtm

**Pull request merged**
