### PR TITLE
Install nfs-common package for CI test

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

 

 
**What type of PR is this?**

**What this PR does / why we need it**:
For some conformance tests like: "should access to two volumes with the same volume mode and retain data across pod recreation on the same node", nfs-common is needed otherwise it will fail. The error message is "bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program."
https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-slow-capz/1501812809107771392/build-log.txt

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

related: https://github.com/kubernetes/test-infra/issues/24957

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lzhecheng** [comment]
Without the packages, some conformance tests will fail:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1129/pull-cloud-provider-azure-e2e-capz-1-23/1498545138043981824/build-log.txt

Error message is: `bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.`

**Comment by mboersma** [comment]
@lzhecheng could you please add the word `NONE` to the release note section in this PR description? That should remove the "do-not-merge" label.

**Comment by CecileRobertMichon** [comment]
@lzhecheng please add a PR description to explain why this change is needed.

> Without the packages, some conformance tests will fail:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1129/pull-cloud-provider-azure-e2e-capz-1-23/1498545138043981824/build-log.txt

This specific test seems to have failed with a cluster creation failure, do you have data of a test that failed with the error due to missing nfs-common? In addition, were you able to verify that this change actually fixes the issue by running conformance tests with this change?

The CAPZ conformance tests running with in-tree cloud-provider don't run into this issue (https://testgrid.k8s.io/provider-azure-1.23-signal#capz-conformance) do you know why? Is this issue only impacting out of tree cloud-provider? Shouldn't the conformance suite be the same?

**Comment by lzhecheng** [comment]
@CecileRobertMichon I have updated the PR description.

I am sorry! Somehow I paste the wrong link there... The correct one is: https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-slow-capz/1501812809107771392/build-log.txt

I tested locally. With default configuration, "should access to two volumes with the same volume mode and retain data across pod recreation on the same node" tests on a CAPZ cluster failed and I manually installed the package on nodes then it worked. 

That job you mentioned doesn't include those tests. Such tests are included in "slow" conformance and it seems to be the only place.

**Comment by CecileRobertMichon** [comment]
ok thank you for clarifying! Let's also follow up on https://github.com/kubernetes-sigs/image-builder/pull/823 to see if this can be avoided and we can include it in all images. 

@jackfrancis I will defer to you on merging timing given that this will conflict with #1994

**Comment by jackfrancis** [comment]
@CecileRobertMichon @lzhecheng I would actually prefer to merge that big one first, I'll be happy to help integrate these changes on top of that once it lands

**Comment by CecileRobertMichon** [comment]
@lzhecheng is this test only going to need to run with k8s released versions? Or do you ever need to run it with an unreleased version of k8s (eg. PR tests)?

**Comment by lzhecheng** [comment]
> @lzhecheng is this test only going to need to run with k8s released versions? Or do you ever need to run it with an unreleased version of k8s (eg. PR tests)?

Currently, the test is a daily one on master branch.

**Comment by CecileRobertMichon** [comment]
> Currently, the test is a daily one on master branch.

The kubernetes master branch or the cloud provider master branch? If it's Kubernetes that means the test is likely using a custom k8s build template so this wouldn't be the right template to add it to. If it cloud provider, what k8s version is the test using?

**Comment by lzhecheng** [comment]
> > Currently, the test is a daily one on master branch.
> 
> The kubernetes master branch or the cloud provider master branch? If it's Kubernetes that means the test is likely using a custom k8s build template so this wouldn't be the right template to add it to. If it cloud provider, what k8s version is the test using?

It is a cloud provider job so the cloud provider master branch. It is now using k8s 1.23 and it should use the latest released k8s.

Here is the link to the job:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L674

**Comment by jackfrancis** [comment]
@lzhecheng what's the name of the test? (I think that line reference isn't working anymore)

**Comment by CecileRobertMichon** [comment]
the image builder [PR](https://github.com/kubernetes-sigs/image-builder/pull/823) merged so presumably we don't need this change anymore, at least for new images built from latest image-builder. @mboersma can you please confirm that the new patch version images will include that change?

**Comment by mboersma** [comment]
> can you please confirm that the new patch version images will include that change?

Yes, we will build images from the latest commit on the `main` branch, so that commit will be included.

**Comment by lzhecheng** [comment]
> > can you please confirm that the new patch version images will include that change?
> 
> Yes, we will build images from the latest commit on the `main` branch, so that commit will be included. Also ([kubernetes-sigs/image-builder#832](https://github.com/kubernetes-sigs/image-builder/pull/832).)

Thank you! Sure, I will close this PR. Could you tell me how can I know the image version capz is using? @mboersma

**Comment by mboersma** [comment]
> how can I know the image version capz is using?

The actual pipeline runs in Azure DevOps in a privileged account, in order to publish to the marketplace. So it's not visible, and which version of image-builder was used isn't metadata that we propagate into the image as far as I know.

We have a nightly job that syncs up the image-builder repo, and it ran last night before I started the publishing process this morning. So the new patch images are being built with https://github.com/kubernetes-sigs/image-builder/commit/5c3b3269cf4b8c669d7d85a333e91a382a0da09f.

It may take a few days before the new images are available. The publishing process involves global replication and is time-consuming, and we may have to work with that team to sort out some issues on this run.

**Comment by lzhecheng** [comment]
> > how can I know the image version capz is using?
> 
> The actual pipeline runs in Azure DevOps in a privileged account, in order to publish to the marketplace. So it's not visible, and which version of image-builder was used isn't metadata that we propagate into the image as far as I know.
> 
> We have a nightly job that syncs up the image-builder repo, and it ran last night before I started the publishing process this morning. So the new patch images are being built with [kubernetes-sigs/image-builder@5c3b326](https://github.com/kubernetes-sigs/image-builder/commit/5c3b3269cf4b8c669d7d85a333e91a382a0da09f).
> 
> It may take a few days before the new images are available. The publishing process involves global replication and is time-consuming, and we may have to work with that team to sort out some issues on this run.

Thank you!

**Pull request closed without merging**
