### PR TITLE
Fix simple typo

### PR DESCRIPTION
**Pull request by kaitoii11**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix a simple typo in azure/services/vnetpeerings/vnetpeerings.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

flake

**Comment by CecileRobertMichon** [comment]
another different flake 😢 

/retest

**Comment by nader-ziada** [comment]
unlucky PR :(

/retest

**Pull request merged**
