### PR TITLE
update capi go module to v1.1.4

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

- update capi to v1.1.4
was missing this bump 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update capi to v1.1.4
```

### CODE REVIEW

**Comment by cpanato** [comment]
ahh! forgot the make generate! thanks @jackfrancis

**Comment by cpanato** [comment]
> @cpanato it's not always (usually) required, it depends upon the inherited data types from capi

getting some errors

```
mv release-v3.23.0/manifests/calico-policy-only.yaml templates/addons/calico-ipv6
/Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/kustomize-v4.5.2 build templates/addons/metrics-server > templates/addons/metrics-server/metrics-server.yaml
/Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/kustomize-v4.5.2 build templates/addons/calico > templates/addons/calico.yaml
/Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/kustomize-v4.5.2 build templates/addons/calico-ipv6 > templates/addons/calico-ipv6.yaml
/Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/kustomize-v4.5.2 build templates/addons/calico-dual-stack > templates/addons/calico-dual-stack.yaml
./hack/gen-flavors.sh
Error: accumulating resources: accumulation err='accumulating resources from '../prow-windows/cni-resource-set-windows.yaml': open /Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/templates/test/ci/prow-windows/cni-resource-set-windows.yaml: no such file or directory': evalsymlink failure on '/Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/templates/test/ci/prow-windows/cni-resource-set-windows.yaml' : lstat /Users/cpanato/code/src/sigs.k8s.io/cluster-api-provider-azure/templates/test/ci/prow-windows: no such file or directory
make[1]: *** [generate-flavors] Error 1
make: *** [generate] Error 2
```

**Comment by jackfrancis** [comment]
@cpanato I opened up a PR myself to see if I could fix it and there are indeed a lot of moving pieces here:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2406

Looks like this is going to be more work. What in particular are you trying to accomplish by getting v1.1.4?

**Comment by CecileRobertMichon** [comment]
I missed that https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2353 wasn't actually updating go dependencies... sorry about that should have called it in review

What's causing the issue here? Is it a controller runtime bump or something else? There shouldn't be any breaking changes in between CAPI patch versions

**Comment by cpanato** [comment]
> I missed that #2353 wasn't actually updating go dependencies... sorry about that should have called it in review
> 
> What's causing the issue here? Is it a controller runtime bump or something else? There shouldn't be any breaking changes in between CAPI patch versions

i will try to investigate why this tomorrow, if no one finds till there :)

**Comment by CecileRobertMichon** [comment]
@jackfrancis in your PR some of the dependencies are ahead of what they should be, we should match what CAPI has for controller runtime and k8s clients https://github.com/kubernetes-sigs/cluster-api/blob/v1.1.4/go.mod#L35

**Review by jackfrancis — APPROVED** [review]
/retitle update capi go module to v1.1.4

**Pull request merged**
