### PR TITLE
add nawazkh to reviewers list

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR will add @nawazkh as a CAPZ reviewer.

According to the requirements defined here:

- https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1

- @nawazkh has been a member of the Kubernetes org since 3 November 2022:
  - https://github.com/kubernetes/org/pull/3814
- was the primary reviewer of these recent 4 PRs:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3187
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2909
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2781
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2523
 - has been the key reviewer of the recently reënabled dependabot (18 PRs):
   - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anawazkh+dependabot
- in addition was the author of 20 merged PRs:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+author%3Anawazkh+is%3Aclosed
- has been a contributing reviewer of 39 PRs overall:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anawazkh+

Nawaz has been involved throughout the CAPZ codebase, and notably has driven many CI improvements. Thank you Nawaz!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

I was literally just about to ask in Slack when @nawazkh was going to join the reviewers, then I got notified of this PR. Well deserved. Thanks for everything that you do @nawazkh!

**Comment by sonasingh46** [comment]
+1  Fantastic work @nawazkh. Thank you

**Review by sonasingh46 — APPROVED** [review]

**Comment by jsturtevant** [comment]
+1 great to see the focus on automating and improving the quality of CI

**Comment by nojnhuh** [comment]
+1, @nawazkh has been awesome at jumping in to pick up issues and review PRs. Looking forward to more!

**Comment by devigned** [comment]
+1 well earned!

**Comment by CecileRobertMichon** [comment]
Should start a lazy consensus on this?

**Comment by jackfrancis** [comment]
Propose lazy consensus expiration after CAPZ office hours tomorrow (roughly 10 a.m. PST)

**Pull request merged**
