### PR TITLE
add nawazkh to maintainers

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Nawaz has consistently demonstrated value across a broad range of the CAPZ project.

Features:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5209
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4551
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4572
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4606
CI and testing:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4939
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4859
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5064
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5109
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5166

Altogether Nawaz has landed 78 PRs throughout his time working on CAPZ:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+author%3Anawazkh+is%3Amerged+

Thank you Nawaz!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/lgtm

Yes please! @nawazkh has been a strong and consistent pillar of CAPZ and I'm excited to have him join the maintainers. 👍🏻

**Comment by nojnhuh** [comment]
+1, LGTM

**Comment by willie-yao** [comment]
Huge +1 from me! Nawaz has made so many impactful contributions to the project especially with his recent work on the ilb stuff! 🚀 

/lgtm

**Review by marosset — APPROVED** [review]
/lgtm
🚀

**Comment by jsturtevant** [comment]
/lgtm  
you've had broad contributions and always willing to dive into the chop wood, carry water tasks

**Comment by Jont828** [comment]
/lgtm

Congrats! 🚀🚀🚀

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
