### PR TITLE
[DO_NOT_MERGE] [WIP] Revert updates to ginkgo and gomega

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This is to test issues with testgrid reporting success on some jobs when some tests failed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
It doesn't seem that this is the culprit, the e2e test job is green but some tests still failed https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3638/pull-cluster-api-provider-azure-e2e/1669856024170860544

**Comment by mboersma** [comment]
See also #3640 (Update Ginkgo to v2.11.0).

**Comment by willie-yao** [comment]
> It doesn't seem that this is the culprit, the e2e test job is green but some tests still failed https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3638/pull-cluster-api-provider-azure-e2e/1669856024170860544

Yup doesn't look like it. I also observed this issue as far back as the 6/02 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e/1664731021301518336

**Comment by willie-yao** [comment]
> See also #3640 (Update Ginkgo to v2.11.0).

Looks like the test is still being marked as passed even though it failed. I'm guessing it's most likely not a Ginkgo problem https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3640/pull-cluster-api-provider-azure-e2e/1670813186707689472

**Comment by willie-yao** [comment]
Closing in favor of #3647 which has the correct fix

**Comment by willie-yao** [comment]
Closing in favor of #3647 which has the correct fix

**Pull request closed without merging**
