### PR TITLE
Add Name and owner tags to NSGs

### LINKED ISSUE #2367: Tag managed NSGs as owned
/kind feature

**Describe the solution you'd like**
Tag managed NSGs as owned i.e. sigs.k8s.io_cluster-api-provider-azure_cluster__clustername_ "owned"

**Anything else you would like to add:**
Child of #2354

### PR DESCRIPTION
**Pull request by josh-ferrell**
**What type of PR is this?**
Add Name and owner tags to NSGs created by CAPZ

/kind feature

**What this PR does / why we need it**:
Adds Name tag and sigs.k8s.io_cluster-api-provider-azure_cluster__clustername_ tag
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2367 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Add Name and owner tags to NSGs
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @Jont828

**Review by Jont828 — COMMENTED** [review]
These changes look pretty solid to me. Thanks for your contribution!

**Pull request merged**
