### PR TITLE
test: remotely retrieve VHD images once

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR ensures that we remotely pull for a list of regionally available images only once during an E2E test run. At present we pull both Linux and Windows images *four times* per run, once in the main `SynchronizedBeforeSuite` flow, and in addition once per node (ginkgo thread). In addition to causing unnecessary calls to the Azure APIs, we are slowing down our test runs by a long time (these pulls and data parsing take ~minutes!).

The E2E tests are currently implemented to build all clusters in a common region, so there is no reason to do "per-test-job image pulling".

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
This is interesting, clearly the changeset is responsible for these test failures, but I can't reproduce them locally.

Does anything look suspicious to you here, @mboersma?

**Comment by mboersma** [comment]
I'm not seeing the change in this PR that could cause those "invalid KubernetesVersion" errors, but obviously it broke something. I'll try locally.

**Comment by jackfrancis** [comment]
@mboersma this must be what's going on... something about the fact that we're only pulling the versions once (instead of four) correlates a little too closely with the fact that we're only getting one successful cluster test (instead of four)

**Pull request closed without merging**
