### PR TITLE
Enable node drain timeout CAPI test

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Follow up on #1423 now that https://github.com/kubernetes-sigs/cluster-api/pull/4830 has merged.

/hold for #1464 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold cancel

this is good to go

/assign @mboersma @nader-ziada

**Review by mboersma — APPROVED** [review]
lgtm

**Comment by CecileRobertMichon** [comment]
@nader-ziada PTAL when you can

**Pull request merged**
