### PR TITLE
Fix error handling when vm is deleted

### LINKED ISSUE #1042: Incorrect error handling in azuremachine controller
/kind bug

**What steps did you take and what happened:**
Recently in #1039 , there was a [check](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/b77c94a09e03bb3b54b5f016be7eb4b3ff16daec/controllers/azuremachine_controller.go#L273) added to see if it is a `VMDeletedError`, and set failure status if it is true. But, this wont work because `VMDeletedError` is an interface, and so all errors will return true.

**What did you expect to happen:**
1. `VMDeletedError` should be a struct for doing a type check.
2. Use `errors.Is(err, target error)` or `errors.As(err error, target interface{}` to handle wrapped errors

**Anything else you would like to add:**
This was discovered [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1032#discussion_r525215168). Thanks to @devigned 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/cc @CecileRobertMichon @nader-ziada

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes error handling when vm is deleted
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1042 

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix error handling when vm is deleted
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Comment by shysank** [comment]
apidiff:

```
sigs.k8s.io/cluster-api-provider-azure/cloud
  Incompatible changes:
  - VMDeletedError: changed from interface{Error() string} to struct{ProviderID string}
```

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm

@shysank were you able to verify this works as expected when a VM is deleted from Azure?

**Comment by shysank** [comment]
> @shysank were you able to verify this works as expected when a VM is deleted from Azure?
Yeah, sorry forgot to attach logs.

case1: When not able to connect to azure sdk ( just turned my wifi off), it should not skip reconciliation which it was doing earlier after the change
```
I1117 22:02:46.906897       1 azurejson_machinetemplate_controller.go:93] controllers/AzureJSONTemplate "msg"="Cluster Controller has not yet set OwnerRef" "azureMachineTemplate"="apple-control-plane" "namespace"="default"
E1117 22:09:43.757070       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to get availability zones: failed to get zones for location centralus: failed to refresh resource sku cache: could not list resource skus: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/providers/Microsoft.Compute/skus?%24filter=location+eq+%27centralus%27\u0026api-version=2019-04-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azurecluster" "name"="explorer" "namespace"="default"
I1117 22:09:43.762706       1 azurecluster_controller.go:168] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="explorer" "cluster"="explorer" "namespace"="default"
E1117 22:09:43.793449       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create inbound NAT rule: failed to get Load Balancer explorer-public-lb: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/resourceGroups/explorer/providers/Microsoft.Network/loadBalancers/explorer-public-lb?api-version=2019-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azuremachine" "name"="explorer-control-plane-zxhlr" "namespace"="default"
E1117 22:09:43.794003       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create network interface: failed to fetch network interface explorer-md-0-wwvc4-nic: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/resourceGroups/explorer/providers/Microsoft.Network/networkInterfaces/explorer-md-0-wwvc4-nic?api-version=2019-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azuremachine" "name"="explorer-md-0-wwvc4" "namespace"="default"
I1117 22:09:43.795103       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:09:43.799258       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
I1117 22:12:05.037715       1 azurejson_machinetemplate_controller.go:93] controllers/AzureJSONTemplate "msg"="Cluster Controller has not yet set OwnerRef" "azureMachineTemplate"="apple-control-plane" "namespace"="default"
I1117 22:12:05.038830       1 helpers.go:319] controllers/AzureJSONTemplate "msg"="returning early from json reconcile, no update needed" "azureMachineTemplate"="explorer-control-plane" "cluster"="explorer" "namespace"="default"
I1117 22:12:05.039547       1 helpers.go:319] controllers/AzureJSONTemplate "msg"="returning early from json reconcile, no update needed" "azureMachineTemplate"="explorer-md-0" "cluster"="explorer" "namespace"="default"
E1117 22:17:13.297659       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to get availability zones: failed to get zones for location centralus: failed to refresh resource sku cache: could not list resource skus: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/providers/Microsoft.Compute/skus?%24filter=location+eq+%27centralus%27\u0026api-version=2019-04-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azurecluster" "name"="explorer" "namespace"="default"
I1117 22:17:13.302222       1 azurecluster_controller.go:168] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="explorer" "cluster"="explorer" "namespace"="default"
E1117 22:17:13.332995       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create inbound NAT rule: failed to get Load Balancer explorer-public-lb: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/resourceGroups/explorer/providers/Microsoft.Network/loadBalancers/explorer-public-lb?api-version=2019-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azuremachine" "name"="explorer-control-plane-zxhlr" "namespace"="default"
I1117 22:17:13.333816       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
E1117 22:17:13.333223       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create network interface: failed to fetch network interface explorer-md-0-wwvc4-nic: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/eba22861-4990-4213-ab8e-776393e3696b/resourceGroups/explorer/providers/Microsoft.Network/networkInterfaces/explorer-md-0-wwvc4-nic?api-version=2019-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: no such host'" "controller"="azuremachine" "name"="explorer-md-0-wwvc4" "namespace"="default"
I1117 22:17:13.337776       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:17:14.752093       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:17:15.135033       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
I1117 22:17:15.882424       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:17:16.730904       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
I1117 22:17:19.009597       1 azurecluster_controller.go:168] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="explorer" "cluster"="explorer" "namespace"="default"

```

case2 : skip reconciliation if vm is deleted
```
I1117 22:23:00.090148       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:23:00.090226       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
I1117 22:23:01.079327       1 azuremachine_controller.go:301] controllers/AzureMachine "msg"="Unexpected VM deletion" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default" "id"=""
I1117 22:23:01.100640       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:23:01.907131       1 azuremachine_controller.go:301] controllers/AzureMachine "msg"="Unexpected VM deletion" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default" "id"=""
I1117 22:23:01.918772       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:23:02.680905       1 azuremachine_controller.go:301] controllers/AzureMachine "msg"="Unexpected VM deletion" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default" "id"=""
I1117 22:29:35.981040       1 azurecluster_controller.go:168] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="explorer" "cluster"="explorer" "namespace"="default"
I1117 22:29:35.982671       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:29:35.983820       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
E1117 22:29:37.111190       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create virtual machine: VM with provider id \"explorer-md-0-wwvc4\" has been deleted" "controller"="azuremachine" "name"="explorer-md-0-wwvc4" "namespace"="default"
I1117 22:29:37.113861       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:29:37.754588       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-zxhlr" "cluster"="explorer" "machine"="explorer-control-plane-dlrt4" "namespace"="default"
E1117 22:29:37.871606       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create virtual machine: VM with provider id \"explorer-md-0-wwvc4\" has been deleted" "controller"="azuremachine" "name"="explorer-md-0-wwvc4" "namespace"="default"
I1117 22:29:37.873132       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
I1117 22:29:37.874036       1 azuremachine_controller.go:230] controllers/AzureMachine "msg"="Error state detected, skipping reconciliation" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-wwvc4" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-pn6kr" "namespace"="default"
```

Let me know if you think there is any other scenario that I need to verify.

**Comment by CecileRobertMichon** [comment]
> Also, I think we should enhance azuremachinecontroller_test to test reconcile error cases. wdyt?

+1, it'd be great to have a test case that fails before this fix and succeeds after

**Comment by shysank** [comment]
> +1, it'd be great to have a test case that fails before this fix and succeeds after

So, I looked at the code, and I think it's going to be harder than I thought because of [tight coupling](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/5ce2cc61a6862852cd7ed7229757422c6f6b7dfb/controllers/azuremachine_controller.go#L266) with `azureMachineService`. Ideally, we'll have to inject this dependency into the reconciler so that we can create mocks for testing. Probably something like 
```
type AzureMachineReconciler struct {
	client.Client
	Log              logr.Logger
	Recorder         record.EventRecorder
	ReconcileTimeout time.Duration
	azureMachineServiceFactory func(*scope.MachineScope, *scope.ClusterScope) azureMachineService
}

// inject it using the factory 
func (r *AzureMachineReconciler) ctx context.Context, machineScope *scope.MachineScope, clusterScope *scope.ClusterScope) (reconcile.Result, error) {
 
ams := r.azureMachineServiceFactory(machineScope, clusterScope)

}
```

And I think we should do it for other controllers as well. Thoughts?

**Comment by devigned** [comment]
Probably want to extract an interface from azureMachineService too.

**Comment by shysank** [comment]
Filed #1047 #1048 to address the above issues.

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
