### PR TITLE
update cluster api version to v0.3.7-rc.0

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- update cluster api dependency

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update cluster-api dependency t0 v0.3.7-rc.0
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
> /test pull-cluster-api-provider-azure-capi-e2e

is that how you trigger the capi tests?

**Comment by CecileRobertMichon** [comment]
> is that how you trigger the capi tests?

yep, they are set up as optional/not run by default in test-infra

**Comment by CecileRobertMichon** [comment]
@vincepri FYI, tests are looking good

**Comment by vincepri** [comment]
LGTM!!

**Comment by vincepri** [comment]
Is this using CRS yet?

**Comment by CecileRobertMichon** [comment]
> Is this using CRS yet?

No, not yet. Will do that separately.

**Pull request merged**
