### PR TITLE
Fix secret list RBAC for deletions

### PR DESCRIPTION
**Pull request by johnharris85**
Signed-off-by: John Harris <joharris@vmware.com>

**What this PR does / why we need it**:
This PR resolves an issue where clusters would not delete due to a
missing `list secrets` RBAC permissions in the provider clusterrole.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Fixed issue with RBAC for listing secrets that would prevent `clusterctl delete` from succeeding.
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@johnharris85 -- can you run a `make test` and push any changes that result from that?

**Comment by johnharris85** [comment]
@justaugustus done

**Pull request merged**
