### PR TITLE
removed SetBootstrapCondition

### LINKED ISSUE #3114: SetBootstrapConditions func is unused and should be removed
The `SetBootstrapConditions` function is no longer used since #2177, it should be deleted.

This issue is to remove the following functions:

- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L569
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepool.go#L462
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepool_test.go#L184

### PR DESCRIPTION
**Pull request by swastik959**
**Kind cleanup**

**removed SetBootstrapCondition**:

**Fixes #3114 **

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
There's a typo in the commit message and PR title: "SetBootstrapCo**n**dition" (missing an "n").

~~Could you explain why this change is needed?~~ Never mind, I guess #3114 explains it all. Thanks again!

**Review by nojnhuh — APPROVED** [review]
Completely red diffs are my favorite! Thanks @swastik959!
/ok-to-test
/lgtm

**Comment by swastik959** [comment]
> @swastik959 The CI failures that are being surfaced are:
> ```
> azure/scope/machine.go:24:2: imported and not used: "time"
> azure/scope/machinepool.go:24:2: imported and not used: "time"
> ```
> 
> I wouldn't expect re-testing to fix those, so you'll need to make those couple of small changes. A tool like `goimports` can do that for you automatically.

@nojnhuh thanks will try to fix those

**Comment by swastik959** [comment]
@nojnhuh please review it now

**Comment by nojnhuh** [comment]
@swastik959 It looks like the pull-cluster-api-provider-azure-test job found some new linter errors if you wouldn't mind addressing those. Sometimes those can be fixed automatically by running `make lint-fix`.

**Comment by swastik959** [comment]
@nojnhuh 
@mboersma 
please review it now

**Comment by nojnhuh** [comment]
/retest
The ci-entrypoint job is known to be flaky lately and I don't see any reason these changes should make that test fail any more frequently.

**Review by mboersma — APPROVED** [review]
/label tide/merge-method-squash
/lgtm
/approve

**Pull request merged**
