### PR TITLE
chore(golangci-lint): add gocritic linter

### LINKED ISSUE #2029: Add gocritic linter
/kind bug

Add `gocritic` linter in the CAPZ repo. 

Some similar PR references for adding linters are below: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1986
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1985

**What did you expect to happen:**
Refer to the umbrella [issue](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1982) 

Ref link for linters: 
https://golangci-lint.run/usage/linters/

/good-first-issue

### PR DESCRIPTION
**Pull request by viniciussaturnino**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2029

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by sonasingh46** [comment]
You will need to run `make generate` locally and check in the files that get changed after that. And to verify that everything is fine, run `make verify` on your local setup. 
That should fix your ci failures.

**Comment by sonasingh46** [comment]
Thanks for the PR.

**Review by mboersma — APPROVED** [review]
/lgtm

I like all the `gocritic` changes here. 👍🏻

**Review by CecileRobertMichon — APPROVED** [review]
/approve

**Pull request merged**
