### PR TITLE
Move alexeldeib to emeritus status

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Moves @alexeldeib to emeritus status. We spoke before I opened this PR.

Thank you 💯 @alexeldeib for all your contributions to CAPZ, for making AKS in CAPZ happen, and for the huge part you have played in getting this Cluster API provider to where it is today! 👏 🙏

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by jackfrancis** [comment]
Thanks @alexeldeib!

❤️ 🦄 ✨

**Pull request merged**
