### PR TITLE
Cherry pick of #1830: chore: add mixed protocol feature gates

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Cherry pick of #1830: chore: add mixed protocol feature gates

We need mixed protocol feature gate to test mixed protocol lb typed service in cloud provider azure e2e test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
chore: add mixed protocol feature gates
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@nilo19 what do you think about cherry picking this to the release-1.0 branch instead and moving the cloud provider tests to use release-1.0? We were going to do have to do that soon anyway.

**Comment by feiskyer** [comment]
could we merge this to unblock the current e2e tests?

**Comment by feiskyer** [comment]
we are not sure whether moving to capz 1.0 would have other issues or not, so it's better to track capz 1.0 as a separate work?

**Comment by CecileRobertMichon** [comment]
Makes sense, thanks for the additional context

Please also cherry-pick this to release-1.0 as the main branch is targeting v1.1.

/lgtm 
/approve

**Pull request merged**
