### PR TITLE
[release-1.9] Update CAPI to v1.4.3

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Manual cherry-pick of #3612.

Updates CAPI references to use the [v1.4.3 release](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.3). Also bumps cert-manager to v1.12.1 to [match CAPI](https://github.com/kubernetes-sigs/cluster-api/pull/8748). Reimplements some trivial string processing methods that were deprecated in CAPI.

**Which issue(s) this PR fixes**:

Closes #3613 

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v1.4.3
```

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

I think #3632 needs to merge first, so this can pass the Codespell linter.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
@mboersma the periodic job seems broken https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-aks-v1beta1-release-1-9

**Comment by mboersma** [comment]
/retest

Hmm. The periodic job passed last night. 🤞🏻

**Pull request merged**
