### PR TITLE
add toleration for control plane taints

### LINKED ISSUE #2640: Add `node-role.kubernetes.io/control-plane` toleration to CAPZ manager deployment
/kind bug

In the Sept 1., 2002 CAPZ Office Hours meeting we agreed on the need to catch up with kubeadm changes for k8s v1.24.0, specifically that the control plane node taint has changed to `node-role.kubernetes.io/control-plane:NoSchedule`.

cc: @sonasingh46

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

/kind feature

**What this PR does / why we need it**:

Adds control plane toleration for manager deployment. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2640 

```release-note
Add tolerations for control plane taints in manager deployment config
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by jackfrancis** [comment]
I thought there was a reason for these tolerations not being present. Maybe @CecileRobertMichon can comment when she returns.

Sorry @sonasingh46 if this is a pressing concern.

**Comment by mboersma** [comment]
I don't think there's urgency to merging this. But the notes from our Sept. 1 meeting claim:

> [Cecile] +1 on adding this toleration to capz components

Having said that, it's safer to take it slow, and I agree it's a bit odd we never added the previous toleration. So let's see if @CecileRobertMichon remembers anything else about this when she's back.

**Comment by jackfrancis** [comment]
thanks @mboersma!

/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
No objections from me, thanks for getting this done!

**Pull request merged**
