### PR TITLE
Add unit tests for AzureManagedMachinePool controller

### LINKED ISSUE #2078: Add unit tests for AzureManagedMachinePool controller
/kind feature

**Describe the solution you'd like**

The file `exp/controllers/azuremanagedmachinepool_controller.go` does not have corresponding unit tests, but should. 

PR #2074 shows AMMPs are in use, and ideally that change would be covered by testing. I think it's too much to ask for that one-line change to implement an entire test module, so I opened this issue.

**Anything else you would like to add:**

Its neighbor `exp/controllers/azuremachinepool_controller.go` has some unit tests in a couple different files. Those could perhaps be used as a model or starting point.

### PR DESCRIPTION
**Pull request by KushalBeniwal**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

The file `exp/controllers/azuremanagedmachinepool_controller.go` does not have corresponding unit tests, but should because AMMPs are in use.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2078

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] add tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Hi @KushalBeniwal, what the status of this PR?

**Comment by KushalBeniwal** [comment]
Hi @CecileRobertMichon, apologies but I won't be able to continue with this PR. Please feel free to open the issue for anyone new to take.

**Pull request closed without merging**
