### PR TITLE
📖   Add missing step in AAD doc

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**: Follow up from #1158 after getting an answer on https://github.com/Azure/azure-cli/issues/16862. I had removed the SP step because I thought it wasn't necessary but it actually is so re-adding.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
