### PR TITLE
fix codespell highlighted error

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- fixes codespell highlighted error

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Codespell has been complaining about the word `identities` on my PRs https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3508.

**Comment by nawazkh** [comment]
What do you think if we add `check_codespell` target in the Makefile where every developer is expected to run `make verify` before raising a PR for final approval? 
The target could look like below.
```shell
CODESPELL_DIR := hack/tools/bin
CODESPELL_BINARY := $(CODESPELL_DIR)/codespell
.
.
.PHONY: check_codespell
check_codespell:
    @which $(CODESPELL_BINARY) >/dev/null || ( \
        echo "codespell not found. Installing..."; \
        mkdir -p $(CODESPELL_DIR); \
        pip install --target=$(CODESPELL_DIR) codespell; \
    )
    $(CODESPELL_BINARY) -r .
```

Catch: this target expects `pip` (and `python`) preinstalled in the system.

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
> What do you think if we add check_codespell target

I think that makes sense. Right now, developers can't actually run this test locally, so you're flying blind to some extent.

I don't think requiring python and pip is much to ask, it's installed by default on all modern operating systems.

**Comment by mboersma** [comment]
/cherry-pick release-1.9

🤦🏻

**Comment by nawazkh** [comment]
> /cherry-pick release-1.9
> 
> 🤦🏻

Oh yes, thank you for creating this.

**Pull request merged**
