### PR TITLE
Fix parsing error for CCM tag

### PR DESCRIPTION
**Pull request by lzhecheng**
If CCM tag is numerical, helm will parse it incorrectly.
https://github.com/helm/helm/issues/1707#issuecomment-810371666

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

 

 
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix parsing error for CCM tag. If CCM tag is numerical, helm will parse it incorrectly.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix parsing error for CCM tag. If CCM tag is numerical, helm will parse it incorrectly.
```

### CODE REVIEW

**Comment by lzhecheng** [comment]
Example:
https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-conformance-vmss-capz/1537344382720544768/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-conformance-vmss-capz/1537344382720544768/artifacts/clusters/capz-5fb7h6/kube-system/cloud-node-manager-dsz25/pod-events.txt

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/cherry-pick release-1.3

**Pull request merged**
