### PR TITLE
Update Kubernetes version support policy

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: 
- Remove 1.15 and add 1.18. 
1.15 is actually not supported with v1alpha3 because CRD v1 requires 1.16+.
- change default env vars from 1.17.3 to 1.17.4 in scripts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

waiting for 1.18 image to be public

**Comment by CecileRobertMichon** [comment]
@justaugustus done, PTAL

**Comment by justaugustus** [comment]
Thanks @CecileRobertMichon!
/lgtm
/approve
/hold cancel

**Comment by CecileRobertMichon** [comment]
1.18 verified:

```
kubectl --kubeconfig=./my-capz-cluster.kubeconfig get nodes -o wide                                                                                                      
NAME                              STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
capz-1dot18-control-plane-blp7c   Ready    master   6m24s   v1.18.0   10.0.0.5      <none>        Ubuntu 18.04.4 LTS   5.0.0-1035-azure   containerd://1.3.3
capz-1dot18-control-plane-dtfk9   Ready    master   7m54s   v1.18.0   10.0.0.4      <none>        Ubuntu 18.04.4 LTS   5.0.0-1035-azure   containerd://1.3.3
capz-1dot18-control-plane-nnf8q   Ready    master   4m11s   v1.18.0   10.0.0.6      <none>        Ubuntu 18.04.4 LTS   5.0.0-1035-azure   containerd://1.3.3
capz-1dot18-md-0-cb4fm            Ready    <none>   5m3s    v1.18.0   10.1.0.4      <none>        Ubuntu 18.04.4 LTS   5.0.0-1035-azure   containerd://1.3.3
```

/hold cancel

**Pull request merged**
