### PR TITLE
Update CAPI to v1.5.2

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI references to use the new [v1.5.2 release](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.2).

Also updates cert-manager to v1.13.0 to keep that in sync with CAPI.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v1.5.2
```

### CODE REVIEW

**Comment by Jont828** [comment]
LGTM pending test failure

**Comment by Jont828** [comment]
It seems like you're having a regex failure:

```
Expected
        <*errors.errorString | 0xc00577fa50>: 
        failed to match regexp "GET /echo\\?msg=prestop" in output "I0[926](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4041/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1706793339065470976#1:build-log.txt%3A926) 22:49:04.855003   15684 log.go:194] Started HTTP server on port 8080\nI0926 22:49:05.028477   15684 log.go:194] Started UDP server on port  8081\n"
        {
            s: "failed to match regexp \"GET /echo\\\\?msg=prestop\" in output \"I0926 22:49:04.855003   15684 log.go:194] Started HTTP server on port 8080\\nI0926 22:49:05.028477   15684 log.go:194] Started UDP server on port  8081\\n\"",
        }
    to be nil
```

**Comment by mboersma** [comment]
/retest

This time, 0 out of 2 machines in the deployment were ready. :shrug:

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Pull request merged**
