### PR TITLE
Update Calico to v3.20.0

### LINKED ISSUE #1584: Calico v3.20 nodes don't become ready
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:** Tried to update Calico to v3.20.0 in #1583, cluster provisioning failed because nodes didn't become ready. Not sure if there is something wrong with Calico v3.20 + vxlan, or if a configuration changed in the manifest which caused it to fail.

To repro, build a cluster and apply https://docs.projectcalico.org/v3.20/manifests/calico-vxlan.yaml 

We should investigate what the error is and open an issue on the Calico repo if there is a regression in 3.20.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- update the version of calico used to v3.20.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1584 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Updated Calico to v3.20.0
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
The `Creating an AKS cluster` test failing here is also failing in the `main` branch https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full/1425796093219704832

**Comment by CecileRobertMichon** [comment]
This is the same flake seen in #1388 

I know @alexeldeib mentioned there were still some flakes he was looking into, this might be one of them.

Regardless, AKS doesn't use the CAPZ Calico spec so this is safe to merge.

/approve

**Pull request merged**
