### PR TITLE
test: surround CAAPH values strings in quotes

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

This PR ensures that HelmChartProxy values strings are strings where there could be some ambiguity.

Addresses https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/175

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lzhecheng** [comment]
/lgtm
Could approvers help review this one? Cloudprovider tests met the issue again.

**Comment by jackfrancis** [comment]
@nawazkh @Jont828 I changed this one up a bit and it looks like it's passing. I think this may solve @lzhecheng's issues w/ short git shas sometimes getting interpreted as number types (when the SHA doesn't include an alpha character in it).

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Comment by jackfrancis** [comment]
👋 it's me from the future, apparently.

**Pull request merged**
