### PR TITLE
Bump helm to v3.14.4

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Bumps helm to the latest version.

**Special notes for your reviewer**:

- [x] cherry-pick candidate, for bugfixing reasons 

**Release note**:

```release-note
Bump helm to v3.14.4
```

### CODE REVIEW

**Comment by damdo** [comment]
@mboersma it is referenced here
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/43283e9f4dce650c67a5a6f59f0adb67c7f18fce/scripts/ci-entrypoint.sh#L36
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/43283e9f4dce650c67a5a6f59f0adb67c7f18fce/test/e2e/helm.go#L40

So I think it is used in the E2Es.

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
