### PR TITLE
Replaced `go get` with `go install` to install binaries

### LINKED ISSUE #2004: Use go install instead of go get to install binaries
https://go.dev/doc/go-get-install-deprecation

Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.

In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. 

we should stop using go get to install hack/tools and instead rely on go install here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/go_install.sh#L54

/good-first-issue

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The PR replaces `go get` with `go install` to install binaries.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2004 

**Release note**:
```
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
It looks like there is a known issue with kustomize that prevents us from using go install with it: https://github.com/kubernetes-sigs/kustomize/issues/3618

we can either wait until it's fixed to merge this, or change the kustomize install to keep using go get for now.

/hold

**Comment by sonasingh46** [comment]
@CecileRobertMichon -- I was thinking we can probably use `go install` to install binary and for `kustomize` we can still use  `go get`.

**Comment by sonasingh46** [comment]
We can use hard coded `go get` here for kustomize 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L255

**Comment by sonasingh46** [comment]
>we can either wait until it's fixed to merge this, or change the kustomize install to keep using go get for now.
I think you suggested the same.

**Comment by CecileRobertMichon** [comment]
#2088 should unblock this

**Comment by jayesh-srivastava** [comment]
@CecileRobertMichon I guess I can't remove the hold. Now that #2091 is merged, I think this should work now.

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

Thanks @jayesh-srivastava!

**Pull request merged**
