### PR TITLE
[release-1.8] update golang to v1.20

### PR DESCRIPTION
**Pull request by jackfrancis**
This is a manual cherry-pick of #3478

/assign CecileRobertMichon

```release-note
use golang v1.20 to build and test CAPZ
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
Have all test-infra jobs (in k/k, provider-azure, SIG Windows, CAPZ, etc) that build CAPZ from source using release-1.8 been updated to use the latest kubekins image with go 1.20?

**Comment by jackfrancis** [comment]
@CecileRobertMichon kubekins audit below:

- CAPZ test jobs are using v1.27 (which is go1.20): https://github.com/kubernetes/test-infra/pull/29355
- k/k presubmit cloud-provider-azure jobs are using v1.27
- cloud-provider-azure jobs are using the master kubekins build (which is go1.20)
  - except the following jobs:
    - `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-25` is using `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-1.25`
    - `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-26` is using `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-1.26`
    - `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-27` is using `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-1.27`
- CSI jobs are using v1.27
- sig-windows tests against master are using the master kubekins build
- sig-windows jobs against k/k release branches are using the same-versioned kubekins image as the release branch

So, according to this we aren't going to be able to use CAPZ @ go1.20 for jobs that use kubekins < v1.27:

- https://github.com/kubernetes/test-infra/blob/master/images/kubekins-e2e/variants.yaml#L40-L57

Do we want to consider pointing older release branch jobs that use kubekins < 1.27 to CAPZ @ release-1.7? The only other near-term way to unblock cloud-provider-azure would be to point its jobs to CAPZ @ main, which I don't think we want to do.

PS @feiskyer @lzhecheng  do we want to update the `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-25`, `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-26`, and `pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-27` jobs so that they use the master kubekins images like their peer jobs? Was that just an oversight?

**Comment by lzhecheng** [comment]
@jackfrancis Yes, I think we can use master kubekins image.

**Comment by mboersma** [comment]
/lgtm cancel

@jackfrancis should we close this PR?

See also kubernetes/test-infra#29431

**Pull request closed without merging**
