### PR TITLE
add apidiff and verify tilt make target

### PR DESCRIPTION
**Pull request by sonasingh46**
/kind cleanup

**What this PR does / why we need it**:
This PR adds the following make targets: 
1. `make apidiff` : This target in turn calls the existing `go-apidiff`
2. `make verify-tiltfile`: This verifies the tiltfile format.
3. `make format-tiltfile`: This formats the tiltfile. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Reference issue #2026 

**Special notes for your reviewer**:
Open for suggestions if the `make apidiff` --> `make go-apidiff` makes sense. I feel it should help in the contributor experience. 

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
```release-note
None
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

I tried out these targets locally. I thought it odd that `verify-tiltfile` isn't a sub-target of `make verify`, but I see that's how CAPI has it as well, so :shrug:.

**Comment by CecileRobertMichon** [comment]
>  I thought it odd that verify-tiltfile isn't a sub-target of make verify

+1 to adding it to make verify, if it's not run by make verify it won't run in CI which means we won't actually use it to gate PRs

**Comment by sonasingh46** [comment]
+1 To add it to make verify. It was a miss from me. Also, capi does have the `verify-tiltfile` as a sub target of `make verify` -- just via little substitutions.

**Comment by sonasingh46** [comment]
@CecileRobertMichon @mboersma -- Added it to `make verify` target.

**Comment by jackfrancis** [comment]
@CecileRobertMichon should we update test-infra so that the `pull-cluster-api-provider-azure-apidiff` invokes `make apidiff` instead of calling the shell script explicitly? Ref:

- https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-main.yaml#L422

(Ditto the three release presubmit specs that we currently maintain.)

**Comment by CecileRobertMichon** [comment]
> should we update test-infra so that the pull-cluster-api-provider-azure-apidiff invokes make apidiff instead of calling the shell script explicitly?

Hmm good point. @sonasingh46 @sbueringer looks like CAPI also calls a shell script despite having a make target https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L35, thoughts?

**Comment by sonasingh46** [comment]
@CecileRobertMichon @jackfrancis -- AFAIK, there is little difference in the `make <targets>` vs the `shell scripts`. There are some custom things that may need to be done. In this case, the script runs the `apidiff` on pull based sha. 
Ref: https://github.com/kubernetes-sigs/cluster-api/blob/main/scripts/ci-apidiff.sh#L28
This sha is exposed as an env var by the prow job.

**Comment by sbueringer** [comment]
As Ashutosh said, there's a difference between the makefile target and the shell script.

The Makefile target is comparing the current state against origin/main, the shell script against `PULL_BASE_SHA`

Maybe we could improve this a bit and make the API_DIFF_BASE_SHA configurable in the makefile target (with a default of `shell git rev-parse origin/main`) and then call the makefile target from the shell script (with PULL_BASE_SHA)?

Related observation. In core CAPI afaik all Jobs are calling `scripts/ci-<>.sh` shell scripts and those are then running the makefile targets, in some cases they are also doing some additional stuff before. (although ideally they don't)
My impression is that this is done to decouple the Job configs from the Makefile targets.

**Pull request merged**
