### PR TITLE
add control plane tolerations to aad pod identity

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

 

 
**What type of PR is this?**

**What this PR does / why we need it**:

Adds control plane tolerations to aad pod identity. The capz manager pod has already this tolerations. The toleration is needed on aad pod identity as well otherwise for situations when capz pod gets scheduled on control plane node, the authentication to azure cloud will fails as the capz-nmi(aad pod identity) pod is not present on the control plane node due to taint policy. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Add tolerations to aad pod identity
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
Seems like the right change. 

Is it reasonable to test this somehow in e2e?

**Comment by sonasingh46** [comment]
@mboersma 

> Is it reasonable to test this somehow in e2e?

I don't think there is any specific way to test other than writing a test that checks if the capz-nmi pods are running on all the nodes including the control plane nodes.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Pull request merged**
