### PR TITLE
Update kpromo to v3.3.0-beta.3

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: kubernetes-sigs/promo-tools#465 (comment) this version fixes how the command is printed in the PR created in k8s.io.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

quota issues

**Review by mboersma — APPROVED** [review]
/lgtm

I don't have context on the changes between -beta.2 and -beta.3, but this PR looks sane. :-)

**Pull request merged**
