### PR TITLE
update the nmi image version to the latest release

### PR DESCRIPTION
**Pull request by devigned**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

This PR updates the nmi image to the latest released version as there have been some meaningful updates recently.

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update aad-pod-identity nmi to v1.8.5
```

### CODE REVIEW

**Comment by mboersma** [comment]
> msg: "failed to download file \"v1.5.3\" from \"cert-manager.yaml\" release",

I haven't seen that failure for the `pull-cluster-api-provider-azure-e2e-windows-dockershim` job before. Doesn't appear related to your change.

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

One question: how do we expect customers running it already in their management cluster to update the image? Is that out of scope for CAPZ?

**Comment by devigned** [comment]
> One question: how do we expect customers running it already in their management cluster to update the image? Is that out of scope for CAPZ?

Great question. The change itself is relatively simple. Is this something that would be handled with https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20201020-capi-provider-operator.md?

**Pull request merged**
