### PR TITLE
ci-build-auzre-ccm build windows host-process-container based images

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
uses new make targets introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6318 for a cloud-node-manager windows image that can be used on all Windows Server versions

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by marosset** [comment]
I'll undraft this once https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6318 merges

**Comment by jsturtevant** [comment]
these changes will fix #4889

**Comment by marosset** [comment]
> Is this PR ready to move out of draft status?

The necessary changes in cloud-provider-azure merged so yup!

**Review by nojnhuh — APPROVED** [review]
/lgtm

Thank you for this!

**Review by willie-yao — APPROVED** [review]
/lgtm
/approve

**Comment by nojnhuh** [comment]
tests passed!
/hold cancel

**Pull request merged**
