### PR TITLE
[release-1.3] Support using a customized template outside CAPZ repo

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

 

 
**What type of PR is this?**
/kind feature
/bug

**What this PR does / why we need it**:
Support using a customized template outside CAPZ repo. A customized template can be one on the host or a link.
cherrypicks: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2299
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Support using a customized template outside CAPZ repo. A customized template can be one on the host or a link.
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
@lzhecheng this changeset lgtm, looks like the same as merged earlier today:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2300/files

Do we want to wait a day or so to let the changes to main bake before merging this to the release branch?

**Comment by lzhecheng** [comment]
> @lzhecheng this changeset lgtm, looks like the same as merged earlier today:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2300/files
> 
> Do we want to wait a day or so to let the changes to main bake before merging this to the release branch?

We can wait to make sure the PR introduces no bug.

**Comment by lzhecheng** [comment]
@jackfrancis I saw your PR to upgrade capz in test-infra repo:
https://github.com/kubernetes/test-infra/pull/26200#issuecomment-1128119292

Is it a best practice that this PR merged first and your PR merged then? So on release-1.3, this PR can be verified? Please correct me if I'm wrong.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
/retest

looking into flakes https://kubernetes.slack.com/archives/CEX9HENG7/p1652914570497179

**Pull request merged**
