### PR TITLE
Bump Windows Calico to v3.25.0

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: The Calico Helm chart is now on the latest version (v3.25.0), this bumps the version in CAPZ to be the same so Windows nodes use the same Calico version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Updated Windows Calico to v3.25.0
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/lgtm
/approve

Tests will tell the tale.

Btw @CecileRobertMichon are things broken until we update this, or were we just observant enough to notice the bump to v3.25.0 via recent helm chart installs?

**Comment by CecileRobertMichon** [comment]
> are things broken until we update this, or were we just observant enough to notice the bump to v3.25.0 via recent helm chart installs?

the latter (because I was watching v3.25 closely because of #3115). Things might break if there was a breaking change in a Calico minor release but the last few we've been lucky. Hopefully we can get out of this split situation and move the Windows stuff to the Calico Helm chart short term enough that we never run into an issue.

cc @marosset

**Comment by CecileRobertMichon** [comment]
New Calico templates have a typo in "overriden" 😢

**Comment by jackfrancis** [comment]
@CecileRobertMichon did you manually correct the spelling?

**Comment by CecileRobertMichon** [comment]
@jackfrancis no I can't it's auto-generated, https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3142/commits/5eccfdf18cf06ef4d3984d24e5a847b321488bb4

but I'm on my way to make a PR to calico to fix the typo...

**Comment by CecileRobertMichon** [comment]
Normal   Pulling      20m (x4 over 21m)    kubelet            Pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
  Warning  Failed       20m (x4 over 21m)    kubelet            Error: ErrImagePull
  Normal   BackOff      2m9s (x83 over 21m)  kubelet            Back-off pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
retrying in case it was a timing fluke....

/retest

**Comment by CecileRobertMichon** [comment]
@marosset 

tests are failing with

```
Normal Pulling 20m (x4 over 21m) kubelet Pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
Warning Failed 20m (x4 over 21m) kubelet Error: ErrImagePull
Normal BackOff 2m9s (x83 over 21m) kubelet Back-off pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
``` 

any ideas what could be wrong?

**Comment by marosset** [comment]
> @marosset
> 
> tests are failing with
> 
> ```
> Normal Pulling 20m (x4 over 21m) kubelet Pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
> Warning Failed 20m (x4 over 21m) kubelet Error: ErrImagePull
> Normal BackOff 2m9s (x83 over 21m) kubelet Back-off pulling image "sigwindowstools/calico-install:v3.25.0-hostprocess"
> ```
> 
> any ideas what could be wrong?

The image is showing as available at https://hub.docker.com/layers/sigwindowstools/calico-install/v3.25.0-hostprocess/images/sha256-2127458c1f0b989888e1be402225776f2fa5469663bfb78fea43d3ffdef2b713?context=explore
as was pushed yesterday.
I'm not sure...?

**Comment by CecileRobertMichon** [comment]
let's try again :/

/retest

**Comment by marosset** [comment]
I built / pushed the images after downgrading to buildx v.0.9.1 so the image pull issue should now be resolved.
Still looking for a longterm solution for building / pushing images with newer versions of buildx tho.

**Review by marosset — APPROVED** [review]
/lgtm

**Pull request merged**
