### PR TITLE
[release-1.3] Help windows cloud-node-manager to be better provisioned

### PR DESCRIPTION
**Pull request by monianshouhou**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2480, https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2511, https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2515
When the release-1.4 is not available, cloud-provider-azure needs to use the release-1.3 to test the Windows worker node.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by monianshouhou** [comment]
@jackfrancis PTAL.

**Comment by mboersma** [comment]
So this is a manual cherry-pick PR that combines three others? The usual process is to ask the prow bot to `/cherrypick release-1.3`, but I see all three were cherry-picked only to release-1.4.

Is there any reason we shouldn't have the bot cherry-pick each PR? It just seems a bit cleaner to me in the commit log to do it that way.

**Comment by monianshouhou** [comment]
> So this is a manual cherry-pick PR that combines three others? The usual process is to ask the prow bot to `/cherrypick release-1.3`, but I see all three were cherry-picked only to release-1.4.
> 
> Is there any reason we shouldn't have the bot cherry-pick each PR? It just seems a bit cleaner to me in the commit log to do it that way.

I manually cherry-pick PR because one combined PR looks more concise. It makes sense about the commit log thing. I will cherrypick each PR seperately.

**Comment by mboersma** [comment]
> I will cherrypick each PR seperately.

@monianshouhou sorry, I didn't mean to shut this down. I think it's ok to squash them together but was curious if other maintainers had a strong opinion.

Thank you for doing this, I see that you cherry-picked a couple already and I'll review them.

**Comment by mboersma** [comment]
As best I can tell, `go-apidiff` is built successfully and then has an internal error that points to [this line](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/release-1.3/util/reconciler/defaults.go#L20) which seems completely fine to me. Any ideas?

**Comment by CecileRobertMichon** [comment]
/close

release-1.3 is no longer supported, all backports should be in release-1.4 and release-1.5

**Pull request closed without merging**
