### PR TITLE
Add jsturtevant to reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Adding @jsturtevant to CAPZ reviewers as he's made lots of [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+jsturtevant+is%3Aclosed) to the project both as an author and as a reviewer. Thank you for all your contributions so far @jsturtevant! 

/assign @nader-ziada @devigned @alexeldeib @shysank

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sonasingh46** [comment]
+1

**Comment by shysank** [comment]
+1

**Comment by devigned** [comment]
+1

**Comment by jsturtevant** [comment]
Thanks for the support! ❤️

**Comment by jackfrancis** [comment]
+1

**Comment by mboersma** [comment]
+1

**Comment by CecileRobertMichon** [comment]
need an lgtm to merge

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
