### PR TITLE
test: validate VMSS accelerated networking during E2E

### LINKED ISSUE #1015: Accelerated networking test should handle VMSS instances
/kind bug

**What steps did you take and what happened:**

The test spec in test/e2e/azure_accelnet.go only loops over VMs in the resource group, so it's not testing the accelerated networking property of any VMSS / MachinePool clusters. It should be expanded and added to cover the VMSS spec that's now in azure_test.go.

**What did you expect to happen:**

e2e tests validate the accelerated networking property on VMSS instances is set as expected (`true` if it's available for the SKU).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

**What this PR does / why we need it**:

This PR adds VMSS accelerated networking E2E coverage, mimic'ing the VM coverage. This is hacky, but I'm just following the existing pattern (apologies for any offense if I'm saying the existing implementation is hacky!)

Because this adds coverage where there is none, perhaps a functional, if hacky, solution is fine for now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1015

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ x ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
#1245 has merged, please rebase to fix quota issues

**Comment by mboersma** [comment]
/lgtm

Thanks @jackfrancis. This should work fine, apologies for the hacky existing test.

**Pull request merged**
