### PR TITLE
🌱 Promote devigned and nader-ziada to maintainers, add cpanato as reviewer

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: @devigned and @nader-ziada have both been very active and done great work as reviewers for the last 3 months, promoting them to maintainer as we need more PR approvers. @cpanato has been making quality contributions to the codebase in many different areas of the code so I'd like him to step in as a reviewer to help ensure quality of the codebase.

/hold
for lazy consensus until Friday's office hours

/assign @justaugustus @awesomenix 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vincepri** [comment]
+1

Thank you all for the great support and contributions!

**Comment by cpanato** [comment]
thanks for the invite and trust <3

**Comment by awesomenix** [comment]
/approve
/lgtm

Thanks for all the contributions

**Comment by justaugustus** [comment]
/lgtm
/approve

Nader, David, and Carlos have been phenomenal contributors to capz for quite some time, and I'm excited to see them step into the next respective steps in the maintainership ladder!

**Pull request merged**
