### PR TITLE
suppress cloud-init wget download progress output

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

In order to better troubleshoot CI failures for custom-built k8s bits, this PR modifies the wget command used by our `preKubeadmCommand' so that we only return basic output. E.g.:

```
$ wget https://storage.googleapis.com/k8s-release-dev/ci/v1.25.0-alpha.1.29+19c8a2127177b4/bin/linux/amd64/kubectl -nv -O ./kubectl
2022-06-17 14:55:47 URL:https://storage.googleapis.com/k8s-release-dev/ci/v1.25.0-alpha.1.29+19c8a2127177b4/bin/linux/amd64/kubectl [44089344/44089344] -> "./kubectl" [1]
$ wget https://storage.googleapis.com/k8s-release-dev/ci/v1.25.0-alpha.1.29+19c8a2127177b4/bin/linux/amd64/kubectlbogon -nv -O ./kubectl
https://storage.googleapis.com/k8s-release-dev/ci/v1.25.0-alpha.1.29+19c8a2127177b4/bin/linux/amd64/kubectlbogon:
2022-06-17 14:55:54 ERROR 404: Not Found.
```

Compare to the current log output we persist to `/var/log/cloud-init-output.log`:

```
[2022-06-17 11:32:41] --2022-06-17 11:32:41--  https://storage.googleapis.com/k8s-release-dev/ci/v1.25.0-alpha.1.29+19c8a2127177b4/bin/linux/amd64/kubectl
[2022-06-17 11:32:41] Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.16.240, 142.250.200.16, 142.250.200.48, ...
[2022-06-17 11:32:41] Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.16.240|:443... connected.
[2022-06-17 11:32:42] HTTP request sent, awaiting response... 200 OK
[2022-06-17 11:32:42] Length: 44089344 (42M) [application/octet-stream]
[2022-06-17 11:32:42] Saving to: ‘/tmp/k8s-ci/kubectl’
[2022-06-17 11:32:42] 
[2022-06-17 11:32:42]      0K .......... .......... .......... .......... ..........  0% 12.2M 3s
[2022-06-17 11:32:42]     50K .......... .......... .......... .......... ..........  0% 20.6M 3s
[2022-06-17 11:32:42]    100K .......... .......... .......... .......... ..........  0% 21.1M 2s
....  0% 47.2M 2s
[2022-06-17 11:32:42]    200K .......... .......... .......... .......... ..........  0% 36.9M 2s
[2022-06-17 11:32:42]    250K .......... .......... .......... .......... ..........  0% 12.2M 2s
[2022-06-17 11:32:42]    300K .......... .......... .......... .......... ..........  0% 54.8M 2s
[2022-06-17 11:32:42]    350K .......... .......... .......... .......... ..........  0% 60.2M 2s
[2022-06-17 11:32:42]    400K .......... .......... .......... .......... ..........  1% 58.8M 2s
[2022-06-17 11:32:42]    450K .......... .......... .......... .......... ..........  1% 49.7M 2s
[2022-06-17 11:32:42]    500K .......... .......... .......... .......... ..........  1% 48.5M 2s
[2022-06-17 11:32:42]    550K .......... .......... .......... .......... ..........  1% 58.4M 1s
[2022-06-17 11:32:42]    600K .......... .......... .......... .......... ..........  1% 56.0M 1s
[2022-06-17 11:32:42]    650K .......... .......... .......... .......... ..........  1% 56.2M 1s
[2022-06-17 11:32:42]    700K .......... .......... .......... .......... ..........  1% 53.4M 1s
...
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @lzhecheng

**Review by CecileRobertMichon — COMMENTED** [review]
@jackfrancis do you want to merge this one separately or are you going to add the other script fixes to it?

/lgtm

**Comment by jackfrancis** [comment]
@CecileRobertMichon let's merge this as it may actually help the discussion here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2398 (not yet lgtm'd by anyone)

Once this lands it'll make it much easier for folks to do investigation which should help consensus around whether or not to merge the above PR.

**Pull request merged**
