### PR TITLE
Remove DNS workaround for ipv6 templates

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: See https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4210

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4210

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> [FAILED] Failed to generate the manifest for "addon-helm" / "v0.1.0-alpha.10"

/retest

unrelated prow network flake

**Comment by CecileRobertMichon** [comment]
/retest

security rules flake

**Comment by CecileRobertMichon** [comment]
/retest

Unfortunate that the dual stack test failed on this one, but it does look like an unrelated Azure error (`InternalExecutionError`) creating the load balancer

**Review by mboersma — COMMENTED** [review]
/lgtm

/assign @nojnhuh

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
