### PR TITLE
docs: Add documentation on the release process

### LINKED ISSUE #97: Document versioning and release process
ref: #92
/milestone baseline 
/assign

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #97 

**Release note**:

```release-note
NONE
```

/kind documentation
/assign @soggiest @tariq1890 
/cc @chuckha

### CODE REVIEW

**Comment by justaugustus** [comment]
@soggiest -- Nope; just for the code itself.

**Comment by tariq1890** [comment]
lgtm. @soggiest I don't believe I've seen copyright headers being used for markdown files

**Comment by justaugustus** [comment]
@tariq1890 -- If you're approving, please:
```
/lgtm
/approve
```

**Comment by justaugustus** [comment]
Sorry @k8s-ci-robot, wasn't trying to self-lgtm! :stuck_out_tongue_closed_eyes: 
/meow space

**Pull request merged**
