### PR TITLE
Add alexeldeib to cluster-api-azure-maintainers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind other

**What this PR does / why we need it**: As discussed in last week's [office hours](https://www.youtube.com/watch?v=ExjKYDG-N4c), @alexeldeib has made meaningful + high-quality contributions for a while now and we would like to promote him to approver. Thank you and congrats @alexeldeib! 🎉 

/cc @devigned @nader-ziada @shysank @juan-lee 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
lgtm

**Comment by shysank** [comment]
lgtm

**Comment by devigned** [comment]
lgtm

**Comment by alexeldeib** [comment]
happy to be here 🎉

**Comment by CecileRobertMichon** [comment]
@nader-ziada can I get an lgtm/approve label on this?

**Comment by nader-ziada** [comment]
/lgtm
/approve

 🎉

**Comment by CecileRobertMichon** [comment]
Welcome @alexeldeib 🎉

When you get a chance please open PRs to add yourself the following OWNERS files:

https://github.com/kubernetes/k8s.io/blob/cb153ca944c0511206e5b26cf44dacf993f17c01/k8s.gcr.io/images/k8s-staging-cluster-api-azure/OWNERS
https://github.com/kubernetes/test-infra/blob/f8a90c0f33ec96557a56c4137a54effeaa71dcb1/config/jobs/kubernetes-sigs/cluster-api-provider-azure/OWNERS
https://github.com/kubernetes/org/blob/d34a80cdb4179a33aaeca0b79ccbdf3038c7aad8/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L109

**Pull request merged**
