### PR TITLE
Add cluster's name to MachinePool and AzureManagedMachinePool in AKS templates

### LINKED ISSUE #2811: Update clusterctl AKS flavor for easier kubectl apply of multiple templates in the same namespace
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When following the managed cluster documentation, <https://capz.sigs.k8s.io/topics/managedcluster.html>, everything works as expected when creating the first cluster. The issue starts when a user tries to generate a second cluster template using clusterctl, then kubectl apply to the same namespace. The issues can be resolved by updating MachinePool and AzureManagedMachinePool resources in the template. I believe it would be helpful for newer users if the AKS flavor template was modified to allow the example below to work without having to manually modify the generated yaml file.

Example:

```bash

clusterctl generate cluster cluster-01 --kubernetes-version v1.24.6 --control-plane-machine-count=1 --worker-machine-count=1 --flavor=aks > cluster-01.yaml
clusterctl generate cluster cluster-02 --kubernetes-version v1.24.6 --control-plane-machine-count=1 --worker-machine-count=1 --flavor=aks > cluster-02.yaml

# This works as expected.
kubectl apply -f cluster-01.yaml
# This fails if MachinePool and AzureManagedMachinePool names are not updated.
kubectl apply -f cluster-02.yaml

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Example error message:

```txt

Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.x-k8s.io/v1beta1\",\"kind\":\"MachinePool\",\"metadata\":{\"annotations\":{},\"name\":\"pool0\",\"namespace\":\"default\"},\"spec\":{\"clusterName\":\"cluster-02\",\"replicas\":1,\"template\":{\"metadata\":{},\"spec\":{\"bootstrap\":{\"dataSecretName\":\"\"},\"clusterName\":\"cluster-02\",\"infrastructureRef\":{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta1\",\"kind\":\"AzureManagedMachinePool\",\"name\":\"pool0\"},\"version\":\"v1.24.6\"}}}}\n"}},"spec":{"clusterName":"cluster-02","template":{"spec":{"clusterName":"cluster-02"}}}}
to:
Resource: "cluster.x-k8s.io/v1beta1, Resource=machinepools", GroupVersionKind: "cluster.x-k8s.io/v1beta1, Kind=MachinePool"
Name: "pool0", Namespace: "default"
for: "cluster-02.yaml": error when patching "cluster-02.yaml": admission webhook "validation.machinepool.cluster.x-k8s.io" denied the request: MachinePool.cluster.x-k8s.io "pool0" is invalid: spec.clusterName: Forbidden: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.x-k8s.io/v1beta1\",\"kind\":\"MachinePool\",\"metadata\":{\"annotations\":{},\"name\":\"pool1\",\"namespace\":\"default\"},\"spec\":{\"clusterName\":\"cluster-02\",\"replicas\":1,\"template\":{\"metadata\":{},\"spec\":{\"bootstrap\":{\"dataSecretName\":\"\"},\"clusterName\":\"cluster-02\",\"infrastructureRef\":{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta1\",\"kind\":\"AzureManagedMachinePool\",\"name\":\"pool1\"},\"version\":\"v1.24.6\"}}}}\n"}},"spec":{"clusterName":"cluster-02","template":{"spec":{"clusterName":"cluster-02"}}}}
to:
Resource: "cluster.x-k8s.io/v1beta1, Resource=machinepools", GroupVersionKind: "cluster.x-k8s.io/v1beta1, Kind=MachinePool"
Name: "pool1", Namespace: "default"
for: "cluster-02.yaml": error when patching "cluster-02.yaml": admission webhook "validation.machinepool.cluster.x-k8s.io" denied the request: MachinePool.cluster.x-k8s.io "pool1" is invalid: spec.clusterName: Forbidden: field is immutable

```

**Environment:**

- cluster-api-provider-azure version: 1.5.4
- Kubernetes version: (use `kubectl version`): 1.24.6
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

### PR DESCRIPTION
**Pull request by AAkindele**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Add the cluster's name to the MachinePool and AzureManagedMachinePool resources in the AKS flavor templates. The previous short names, like pool0 and pool1, are added as spec.name in AzureManagedMachinePool. This keeps the nodepool names in Azure the same as before. This will make it easier for users to generate multiple AKS templates with clusterctl and apply them to the same namespace without extra modifications.

This also fixes an issue where the reconciler can't find the node pool VMSS when the AzureManagedMachinePool `metadata.name` is different from `spec.name`. Using the example below, the reconciler would look for the nodepool with the name capi-cluster-01-pool0 instead of pool0. This has been fixed to look for pool0.

example:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: capi-cluster-01-pool0
  namespace: default
spec:
  enableNodePublicIP: false
  mode: System
  name: pool0
  osDiskSizeGB: 30
  sku: Standard_A2_v2
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2811

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update node pool names in AKS flavor templates to include the cluster's name

Update AzureManagedMachinePool reconciler to use spec.name to find the matching node pool VMSS
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@AAkindele this generally looks ready for review, can you promote this from a draft PR to a real PR, and remove the `WIP` in the title? Thanks!

**Review by nojnhuh — APPROVED** [review]
Took this for another spin and it works great!
/lgtm

**Comment by jackfrancis** [comment]
/approve

thank you @AAkindele !

**Pull request merged**
