### PR TITLE
🌱 bump capi to v0.3.10

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- update cluster-api dependency to v0.3.10

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
we might not want to merge this PR, but just to test out the new capi release and find any issues early

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump cluster-api version to  v0.3.10
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
This PR in cluster-api https://github.com/kubernetes-sigs/cluster-api/pull/3651 changed how the tests get their templates, so we would have to do the same here if we use the tests as-is :(

**Comment by CecileRobertMichon** [comment]
@nader-ziada what exactly changed in kubernetes-sigs/cluster-api#3651 that requires changes here? If it's a breaking change it needs to be called out in the 0.3.10 release notes

**Comment by nader-ziada** [comment]
> @nader-ziada what exactly changed in [kubernetes-sigs/cluster-api#3651](https://github.com/kubernetes-sigs/cluster-api/pull/3651) that requires changes here? If it's a breaking change it needs to be called out in the 0.3.10 release notes

its in the capi tests themselves, the tests are looking for a template with a specific file name and some changes in the template itself

**Comment by CecileRobertMichon** [comment]
FYI @fabriziopandini 

I think CAPZ is the only provider besides Docker than runs the CAPI E2E tests but might be worth calling out in release notes anyways.

**Comment by nader-ziada** [comment]
@CecileRobertMichon all I had to do to fix the capi tests is update the templates:
 - for kcp-adoption use different labels;  `kcp-adoption.step1` instead of `initial` and `kcp-adoption.step2` instead of `kcp`
 - for `mhc` test; use a flavor of `mhc` by adding the same cluster-template file we already use but call it `cluster-template-mhc.yaml`

**Comment by fabriziopandini** [comment]
@CecileRobertMichon gotcha!
sorry for causing troubles

**Comment by nader-ziada** [comment]
rebased to include the ipv6 PR, and run the capi tests with it

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by CecileRobertMichon** [comment]
The adoption test seems broken in the master branch even with capi 0.3.9 https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-capi-e2e

**Comment by CecileRobertMichon** [comment]
it looks like it started failing with https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/5f7473fd8221248ca01e35365e4e862a27bf5acf

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/965 should fix it

**Comment by nader-ziada** [comment]
updated the templates and running the tests again

**Comment by nader-ziada** [comment]
/hold

for capi-0.3.10 release coming soon

**Comment by CecileRobertMichon** [comment]
@nader-ziada maybe we should run the tests on CAPI main branch to test the latest before the release is cut, wdyt?

**Comment by nader-ziada** [comment]
> ts on CAPI main branch to test the latest before the release is cut, wdyt?

we can, but there are PR still in progress, so we still need to run the tests again anyways

**Comment by nader-ziada** [comment]
actually rc.1 just came out so switched to that

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
will try again to see if it was just a timeout issue

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
increased the timeout used by the capi test to see if that's the issue

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by nader-ziada** [comment]
the capi tests passed after increasing the timeout for the upgrade tests

now of the azure tests failed, but these already passed before so will try one more time while investigating 

 /test pull-cluster-api-provider-azure-e2e

**Comment by vincepri** [comment]
@nader-ziada Can we use the newly v0.3.10 tag for these now?:)

**Comment by nader-ziada** [comment]
all passed with final v0.3.10

**Comment by vincepri** [comment]
LGTM

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
