### PR TITLE
Update klog dependency to v2

### PR DESCRIPTION
**Pull request by stmcginnis**
**What this PR does / why we need it**:

The klog v1 dependency used is quite old now, and the k/k repo has
switched to more recent v2 versions for quite some time now.

This updates klog usage to use the v2 package version.

**Special notes for your reviewer**:

This is part of an overall effort along with updating the k-sigs/cluster-api repo here:

https://github.com/kubernetes-sigs/cluster-api/pull/4284

**Release note**:

```release-note
NONE
```

/kind cleanup

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
should we wait until kubernetes-sigs/cluster-api#4284 is merged and bump the capi nightly build version before doing this?

**Comment by nader-ziada** [comment]
@stmcginnis would you mind updating the capi nightly release used in capz as part of this PR as well?

we can use `nightly_master_20210315`

The capi release is mentioned in 3 files:
- Makefile
- Tiltfile
- test/e2e/config/azure-dev.yaml

**Comment by stmcginnis** [comment]
Rebased on master to pick up some other changes to the Tiltfile.

**Comment by stmcginnis** [comment]
Job failures don't look related to this change.

/test pull-cluster-api-provider-azure-e2e

**Comment by stmcginnis** [comment]
> ERROR: (AuthenticationFailed) Authentication failed.

Definitely not related to this change. Third times a charm?

/test pull-cluster-api-provider-azure-e2e

**Comment by nader-ziada** [comment]
> > ERROR: (AuthenticationFailed) Authentication failed.
> 
> Definitely not related to this change. Third times a charm?
> 
> /test pull-cluster-api-provider-azure-e2e

we think its because of an Azure ADD issue, waiting for it to be resolved

**Comment by stmcginnis** [comment]
/test pull-cluster-api-provider-azure-e2e-windows

Test timeout.

**Comment by stmcginnis** [comment]
/test pull-cluster-api-provider-azure-e2e

Whack a mole. :)

**Comment by CecileRobertMichon** [comment]
Looks like we're getting hit by quota issues in the CNCF sub, I'm looking into it

```
E0316 20:55:14.568097       1 controller.go:302] controller-runtime/manager/controller/azuremachine "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create virtual machine: failed to create VM capz-e2e-jv25q7-control-plane-x4gs5 in resource group capz-e2e-jv25q7: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"OperationNotAllowed\" Message=\"Operation could not be completed as it results in exceeding approved standardDSv3Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: southcentralus, Current Limit: 220, Current Usage: 220, Additional Required: 2, (Minimum) New Limit Required: 222. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22===REDACTED===%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests.\"" "name"="capz-e2e-jv25q7-control-plane-x4gs5" "namespace"="create-workload-cluster-qrxh3z" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" 
```

**Comment by CecileRobertMichon** [comment]
Opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1245 to mitigate

**Comment by CecileRobertMichon** [comment]
#1245 has merged, please rebase to fix quota issues

**Comment by stmcginnis** [comment]
Rebased to pick up the latest.

**Pull request merged**
