### PR TITLE
Update ci-version jobs to use new environment variables for identities

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This PR updates a few user assigned identity IDs that weren't updated with the new environment variables for CI_RG and USER_IDENTITY. It was causing this test to fail: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-conformance-custom-builds

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Just curious, will this PR help devs in running tests locally by setting their own `CI_RG` & `USER_IDENTITY`?

**Comment by willie-yao** [comment]
> Just curious, will this PR help devs in running tests locally by setting their own `CI_RG` & `USER_IDENTITY`?

Yes this replaces all occurrences of `/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/capz-ci/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cloud-provider-user-identity` without the environment variables. The local test templates should already use the environment variables as seen [here](https://github.com/willie-yao/cluster-api-provider-azure/blob/b80dee28252394c061d1a221991c3f8f7bf3ecf0/templates/cluster-template.yaml#L130).

**Comment by jackfrancis** [comment]
Carried over into #5043

**Pull request closed without merging**
