### PR TITLE
test: Add functionality to collect init container logs

### PR DESCRIPTION
**Pull request by chandankumar4**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

- Add functionality for collection init container logs as well with main container logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1862

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Comment by CecileRobertMichon** [comment]
@chandankumar4 the two failing tests are currently known failing https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4180, unrelated to your PR

**Comment by CecileRobertMichon** [comment]
/retest

the failing jobs should be fixed now

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

Awesome thank you @chandankumar4! Checked the logs to make sure everything looks good and can see the init container logs got collected for Calico node

**Review by nawazkh — COMMENTED** [review]
/lgtm
Good work @chandankumar4 !!

**Pull request merged**
