### PR TITLE
update codecov workflow name

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- Updates the Codecove-cover.yaml workflow name for better looking GitHub actions tab.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by marosset** [comment]
Not directly related to these changes but if you add the following as the first line in the workflows this will enable auto completion in vs code and other editions.

```
 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
```

**Comment by nawazkh** [comment]
> Not directly related to these changes but if you add the following as the first line in the workflows this will enable auto completion in vs code and other editions.
> 
> ```
>  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
> ```

Thanks for the cool suggestion @marosset! 
I added `# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json` modeline for the current yaml.

**Review by marosset — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
