### PR TITLE
decoupling using K8s ci binaries and different versions of containerd for ci windows templates

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

 

 
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR separates replaces updating containerd bits and updating kubernetes bits into separate kubeadm actions for windows.
This PR also adds the kubeadm action to update container binaries to all templates CI templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by marosset** [comment]
/hold
while I do some manual validation

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @jackfrancis

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
