### PR TITLE
bump CAPI to v1.3.3

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates the cluster-api dependency to recent release v1.3.3. See https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.3

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
bump CAPI to v1.3.3
```

### CODE REVIEW

**Comment by nawazkh** [comment]
Thanks for putting this together! 
I am curious on how we generally test CAPI version upgrades? 
Apart from relying on e2e tests, are there any more validations we can do on our local to test these changes?

**Comment by CecileRobertMichon** [comment]
> I am curious on how we generally test CAPI version upgrades?

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by mboersma** [comment]
The other pertinent change I notice in the CAPI release notes is

> Update cert-manager to v1.11.0

CAPZ should sync up with that too. Should I add that to this PR, or create a separate one?

**Comment by CecileRobertMichon** [comment]
> CAPZ should sync up with that too. Should I add that to this PR, or create a separate one?

+1 for separate PR

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
> /cherry-pick release-1.7

any reason for not cherry-picking to release-1.6 too?

**Comment by mboersma** [comment]
> any reason for not cherry-picking to release-1.6 too?

release-1.6 is still on CAPI v1.2.x: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/release-1.6/go.mod#L214

**Comment by mboersma** [comment]
But you pointed out @CecileRobertMichon that we should update release-1.6 to CAPI v1.2.10; I'll do that.

**Comment by CecileRobertMichon** [comment]
@mboersma I think something is wrong with `capz-e2e: [It] Running the Cluster API E2E tests Running the MachineDeployment rollout spec Should successfully upgrade Machines upon changes in relevant MachineDeployment fields`

**Comment by mboersma** [comment]
CI failures are:

`BuildKit is enabled but the buildx component is missing or broken.`

**Comment by mboersma** [comment]
I've tried to reproduce this failure twice locally, but it passed.

```shell
% SKIP_CLEANUP=true SKIP_LOG_COLLECTION=true GINKGO_SKIP="" \
  GINKGO_FOCUS="Running the MachineDeployment rollout spec" \
  ./scripts/ci-e2e.sh
```

**Comment by CecileRobertMichon** [comment]
@mboersma it looks like the periodic job is also failing the same spec since last week https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main

**Comment by CecileRobertMichon** [comment]
@mboersma looks like both PR tests and periodic tests are running into a similar issue as https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3108 (suite is timing out after the machine rollout jobs hits a 3h55 time in the cleanup phase, after the actual test passed)

**Comment by mboersma** [comment]
I added a 30s timeout to the sshConfig after reading #3108, and the CAPI `MachineDeployment rollout` spec passed for the first time (after four failures). This isn't definitive, but I'm hopeful. I'll make a separate PR of the timeout fix.

**Comment by CecileRobertMichon** [comment]
/hold

for rebase

**Pull request merged**
