### PR TITLE
Update opentelemetry-go to v1.3.0

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates opentelemetry-go to v1.3.0, and its unstable packages to v0.26.0. Also updates the otel helm chart to v0.8.3 and adjusts a few values to match.

See https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.3.0

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

I've tested this locally and metrics and traces (to App Insights and to Jaeger) work fine.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/retest-required

Some unrelated AKS provisioning failure.

**Comment by mboersma** [comment]
/retest

(Although the failure was unrelated and not blocking, I don't think reviewers look at PRs if they're red.)

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
