### PR TITLE
Add e2e spec name as cluster name suffix

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Improve debugging experience by including the cluster type in the cluster name so we can easily find the right log folder, etc. instead of having to remember a random 6 char string.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> Code=\"DomainNameLabelReserved\" Message=\"The domain name label capz-e2e-a4mcau-windows-vmss-b9ee80b9 is invalid. The name itself or part of the name is a reserved word such as a trademark. Please use a different name.\"

that's a fun error... so we can't use windows as part of the cluster name...

**Comment by CecileRobertMichon** [comment]
seeing some new accelerated net flakes I haven't seen before

/retest

**Comment by CecileRobertMichon** [comment]
/assign @devigned 

I think this is ready. The GPU flake is one we've seen before and is unrelated to this PR https://kubernetes.slack.com/archives/CEX9HENG7/p1626374011492600

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
