### PR TITLE
use AKS 1.22 for e2e exp

### PR DESCRIPTION
**Pull request by zmalik**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

use kubernetes 1.22 for AKS also. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
do we want to cherry-pick this one?

**Comment by jackfrancis** [comment]
I think we need to if 1.19 has been deprecated

**Pull request merged**
