### PR TITLE
[Release-1.7] AzureMachinePool windows template fixes

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
AzureMachinePool windows fixes to
- to set disk size to 128gb
- honor WINDOWS_SERVER_VERSION
- use newer pause image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixes for AzureMachinePool running Windows
```

### CODE REVIEW

**Comment by marosset** [comment]
manual cherry-pick of #3311 into `release-1.7`

**Comment by CecileRobertMichon** [comment]
Can you please amend the commit message and PR title to be the same as the original commit? And add [release-1.7] prefix to the title

**Comment by marosset** [comment]
> Can you please amend the commit message and PR title to be the same as the original commit? And add [release-1.7] prefix to the title

Done

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
