### PR TITLE
ci: external cloud-provider-azure includes Windows

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This PR adds a Windows node pool to the external cloud-provider-azure test scenario.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
test Windows external cloud-provider-azure
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
AFAIK we're not actually testing OOT cloud-provider in PRs if we don't run

/test pull-cluster-api-provider-azure-e2e-optional

**Comment by CecileRobertMichon** [comment]
@jackfrancis should we close this in favor of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2165? I'm going to be starting on that one soon

**Comment by jackfrancis** [comment]
@CecileRobertMichon I think that if we get this working in this PR it'll make that other workstream a bit easier (you'll already have the Windows part done).

I don't recall if the test failure is a signal here, lemme retest this PR.

**Comment by jackfrancis** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3105

**Pull request closed without merging**
