### PR TITLE
Update godoc of CapacityReservationGroupID of AzureMachineSpec

### LINKED ISSUE #4829: In the godoc of CapacityReservationGroupID of AzureMachineSpec include an explanation of what are the requirements for the ID
/kind cleanup

**What needs cleanup:**
- Add explanation of what are the requirements for the `CapacityReservationGroupID` field.

**Describe the solution you'd like**
Change the current godoc of `CapacityReservationGroupID` field in `AzureMachineSpec` from
```go
	// CapacityReservationGroupID specifies the capacity reservation group resource id that should be
	// used for allocating the virtual machine.
	// +optional
	CapacityReservationGroupID *string `json:"capacityReservationGroupID,omitempty"`
```
to
```go
	// CapacityReservationGroupID specifies the capacity reservation group resource id that should be
	// used for allocating the virtual machine.
	// The field size should be greater than 0 and the field input must start with '/'.
	// The input for capacityReservationGroupID must be similar to '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/capacityReservationGroups/{capacityReservationGroupName}'.
	// The keys which are used should be among 'subscriptions', 'providers' and 'resourcegroups' followed by valid ID or names respectively.
	// It is optional but may not be changed once set.
	// +optional
	CapacityReservationGroupID *string `json:"capacityReservationGroupID,omitempty"`
```

Files to change: 2

- [ ] api/v1beta1/azuremachine_types.go
  - Specific lines to cleanup: 146-147

**Anything else you would like to add:**

### PR DESCRIPTION
**Pull request by arkadeepsen**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updates the godoc of `CapacityReservationGroupID` of `AzureMachineSpec`. The updated godoc contains the explanation of what the requirements are for the `CapacityReservationGroupID`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4829 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @arkadeepsen!

The `azuremachine_types.go` file is used in generating the CRD definitions. So you need to run `make generate` and commit those changes or this will fail the `make verify-gen` check.

**Comment by arkadeepsen** [comment]
> Thanks @arkadeepsen!
> 
> The `azuremachine_types.go` file is used in generating the CRDs. So you need to run `make generate` and commit those changes or this will fail the `make verify-gen` check.

@mboersma my bad. Thanks for pointing that out. I have run `make generate` and pushed the changes.

**Review by willie-yao — COMMENTED** [review]
I'm not so sure if we need to be making this change since the validation is already being done in [ValidateCapacityReservationGroupID](https://github.com/willie-yao/cluster-api-provider-azure/blob/5243ae7d5dae9483280e73da2904a3568fbf8839/api/v1beta1/azuremachine_validation.go#L463). I think the clarity helps but other fields that have similar requirements do not include this information in the godoc. @jackfrancis @mboersma what's your take on this?

**Comment by arkadeepsen** [comment]
> I see the validation is already being done in [ValidateCapacityReservationGroupID](https://github.com/willie-yao/cluster-api-provider-azure/blob/5243ae7d5dae9483280e73da2904a3568fbf8839/api/v1beta1/azuremachine_validation.go#L463). I think the clarity helps but other fields that have similar requirements do not include this information in the godoc. @jackfrancis @mboersma what's your take on this? Was just wondering for the sake of consistency, otherwise lgtm.

Providing a context as to why the change in the godoc is introduced. In OpenShift specific APIs, we try to provide information in the godoc which will be beneficial for the user to create/update a CR. Though, as pointed out, the information is provided when the validation fails, it's good to have the information available beforehand.
P.S. I made the change to the godoc specific to CapacityReservationGroupID as I had worked on the PR which adds the field.

**Comment by mboersma** [comment]
@willie-yao it's a good point–we could argue it should be documented similarly for many other fields. I just assumed this change in particular would be (would have been) helpful for the requestor and perhaps others, and wasn't bothered by the inconsistency. But we should hear from other maintainers.

**Review by willie-yao — COMMENTED** [review]
> In OpenShift specific APIs, we try to provide information in the godoc which will be beneficial for the user to create/update a CR

Sounds good, it definitely doesn't hurt. I'll wait for another opinion from the team before lgtm but I'm good with this change!

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

Plus 1 for additional context to help users coming up with the correct input

**Review by willie-yao — APPROVED** [review]
/approve

**Pull request merged**
