### PR TITLE
Fix: running tests against existing clusters

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind cleanup

#1535 and #1360 broke running tests against existing clusters because the namespaces and secrets where regenerated.

**What this PR does / why we need it**:

this lets a developer use an existing cluster and run the Azure specs against it. When working on tests specs it makes the dev cycle faster to not have to wait for cluster to be created.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
run e2e tests specs against existing capz created clusters
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by jsturtevant** [comment]
looks like the VM failed:

```
E0927 16:57:25.295887       1 controller.go:304] controller-runtime/manager/controller/azuremachinepool "msg"="Reconciler error" "error"="failed to create scale set: failed to get VMSS win-p-win: failed to get result from future: failed checking if the operation was complete: Code=\"OSProvisioningInternalError\" Message=\"OS Provisioning failed for VM 'win-p-win_0' due to an internal error.\"" "name"="capz-e2e-x131w7-win-vmss-mp-win" "namespace"="capz-e2e-x131w7" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachinePool" 
```

```
  "level": "Error",
    "resourceGroupName": "capz-e2e-x131w7-win-vmss",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceId": "/subscriptions/===REDACTED===/resourcegroups/capz-e2e-x131w7-win-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/win-p-win",
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachineScaleSets",
        "localizedValue": "Microsoft.Compute/virtualMachineScaleSets"
    },
    "operationId": "506df8c1-a0fd-4d00-b4e3-19fa40fd075d",
    "operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/write",
        "localizedValue": "Create or Update Virtual Machine Scale Set"
    },
    "properties": {
        "entity": "/subscriptions/===REDACTED===/resourcegroups/capz-e2e-x131w7-win-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/win-p-win",
        "eventCategory": "Administrative",
        "hierarchy": "===REDACTED===",
        "message": "Microsoft.Compute/virtualMachineScaleSets/write",
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"OSProvisioningInternalError\",\"message\":\"OS Provisioning failed for VM 'win-p-win_0' due to an internal error.\"}]}}"
    },
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
```

What is interesting is the Windows kube-proxy show that it started:

```
I0927 16:58:35.144332    6380 node.go:172] Successfully retrieved node IP: 10.1.0.4
I0927 16:58:35.144870    6380 server_windows.go:86] "Detected node IP" IP="10.1.0.4"
I0927 16:58:35.167085    6380 server_windows.go:107] "Using Kernelspace Proxier."
```

**Comment by jsturtevant** [comment]
looks like the prior run did the same: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1733/pull-cluster-api-provider-azure-e2e-windows/1441541769496891392/artifacts/clusters/capz-e2e-y6ay4s-win-vmss/azure-activity-logs/capz-e2e-y6ay4s-win-vmss.log

**Comment by jsturtevant** [comment]
/retest

tests are passing locally, going to try again

**Pull request merged**
