### PR TITLE
explicitly set EXP_ASO_API=true for controller-manager

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR updates the capz-controller-manager manifest to enable the ASOAPI feature flag by default to align with the intent of #4969: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4969/files#diff-bd8758c39c0deb35ee6c5c387594f6575580918777fbf2926f5762c7c9fce755R68

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [X] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixed a bug preventing the ASOAPI feature flag from being enabled by default.
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
/retitle explicitly set EXP_ASO_API=true for controller-manager

/cherry-pick release-1.16
^ This is usually not something we'd cherry-pick, but the release note for #4969 says the flag is enabled by default while it currently is not for a plain `clusterctl init`. This PR should rectify that.

**Comment by nojnhuh** [comment]
Thank you for pointing this out @dtzar!

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
