### PR TITLE
Add Jont828 to reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Adding @Jont828 to CAPZ reviewers as a result of his significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+Jont828+is%3Aclosed) to the project both as an author and as a reviewer. Thank you for all your contributions so far @Jont828!

/assign @mboersma @devigned @alexeldeib @shysank

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

@Jont828 has been a huge help to CAPZ and I would love to see him formalized as a reviewer. Thanks Jonathan, let’s go! 👍🏻

**Comment by jsturtevant** [comment]
/lgtm 
🥳

**Comment by Jont828** [comment]
Thanks everyone!

**Pull request merged**
