### PR TITLE
remove unneeded code copied from CAPI

### PR DESCRIPTION
**Pull request by nojnhuh**
This code was originally added in #4248 so we could update our controller-runtime and ASO without also bumping CAPI. Now that that dust has settled, we can use this code straight from CAPI.

 

 
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This code was originally added in #4248 so we could update our controller-runtime and ASO without also bumping CAPI. Now that that dust has settled, we can use this code straight from CAPI. AFAICT CAPI's implementation this now uses has not drifted from what we had here.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Comment by nojnhuh** [comment]
squashed!
/hold cancel

**Pull request merged**
