### PR TITLE
use default k8s version for spot e2e test

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

It looks like there was some copy-pasta when this test was first made that locked it to the Flatcar test's k8s version which seems like a mistake. This PR removes that to fallback to the default to fix this test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [X] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
/cherry-pick release-1.14
cherry-pick release-1.15

/test pull-cluster-api-provider-azure-e2e-optional

**Comment by nojnhuh** [comment]
@mboersma Is my assumption that the k8s v1.26.13 images are EOL correct based on this log message in the failing tests?

```
E0608 21:06:58.188500       1 controller.go:329] "Reconciler error" err="failed to init machine scope cache: failed to get default image: no VM image found for publisher \"cncf-upstream\" offer \"capi\" sku \"ubuntu-2204-gen1\" with Kubernetes version \"v1.26.13\"" controller="azuremachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureMachine" AzureMachine="capz-e2e-aqq03a/capz-e2e-aqq03a-spot-control-plane-j76xm" namespace="capz-e2e-aqq03a" name="capz-e2e-aqq03a-spot-control-plane-j76xm" reconcileID="f6ef8327-3107-4af3-939d-db22c64664ff"
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1799541282691878912

**Comment by mboersma** [comment]
@nojnhuh yes, (almost) all the v1.26.x images were deprecated on June 5th. But v1.26.15 will be available until August 17th, so if a test really can't update to a more current, supported version of Kubernetes, they can use v1.26.15 for another sixty or so days.

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by nojnhuh** [comment]
Optional job failure is in the cluster class test so I'm reasonably confident that's a flake. The spot test passed.

**Review by willie-yao — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
