### PR TITLE
Update clusterctl API upgrade test versions

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Updates e2e configuration for the new v1.15.1 and v1.14.5 CAPZ releases.

**Which issue(s) this PR fixes**:

None, but see #4822 for prior art.

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@mboersma is `pull-cluster-api-provider-azure-apiversion-upgrade` the sufficient test coverage for this change?

**Comment by mboersma** [comment]
> is `pull-cluster-api-provider-azure-apiversion-upgrade` sufficient test coverage ?

Yes, I think so.

**Comment by jackfrancis** [comment]
> > is `pull-cluster-api-provider-azure-apiversion-upgrade` sufficient test coverage ?
> 
> Yes, I think so.

Thanks. I think we should make this change: https://github.com/kubernetes/test-infra/pull/32646

**Pull request merged**
