### PR TITLE
Update Azure documentation links

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

At some point recently, links to https://azure.microsoft.com/ began failing our link checker (although in reality they are valid).

This skips link checking for two such documentation links, updates many links from "docs.microsoft.com" to "learn.microsoft.com", and removes `en-us/` from links to enable localization.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
```
ERROR: 1 dead links found!
[✖] https://azure.microsoft.com/ → Status: 0
```

**Comment by mboersma** [comment]
Now I'm seeing some 404s accessing `https://azure.microsoft.com/en-us/` directly. So let's wait for the webmasters to sort this out.

**Comment by mboersma** [comment]
I removed the `<!-- markdown-link-check-disable -->` lines temporarily to find that https://azure.microsoft.com/ is still a problem for the link checker. So I think we should merge this.

ping @Jont828 @nojnhuh

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by nojnhuh** [comment]
Did some digging because I was curious and noticed this seems to be the kind of error the link checker is running into:
```
[✖] https://azure.microsoft.com/ → Status: 0 Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:627:28)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:848:9)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:525:35)
    at Socket._onTimeout (node:net:570:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
```

curl seems to agree with a timeout being a possible issue:
```
curl -IL https://learn.microsoft.com/  0.08s user 0.01s system 45% cpu 0.207 total
curl -IL https://azure.microsoft.com/  0.09s user 0.00s system 2% cpu 4.209 total
```

I don't see a way for us to configure that particular timeout here, so overall it seems like ignoring those errors is the most reasonable path forward for now.

**Pull request merged**
