### PR TITLE
Re-add handling of CNI variables in e2e for CAPI suite

### LINKED ISSUE #1377: capz-periodic-capi-e2e-main is failing
looks like https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main is failing since #1371 merged with:

```
    Unexpected error:
        <*yamlprocessor.errMissingVariables | 0xc001048000>: {
            Missing: ["CNI_RESOURCES"],
        }
        value for variables [CNI_RESOURCES] is not set. Please set the value using os environment variables or the clusterctl config file
    occurred
    ```
    
We need to either re-add the CNI_RESOURCES variables, or add CNIs to the templates in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/data/infrastructure-azure

_Originally posted by @CecileRobertMichon in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1371#issuecomment-842453555_

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1377 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
```
Timed out after 300.033s.
Service default/webtvzvcq-elb failed
```

/retest

**Pull request merged**
