### PR TITLE
refactor agentpool test definitions

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR refactors the agentpools unit test definitions to be more readable and self-contained by removing the shared test fixtures and instead using flexible builder functions to construct objects for each individual test. With this change, new tests should be easier to add in the future without having to copy-paste a full fixture to change a couple of fields like in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2751/files#diff-224617dc1cf5a3e1abbc71a49b79c42441871bef5a14e810921526267e6bde82.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
AFAICT the actual tests are exactly the same, the only difference is the syntax to define them.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

/area managedclusters

cc @willie-yao in case this is useful for #3003

### CODE REVIEW

**Review by jackfrancis — COMMENTED** [review]
@nojnhuh any preference between landing this before or after the taints fix?

**Comment by nojnhuh** [comment]
> @nojnhuh any preference between landing this before or after the taints fix?

Not necessarily, rebase shouldn't be bad either way.

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
