### PR TITLE
Set nonzero default control plane node count in templates

### LINKED ISSUE #4656: Set default ENV variables for clusterctl templates
/kind feature

**Describe the solution you'd like**
I'd like it when I initiate a `clusterctl generate cluster --flavor ##` that if some environment variables are not set or detected, that the templates default to safe/functional default values.

In particular, the `WORKER_MACHINE_COUNT` causes lots of problems when not set provisioning AKS clusters.  The replica value becomes `0` and you have to debug logs to find out why the cluster gets stuck in `provisioning` state.

Relevant logs for reference:

```
E0319 15:58:23.259912       1 controller.go:329] "Reconciler error" err="failed to retrieve Spec.ControlPlaneEndpoint from infrastructure provider for Cluster \"argoclustercaaph\" in namespace \"default\": field not found" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="default/argoclustercaaph" namespace="default" name="argoclustercaaph" reconcileID="2786bd78-2542-42b8-b247-c84c4fd8b5f5"
I0318 21:49:52.597331       1 azuremanagedmachinepool_controller.go:194] "AzureManagedControlPlane is not initialized" logger="controllers.AzureManagedMachinePoolReconciler.Reconcile" controller="azuremanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureManagedMachinePool" AzureManagedMachinePool="default/argoclustercaaph-pool0" namespace="default" name="argoclustercaaph-pool0" reconcileID="be8e3fc3-94e6-4f13-99c5-bf02a9310f56" namespace="default" name="argoclustercaaph-pool0" kind="AzureManagedMachinePool" x-ms-correlation-request-id="b429506e-1e69-4456-acd6-f20bb809aca3" ownerCluster="argoclustercaaph"
```

**Environment:**

- cluster-api-provider-azure version: 1.14.0
- Kubernetes version: (use `kubectl version`): 1.29.1
- OS (e.g. from `/etc/os-release`): Docker Desktop K8s / WSL

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- This PR adds defaults to the control plane count and worker count to all the templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4656 

**Special notes for your reviewer**:
- I have split the PR into commits for the ease of review.
- I have only addressed updating `WORKER_MACHINE_COUNT` and `CONTROL_PLANE_MACHINE_COUNT`. Other variables have not been defaulted for maintainability reason. 

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dtzar — APPROVED** [review]

**Comment by mboersma** [comment]
/retest

```
fatal: unable to access 'https://github.com/kubernetes-sigs/cluster-api-provider-azure.git/': Recv failure: Connection reset by peer
```

**Comment by jackfrancis** [comment]
@nawazkh after the optional E2E scenarios test runs, could you kindly squash commits and add more detail to commit message and PR title (like "ensure reference templates have default replica count values" or something...)

Thanks!

**Review by mboersma — APPROVED** [review]
/lgtm
/retitle Set nonzero default control plane node count in templates

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
