### PR TITLE
[release-1.10] Update CAPI to v1.4.7

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI references to use the new [v1.4.7 release](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.7).

Also updates cert-manager to v1.13.0 to keep that in sync with CAPI.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v1.4.7
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
> MachinePool.cluster.x-k8s.io "capz-e2e-9b7810-vmss-mp-0" is invalid:
   .spec.replicas: Invalid value: -52: should be a non-negative integer

what happened??

**Pull request merged**
