### PR TITLE
Add jackfrancis to reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: @jackfrancis has made significant [contributions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+jackfrancis+is%3Aclosed) to the project both as an author and as a reviewer, this PR adds him as a reviewer in OWNERs. Thank you for all your contributions so far @jackfrancis! 

/assign @nader-ziada @devigned @alexeldeib @shysank

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shysank** [comment]
+1

**Comment by jackfrancis** [comment]
Excited to lean even more into the capz project! Thanks especially to @CecileRobertMichon for all the hard work expended over the past years.

**Comment by mboersma** [comment]
+1

**Comment by jsturtevant** [comment]
+1

**Pull request merged**
