### PR TITLE
💚  Increase e2e control plane timeout

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**:  Seeing some occasional flakes where 3 control planes takes more than 10 minutes for all 3 to be ready, eg. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/893/pull-cluster-api-provider-azure-e2e/1297955254075133952 (from #893)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
I've seen the same thing at least a few times. 👍

**Comment by CecileRobertMichon** [comment]
```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:99
Expected an error to have occurred.  Got:
    <nil>: nil
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/kubernetes/networkpolicy/networkpolicy.go:89
```

sad... first time I see this one 

/retest

**Comment by CecileRobertMichon** [comment]
/hold

This is not fixing anything, just ran into the same flake

What's strange is that when looking at the job artifacts I see: 

```
status:
  conditions:
  - lastTransitionTime: "2020-08-25T00:12:06Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-08-25T00:07:10Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-25T00:05:01Z"
    status: "True"
    type: CertificatesAvailable
  - lastTransitionTime: "2020-08-25T00:12:06Z"
    status: "True"
    type: MachinesReady
  - lastTransitionTime: "2020-08-25T00:12:06Z"
    status: "True"
    type: Resized
  initialized: true
  observedGeneration: 1
  ready: true
  readyReplicas: 3
  replicas: 3
  selector: cluster.x-k8s.io/cluster-name=capz-e2e-p3ydpo,cluster.x-k8s.io/control-plane
  updatedReplicas: 3
```

yet the test complains that only 2 replicas are ready... It's possible the 3rd replica became ready right after the timeout (before artifacts were collected), looking.

**Comment by CecileRobertMichon** [comment]
Update: I do see one of the Machines in "provisioning" phase and without a nodeRef:

```
status:
  addresses:
  - address: 10.0.0.6
    type: InternalIP
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2020-08-25T00:12:04Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-08-25T00:10:13Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2020-08-25T00:16:02Z"
    status: "True"
    type: InfrastructureReady
  infrastructureReady: true
  lastUpdated: "2020-08-25T00:10:13Z"
  observedGeneration: 2
  phase: Provisioning
```

So it's possible this is one of the cases where having kubeadm join actually failed.

**Comment by nader-ziada** [comment]
I don't think we need this anymore

**Pull request closed without merging**
