### PR TITLE
Add more e2e regions to spread quota usage

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Add a few more regions to the list of test regions so we can spread the load a bit as we have more tests running now with different release branch tests + all periodic jobs. I verified that the test subscription has quota in the added regions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
In #1690 I removed `canadacentral` and `westus` because they didn't offer the `Standard_NV6` GPU SKU that e2e tests use by default. I think that's still the case, but things are complicated by the fact that this SKU is deprecated and doesn't show up in `az vm list-skus` even in regions where it is still supported currently.

We could consider having a separate random region function for just the GPU test, although that sounds clunky. We need to move to another, supported SKU before summer of 2022, but getting quota is difficult.

**Comment by CecileRobertMichon** [comment]
/retest

no region related issue

**Comment by CecileRobertMichon** [comment]
> We could consider having a separate random region function for just the GPU test, although that sounds clunky. We need to move to another, supported SKU before summer of 2022, but getting quota is difficult.

@mboersma the GPU test has actually been failing https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-main, not sure if it's a SKU issue though

**Comment by mboersma** [comment]
> the GPU test has actually been failing

It doesn't appear to be a SKU issue in testgrid, because the GPU nodes have boot logs, etc. I don't see the problem yet, but I'll dig into it.

For this PR, I'm pretty sure adding those two regions guarantees failure for the GPU tests if they're selected. We could add separate logic for finding a random GPU-enabled region, but really we need to use a new GPU SKU and ensure quota for it. This will probably introduce a different set of compatible/incompatible regions, but IIRC the new recommended type is more widely available.

**Comment by mboersma** [comment]
@CecileRobertMichon I'm still looking at the GPU failure and thinking about how to transition us to [`Standard_NV12s_v3`](https://docs.microsoft.com/en-us/azure/virtual-machines/nv-series-migration-guide#nvsv3-series). Hopefully we can arrive at a configuration that includes more regions in the end.

**Pull request closed without merging**
