### PR TITLE
bump cluster api version to 0.3.7-alpha.0 

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- bump cluster api version to 0.3.7-alpha.0  to enable development of features that require a newer cluster-api

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update cluster-api dependency to 0.3.7-alpha.0
```

### CODE REVIEW

**Comment by mboersma** [comment]
Thank you! I have an identical local commit, trying to get new test helper code from CAPI.

**Comment by devigned** [comment]
I also have identical commit in a PR I'm working on. Let's get this pulled in 👍

**Comment by cpanato** [comment]
A late lgtm
/lgtm

:)

**Pull request merged**
