### PR TITLE
Build Windows k8s artifacts if TEST_WINDOWS or WINDOWS is set

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: `ci-entrypoint.sh` uses `TEST_WINDOWS` to determine Windows nodes should be built, while `ci-conformance.sh` uses `WINDOWS`. As test-infra jobs use both in different places, the quickest fix for now is to allow both. Eventually, we may want to consider converging to one or the other and refactoring all jobs for consistency.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by marosset** [comment]
Should we update https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7425764f4e42df05712ed300bd0123eece3aa016/docs/book/src/developers/development.md?plain=1#L537-L546 too?

**Comment by CecileRobertMichon** [comment]
@marosset I don't think we need to update the doc since we already have https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7425764f4e42df05712ed300bd0123eece3aa016/docs/book/src/developers/development.md?plain=1#L523 for conformance and https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7425764f4e42df05712ed300bd0123eece3aa016/docs/book/src/developers/development.md?plain=1#L567 for ci-entrypoint.sh documented

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Pull request merged**
