### PR TITLE
[release-1.2] Fetch calico manifests from release artifacts

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: cherry-pick #2149 to fix `make verify` on release-1.2.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@mboersma @CecileRobertMichon this one looks good for final merge

**Review by mboersma — APPROVED** [review]
/approve

**Comment by mboersma** [comment]
@CecileRobertMichon I wasn't a maintainer when the release-1.2 branch was cut, so I think this needs approval from you.

**Pull request merged**
