### PR TITLE
chore(golangci-lint): add ifshort linter

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

/kind cleanup

**What this PR does / why we need it**:
This PR adds `ifshort` linter 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Reference umbrella issue: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1982

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
Looks like this has the unparam commit from https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1985

**Comment by sonasingh46** [comment]
@jsturtevant -- Yes. I did it intentionally so that once the PR is merged, it is easy for me to rebase(assuming conflicts can happen). 
These lint PRs should be merged in order. I thought this will save some effort.

**Pull request merged**
