### PR TITLE
[release-1.1] e2e: Use the intersection of images available for windows and ubuntu to determine latest patch

### PR DESCRIPTION
**Pull request by jackfrancis**
This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1995

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@jackfrancis do we still want to hold this? Even if it isn't enough by itself and we also need #1879 to fully fix release-1.1 for presubmit jobs, we might still want to merge it to prevent running into the bug it fixes when image publishing is in progress.

**Comment by jackfrancis** [comment]
> @jackfrancis do we still want to hold this? Even if it isn't enough by itself and we also need #1879 to fully fix release-1.1 for presubmit jobs, we might still want to merge it to prevent running into the bug it fixes when image publishing is in progress.

I held it because I didn't fully understand what the ramifications of merging it into `release-1.1` would be, after losing confidence that doing so would actually fix the blocked upstream k/k PRs (which we later determined will be fixed by #1879).

If we're confident this is a useful cherry-pick let's remove the hold!

**Comment by CecileRobertMichon** [comment]
/hold cancel

This + https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2052 should help fix upstream tests on release-1.1

**Pull request merged**
