### PR TITLE
ci: remove upstream-windows-serial-slow configs

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR removes "Serial" + "Slow" Windows conformance configs, now that we no longer have a native test to gather that coverage. Ref:

- https://github.com/kubernetes/test-infra/pull/33197

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @jsturtevant @marosset

**Comment by jsturtevant** [comment]
did you want to clean up files like https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/data/kubetest/upstream-windows-serial-slow.yaml?

**Comment by jackfrancis** [comment]
> did you want to clean up files like https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/data/kubetest/upstream-windows-serial-slow.yaml?

lol I thought I had! done now

**Review by jsturtevant — COMMENTED** [review]
/lgtm

**Pull request merged**
