### PR TITLE
update error statement to not show stacktrace in resource status

### LINKED ISSUE #1031: stacktrace when running kubectl  describe azurecluster
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Had a typo in the value of AZURE_ENVIRONMENT when trying to deploy a workload cluster
- the creation of the workload cluster failed, but the error message was not helpful
- when running `kubectl describe azurecluster` I see a stack trace

```
....
Events:
  Type     Reason                    Age                     From                     Message
  ----     ------                    ----                    ----                     -------
  Normal   OwnerRefNotSet            5m22s                   azurecluster-reconciler  Cluster Controller has not yet set OwnerRef
  Warning  CreateClusterScopeFailed  2m37s (x16 over 5m20s)  azurecluster-reconciler  failed to create scope: autorest/azure: There is no cloud environment matching the name "AZUREPUBLIC"
failed to configure azure settings and credentials from environment
sigs.k8s.io/cluster-api-provider-azure/cloud/scope.NewClusterScope
  /workspace/cloud/scope/cluster.go:66
sigs.k8s.io/cluster-api-provider-azure/controllers.(*AzureClusterReconciler).Reconcile
  /workspace/controllers/azurecluster_controller.go:136
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:255
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:231
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:210
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
  /go/pkg/mod/k8s.io/apimachinery@v0.17.12/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
  /go/pkg/mod/k8s.io/apimachinery@v0.17.12/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
  /go/pkg/mod/k8s.io/apimachinery@v0.17.12/pkg/util/wait/wait.go:88
runtime.goexit
           /usr/local/go/src/runtime/asm_amd64.s:1357
  Warning  Error creating the cluster scope  2m36s (x16 over 5m20s)  azuremachine-reconciler  failed to configure azure settings and credentials from environment: autorest/azure: There is no cloud environment matching the name "AZUREPUBLIC"
```

**What did you expect to happen:**
- would be better to see a condition on the cluster to indicate the initialization failed somehow

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: master as of Nov112020
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
- update error statement from `Wrapf` to `Errorf` so stacktrace is not shown in the `azurecluster` status when using `kubectl get -o yaml`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1031 

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
