### PR TITLE
Tiltfile decodes Azure SSH key from base 64 encoding

### LINKED ISSUE #1572: Tiltfile should use AZURE_SSH_PUBLIC_KEY_B64 to deduce AZURE_SSH_PUBLIC_KEY
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Tiltfile gets the value of `ssh_pub_key_B64` from env/file https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Tiltfile#L223. It should decode that value to set `ssh_pub_key` instead of trying to get the value again. For this we can use the `base64_decode` function to decode the `ssh_pub_key_B64` and use it to set `AZURE_SSH_PUBLIC_KEY`.

/good-first-issue
/help

**What did you expect to happen:** 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**: Tiltfile uses 'AZURE_SSH_PUBLIC_KEY_B64' to decode 'AZURE_SSH_PUBLIC_KEY' instead of getting the value again.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1572 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Review by mboersma — APPROVED** [review]
/lgtm

We don't seem to reference `AZURE_SSH_PUBLIC_KEY` in docs, only the `_B64` version. I guess it's possible that someone had set these two variables to different keys and was inadvertently relying on that behavior, but...nah--that seems very unlikely.

**Comment by nader-ziada** [comment]
tried it with both `AZURE_SSH_PUBLIC_KEY ` and `AZURE_SSH_PUBLIC_KEY_B64 ` and works fine in both cases

/lgtm
/approve

**Pull request merged**
