### PR TITLE
Remove unused multi-tenancy creds

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: Noticed these leftover creds are no longer used anywhere and were leftover from an old test that got removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @nojnhuh @mboersma

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
> cannot checkout release 1.10

whoops, thank you @mboersma!

**Pull request merged**
