### PR TITLE
Install cloud provider azure Helm chart with CAAPH

### LINKED ISSUE #3736: Use CAAPH to install Helm charts in e2e tests
/kind feature

**Describe the solution you'd like**

Cluster API v1.5 brings support for installing add-on providers using clusterctl. This allows us to use CAAPH in the e2e tests to install cloud-provider-azure, calico, and azuredisk-csi-driver rather than a manual Helm install.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**: Install cloud provider azure Helm chart with CAAPH in e2e tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3736

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Install cloud provider azure Helm chart with CAAPH
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@Jont828 I think we want to install with a label assignment during E2E runtime rather than adding the label in the template itself. Like we ended up doing here for azuredisk-csi:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4334/files#diff-1131bb4107662928d2a952d842948b3d7ae633a00339807f164ac7446ad807c5

Basically some of these templates may be used by downstream cloud-provider-azure tests where they want to install their own opinionated installation of cloud-provider-azure (for example from bits built at runtime against a cloud-provider-azure dev branch).

cc @CecileRobertMichon

**Comment by Jont828** [comment]
@jackfrancis I already set up something similar since it's configured based on an environment variable

**Comment by CecileRobertMichon** [comment]
/close

will open a new PR when ready

**Pull request closed without merging**
