### PR TITLE
Fix an AKS e2e test expectation

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Fixes an arity mismatch in `WaitForControlPlaneMachinesToExist` in the AKS flavor tests.

This causes this obfuscating error in e2e logs:

```
    [91mTimed out after 1200.000s.
    Error: Unexpected non-nil/non-zero extra argument at index 1:
    	<*errors.errorString>: &errors.errorString{s:"system machine pools not ready"}[0m
```

I'm not sure why this doesn't also break when the cluster succeeds, but perhaps Ginkgo's implementation of `Equal` has a reasoning for that.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
The test failed due to timeout, but the output shows this change worked to fix the extraneous error:

```
[0mWorkload cluster creation[0m [90mCreating an AKS cluster[0m 
  [1mwith a single control plane node and 1 node[0m
  [37m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:435[0m

INFO: "with a single control plane node and 1 node" started at Fri, 17 Sep 2021 17:28:53 UTC on Ginkgo node 1 of 3
[1mSTEP[0m: Creating namespace "capz-e2e-6vdvpk" for hosting the cluster
Sep 17 17:28:53.890: INFO: starting to create namespace for hosting the "capz-e2e-6vdvpk" test spec
2021/09/17 17:28:53 failed trying to get namespace (capz-e2e-6vdvpk):namespaces "capz-e2e-6vdvpk" not found
INFO: Creating namespace capz-e2e-6vdvpk
INFO: Creating event watcher for namespace "capz-e2e-6vdvpk"
INFO: Cluster name is capz-e2e-6vdvpk-aks
INFO: Creating the workload cluster with name "capz-e2e-6vdvpk-aks" using the "aks-multi-tenancy" template (Kubernetes v1.19.13, 1 control-plane machines, 1 worker machines)
INFO: Getting the cluster template yaml
INFO: clusterctl config cluster capz-e2e-6vdvpk-aks --infrastructure (default) --kubernetes-version v1.19.13 --control-plane-machine-count 1 --worker-machine-count 1 --flavor aks-multi-tenancy
INFO: Applying the cluster template yaml to the cluster
cluster.cluster.x-k8s.io/capz-e2e-6vdvpk-aks created
azuremanagedcontrolplane.infrastructure.cluster.x-k8s.io/capz-e2e-6vdvpk-aks created
azuremanagedcluster.infrastructure.cluster.x-k8s.io/capz-e2e-6vdvpk-aks created
machinepool.cluster.x-k8s.io/agentpool0 created
azuremanagedmachinepool.infrastructure.cluster.x-k8s.io/agentpool0 created
machinepool.cluster.x-k8s.io/agentpool1 created
azuremanagedmachinepool.infrastructure.cluster.x-k8s.io/agentpool1 created
azureclusteridentity.infrastructure.cluster.x-k8s.io/cluster-identity created

INFO: Waiting for the cluster infrastructure to be provisioned
[1mSTEP[0m: Waiting for cluster to enter the provisioned phase
INFO: Waiting for control plane to be initialized
Sep 17 17:32:26.052: INFO: Waiting for the first control plane machine managed by capz-e2e-6vdvpk/capz-e2e-6vdvpk-aks to be provisioned
[1mSTEP[0m: Waiting for atleast one control plane node to exist
Sep 17 17:32:26.063: INFO: System machine pools not ready
Sep 17 17:32:36.074: INFO: System machine pools not ready
Sep 17 17:32:46.083: INFO: System machine pools not ready
Sep 17 17:32:56.092: INFO: System machine pools not ready
Sep 17 17:33:06.102: INFO: System machine pools not ready
Sep 17 17:33:16.111: INFO: System machine pools not ready
Sep 17 17:33:26.121: INFO: System machine pools not ready
Sep 17 17:33:36.130: INFO: System machine pools not ready
Sep 17 17:33:46.139: INFO: System machine pools not ready
Sep 17 17:33:56.150: INFO: System machine pools not ready
Sep 17 17:34:06.159: INFO: System machine pools not ready
Sep 17 17:34:16.169: INFO: System machine pools not ready
Sep 17 17:34:26.178: INFO: System machine pools not ready
Sep 17 17:34:36.188: INFO: System machine pools not ready
Sep 17 17:34:46.197: INFO: System machine pools not ready
Sep 17 17:34:56.207: INFO: System machine pools not ready
Sep 17 17:35:06.216: INFO: System machine pools not ready
Sep 17 17:35:16.227: INFO: System machine pools not ready
Sep 17 17:35:26.237: INFO: System machine pools not ready
Sep 17 17:35:36.247: INFO: System machine pools not ready
Sep 17 17:35:46.255: INFO: System machine pools not ready
Sep 17 17:35:56.266: INFO: System machine pools not ready
Sep 17 17:36:06.276: INFO: System machine pools not ready
Sep 17 17:36:16.286: INFO: System machine pools not ready
Sep 17 17:36:26.296: INFO: System machine pools not ready
Sep 17 17:36:36.307: INFO: System machine pools not ready
Sep 17 17:36:46.316: INFO: System machine pools not ready
Sep 17 17:36:56.326: INFO: System machine pools not ready
Sep 17 17:37:06.336: INFO: System machine pools not ready
Sep 17 17:37:16.345: INFO: System machine pools not ready
Sep 17 17:37:26.355: INFO: System machine pools not ready
Sep 17 17:37:36.364: INFO: System machine pools not ready
Sep 17 17:37:46.374: INFO: System machine pools not ready
Sep 17 17:37:56.384: INFO: System machine pools not ready
Sep 17 17:38:06.394: INFO: System machine pools not ready
Sep 17 17:38:16.403: INFO: System machine pools not ready
Sep 17 17:38:26.412: INFO: System machine pools not ready
Sep 17 17:38:36.422: INFO: System machine pools not ready
Sep 17 17:38:46.432: INFO: System machine pools not ready
Sep 17 17:38:56.444: INFO: System machine pools not ready
Sep 17 17:39:06.457: INFO: System machine pools not ready
Sep 17 17:39:16.469: INFO: System machine pools not ready
Sep 17 17:39:26.480: INFO: System machine pools not ready
Sep 17 17:39:36.491: INFO: System machine pools not ready
Sep 17 17:39:46.501: INFO: System machine pools not ready
Sep 17 17:39:56.511: INFO: System machine pools not ready
Sep 17 17:40:06.522: INFO: System machine pools not ready
Sep 17 17:40:16.533: INFO: System machine pools not ready
Sep 17 17:40:26.542: INFO: System machine pools not ready
Sep 17 17:40:36.553: INFO: System machine pools not ready
Sep 17 17:40:46.564: INFO: System machine pools not ready
Sep 17 17:40:56.574: INFO: System machine pools not ready
Sep 17 17:41:06.584: INFO: System machine pools not ready
Sep 17 17:41:16.594: INFO: System machine pools not ready
Sep 17 17:41:26.604: INFO: System machine pools not ready
Sep 17 17:41:36.614: INFO: System machine pools not ready
Sep 17 17:41:46.622: INFO: System machine pools not ready
Sep 17 17:41:56.633: INFO: System machine pools not ready
Sep 17 17:42:06.642: INFO: System machine pools not ready
Sep 17 17:42:16.651: INFO: System machine pools not ready
Sep 17 17:42:26.661: INFO: System machine pools not ready
Sep 17 17:42:36.673: INFO: System machine pools not ready
Sep 17 17:42:46.684: INFO: System machine pools not ready
Sep 17 17:42:56.694: INFO: System machine pools not ready
Sep 17 17:43:06.705: INFO: System machine pools not ready
Sep 17 17:43:16.714: INFO: System machine pools not ready
Sep 17 17:43:26.723: INFO: System machine pools not ready
Sep 17 17:43:36.734: INFO: System machine pools not ready
Sep 17 17:43:46.743: INFO: System machine pools not ready
Sep 17 17:43:56.752: INFO: System machine pools not ready
Sep 17 17:44:06.760: INFO: System machine pools not ready
Sep 17 17:44:16.771: INFO: System machine pools not ready
Sep 17 17:44:26.780: INFO: System machine pools not ready
Sep 17 17:44:36.788: INFO: System machine pools not ready
Sep 17 17:44:46.836: INFO: System machine pools not ready
Sep 17 17:44:56.891: INFO: System machine pools not ready
Sep 17 17:45:06.950: INFO: System machine pools not ready
Sep 17 17:45:17.005: INFO: System machine pools not ready
Sep 17 17:45:27.069: INFO: System machine pools not ready
Sep 17 17:45:37.128: INFO: System machine pools not ready
Sep 17 17:45:47.193: INFO: System machine pools not ready
Sep 17 17:45:57.246: INFO: System machine pools not ready
Sep 17 17:46:07.295: INFO: System machine pools not ready
Sep 17 17:46:17.371: INFO: System machine pools not ready
Sep 17 17:46:27.441: INFO: System machine pools not ready
Sep 17 17:46:37.513: INFO: System machine pools not ready
Sep 17 17:46:47.593: INFO: System machine pools not ready
Sep 17 17:46:57.670: INFO: System machine pools not ready
Sep 17 17:47:07.732: INFO: System machine pools not ready
Sep 17 17:47:17.798: INFO: System machine pools not ready
Sep 17 17:47:27.861: INFO: System machine pools not ready
Sep 17 17:47:37.935: INFO: System machine pools not ready
Sep 17 17:47:48.010: INFO: System machine pools not ready
Sep 17 17:47:58.062: INFO: System machine pools not ready
Sep 17 17:48:08.127: INFO: System machine pools not ready
Sep 17 17:48:18.190: INFO: System machine pools not ready
Sep 17 17:48:28.275: INFO: System machine pools not ready
Sep 17 17:48:38.342: INFO: System machine pools not ready
Sep 17 17:48:48.405: INFO: System machine pools not ready
Sep 17 17:48:58.468: INFO: System machine pools not ready
Sep 17 17:49:08.544: INFO: System machine pools not ready
Sep 17 17:49:18.604: INFO: System machine pools not ready
Sep 17 17:49:28.664: INFO: System machine pools not ready
Sep 17 17:49:38.718: INFO: System machine pools not ready
Sep 17 17:49:48.788: INFO: System machine pools not ready
Sep 17 17:49:58.844: INFO: System machine pools not ready
Sep 17 17:50:08.901: INFO: System machine pools not ready
Sep 17 17:50:18.977: INFO: System machine pools not ready
Sep 17 17:50:29.023: INFO: System machine pools not ready
Sep 17 17:50:39.097: INFO: System machine pools not ready
Sep 17 17:50:49.175: INFO: System machine pools not ready
Sep 17 17:50:59.238: INFO: System machine pools not ready
Sep 17 17:51:09.304: INFO: System machine pools not ready
Sep 17 17:51:19.365: INFO: System machine pools not ready
Sep 17 17:51:29.417: INFO: System machine pools not ready
Sep 17 17:51:39.486: INFO: System machine pools not ready
Sep 17 17:51:49.547: INFO: System machine pools not ready
Sep 17 17:51:59.610: INFO: System machine pools not ready
Sep 17 17:52:09.663: INFO: System machine pools not ready
Sep 17 17:52:19.736: INFO: System machine pools not ready
[1mSTEP[0m: Dumping logs from the "capz-e2e-6vdvpk-aks" workload cluster
[1mSTEP[0m: Dumping workload cluster capz-e2e-6vdvpk/capz-e2e-6vdvpk-aks logs
[1mSTEP[0m: Dumping workload cluster capz-e2e-6vdvpk/capz-e2e-6vdvpk-aks kube-system pod logs
[1mSTEP[0m: Fetching kube-system pod logs took 1.017828599s
[1mSTEP[0m: Creating log watcher for controller kube-system/calico-node-dljpv, container calico-node
[1mSTEP[0m: Creating log watcher for controller kube-system/calico-typha-horizontal-autoscaler-599c7bb664-v97pt, container autoscaler
[1mSTEP[0m: Creating log watcher for controller kube-system/kube-proxy-gfwcb, container kube-proxy
[1mSTEP[0m: Dumping workload cluster capz-e2e-6vdvpk/capz-e2e-6vdvpk-aks Azure activity log
[1mSTEP[0m: Creating log watcher for controller kube-system/coredns-84d976c568-56q6t, container coredns
[1mSTEP[0m: Creating log watcher for controller kube-system/coredns-84d976c568-79t2d, container coredns
[1mSTEP[0m: Creating log watcher for controller kube-system/calico-node-6kv92, container calico-node
[1mSTEP[0m: Creating log watcher for controller kube-system/kube-proxy-mgm8x, container kube-proxy
[1mSTEP[0m: Creating log watcher for controller kube-system/coredns-autoscaler-6699988865-cdsqq, container autoscaler
[1mSTEP[0m: Creating log watcher for controller kube-system/tunnelfront-656479dbd-7v52s, container tunnel-front
[1mSTEP[0m: Creating log watcher for controller kube-system/metrics-server-97958786-72zmm, container metrics-server
[1mSTEP[0m: Creating log watcher for controller kube-system/calico-typha-deployment-76cb9744d8-g9sdv, container calico-typha
[1mSTEP[0m: Fetching activity logs took 753.731037ms
[1mSTEP[0m: Dumping all the Cluster API resources in the "capz-e2e-6vdvpk" namespace
[1mSTEP[0m: Deleting all clusters in the capz-e2e-6vdvpk namespace
[1mSTEP[0m: Deleting cluster capz-e2e-6vdvpk-aks
INFO: Waiting for the Cluster capz-e2e-6vdvpk/capz-e2e-6vdvpk-aks to be deleted
[1mSTEP[0m: Waiting for cluster capz-e2e-6vdvpk-aks to be deleted
[1mSTEP[0m: Deleting namespace used for hosting the "create-workload-cluster" test spec
INFO: Deleting namespace capz-e2e-6vdvpk
[1mSTEP[0m: Checking if any resources are left over in Azure for spec "create-workload-cluster"
[1mSTEP[0m: Redacting sensitive information from logs
INFO: "with a single control plane node and 1 node" ran for 29m17s on Ginkgo node 1 of 3


[91m[1m• Failure [1756.974 seconds][0m
Workload cluster creation
[90m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:41[0m
  Creating an AKS cluster
  [90m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:434[0m
    [91m[1mwith a single control plane node and 1 node [It][0m
    [90m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:435[0m

    [91mTimed out after 1200.000s.
    Expected
        <bool>: false
    to equal
        <bool>: true[0m

    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/aks.go:217

    [91mFull Stack Trace[0m
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.WaitForControlPlaneMachinesToExist(0x2520dc0, 0xc0000560e0, 0x7f7b50206840, 0xc000314460, 0x7f7b50603d28, 0xc000314460, 0xc0009d2480, 0xc000c05b00, 0x13, 0xc001eb0990, ...)
```

Should I move the `System machine pools not ready` log message outside the loop, so it only shows up once when things fail?

**Comment by CecileRobertMichon** [comment]
> Should I move the System machine pools not ready log message outside the loop, so it only shows up once when things fail?

+1

**Pull request merged**
