### PR TITLE
Add godot linter

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Adds the [`godot`](https://github.com/tetafro/godot) linter to the golangci-lint config to ensure that Go doc comments end with periods. This linter is also [enabled in CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/.golangci.yml#L14).

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

This is a pet peeve of mine, but feel free to close it if this isn't considered productive. Sorry it's so big--I can split it up if necessary.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
related to #1443

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

will leave it up for a bit in case anyone has objections to enabling the linter

**Review by devigned — APPROVED** [review]
/lgtm

Pretty sure this made @CecileRobertMichon's day.

**Pull request merged**
