### PR TITLE
Change vm extension test to use resource group name correctly

### LINKED ISSUE #2696: capz-periodic-e2e-full-main CI job failing
/kind bug

**What steps did you take and what happened:**

In testgrid, the [capz-periodic-e2e-full-main](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-main) job began failing after the [custom VM extensions](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2631) PR got merged. Here is [the log](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1576982668388601856) that seems to implicate new custom VM code somehow:

```
capz-e2e: Workload cluster creation Creating clusters using clusterclass [OPTIONAL] with a single control plane node, one linux worker node, and one windows worker node expand_less | 21m9s
-- | --
{ Failure /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:670 Unexpected error:     <autorest.DetailedError>: {         Original: <*azure.RequestError \| 0xc000f6a6c0>{             DetailedError: {                 Original: nil,                 PackageType: "",                 Method: "",                 StatusCode: <int>404,                 Message: "",                 ServiceError: nil,                 Response: {                     Status: "404 Not Found",                     StatusCode: 404,                     Proto: "HTTP/2.0",                     ProtoMajor: 2,                     ProtoMinor: 0,                     Header: {                         "X-Ms-Failure-Cause": ["gateway"],                         "X-Ms-Correlation-Request-Id": [                             "fa92e7e4-30c2-4a30-9670-2aacda76b2e8",                         ],                         "Date": [                             "Mon, 03 Oct 2022 17:27:42 GMT",                         ],                         "Content-Length": ["110"],                         "Content-Type": [                             "application/json; charset=utf-8",                         ],                         "Expires": ["-1"],                         "X-Ms-Request-Id": [                             "fa92e7e4-30c2-4a30-9670-2aacda76b2e8",                         ],                         "X-Ms-Routing-Request-Id": [                             "CENTRALUS:20221003T172742Z:fa92e7e4-30c2-4a30-9670-2aacda76b2e8",                         ],                         "Strict-Transport-Security": [                             "max-age=31536000; includeSubDomains",                         ],                         "X-Content-Type-Options": ["nosniff"],                         "Cache-Control": ["no-cache"],                         "Pragma": ["no-cache"],                     },                     Body: <io.nopCloser>{                         Reader: <*bytes.Buffer \| 0xc001d539e0>{                             buf: "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'capz-e2e-2tk088-cc' could not be found.\"}}",                             off: 0,                             lastRead: 0,                         },                     },                     ContentLength: 110,                     TransferEncoding: nil,                     Close: false,                     Uncompressed: false,                     Trailer: nil,                     Request: {                         Method: "GET",                         URL: {                             Scheme: "https",                             Opaque: "",                             User: nil,                             Host: "management.azure.com",                             Path: "/subscriptions/===REDACTED===/resourceGroups/capz-e2e-2tk088-cc/providers/Microsoft.Compute/virtualMachines",                             RawPath: "",                             ForceQuery: false,                             RawQuery: "api-version=2021-11-01",                             Fragment: "",                             RawFragment: "",                         },                         Proto: "",                         ProtoMajor: 0,                         ProtoMinor: 0,                         Header: {                             "User-Agent": [                                 "Go/go1.18.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v63.4.0 compute/2021-11-01",                             ],                             "Authorization": [                                 "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzA5N2Y4OWEwLTkyODYtNDNkMi05YTFhLTA4ZjFkNDliMWFmOC8iLCJpYXQiOjE2NjQ4MTc3NjIsIm5iZiI6MTY2NDgxNzc2MiwiZXhwIjoxNjY0ODIxNjYyLCJhaW8iOiJFMlpnWVBnWFdQZzQ1RTFRc1lTL2gzNmR3TU1JQUE9PSIsImFwcGlkIjoi===REDACTED===IiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvM...  Gomega truncated this representation as it exceeds 'format.MaxLength'. Consider having the object provide a custom 'GomegaStringer' representation or adjust the parameters in Gomega's 'format' package.  Learn more here: https://onsi.github.io/gomega/#adjusting-output      compute.VirtualMachinesClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'capz-e2e-2tk088-cc' could not be found." occurred /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_vmextensions.go:97}
```

**What did you expect to happen:**

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This PR corrects an issue in the vm extension E2E test where the clusterName was being used as the resource group name to list VMs and VM extensions from Azure. The correct way is to get the resource group name from the ProviderID.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2696

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by willie-yao** [comment]
Putting this on hold for now while I figure out the resource group name issue being discussed in #2696

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
