### PR TITLE
bump google.golang.org/grpc to v1.58.3

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates the google.golang.org/grpc package to v1.58.3 to address a security vulnerability identified by dependabot. This was just identified in the last few hours and has begun to fail CAPZ PRs in the "Dependency Review" action.

> ### Impact
> In affected releases of gRPC-Go, it is possible for an attacker to send HTTP/2 requests, cancel them, and send subsequent requests, which is valid by the HTTP/2 protocol, but would cause the gRPC-Go server to launch more concurrent method handlers than the configured maximum stream limit.
> ### Patches
> This vulnerability was addressed by #6703 and has been included in patch releases: 1.56.3, 1.57.1, 1.58.3. It is also included in the latest release, 1.59.0.

**Which issue(s) this PR fixes**:

Fixes several security [alerts](https://github.com/kubernetes-sigs/cluster-api-provider-azure/security/dependabot).

**Special notes for your reviewer**:

Dependabot failed to create a PR for this, so I did. We can look at the Security Alert logs to find out why.

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

@mboersma Do all of the hack/tools/go.mod changes need to come with this? Just curious.

**Comment by nojnhuh** [comment]
> /lgtm /approve
> 
> @mboersma Do all of the hack/tools/go.mod changes need to come with this? Just curious.

Ah, I see the security alert also flags hack/tools

**Comment by mboersma** [comment]
> #4184 failed to apply on top of branch "release-1.11":

I will make separate PRs for the release branches to fix this.

**Pull request merged**
