### PR TITLE
Add version pin and registry values to calico Helm install with CAAPH

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Fixes an oversight in #3971 where we lose the version pin and registry information in values.yaml.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by mboersma** [comment]
/hold
(Pending squash of commits.)

/test pull-cluster-api-provider-azure-e2e-optional

**Comment by Jont828** [comment]
@CecileRobertMichon @mboersma I got the tests passing and squashed. If it passes on the squashed branch, I think I'm ready on my end!

**Comment by CecileRobertMichon** [comment]
/retest

optional test failed

@Jont828 please remove the hold label if/when this is ready!

**Comment by Jont828** [comment]
I think we're ready pending that test. I can't tell if that test is still a flake issue, though.

**Pull request merged**
