### PR TITLE
🏃 Update capi to v0.3.2

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Update Cluster API to v0.3.2
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@vincepri @chuckha E2E is failing after moving to the new release with error 

```
admission webhook "validation.machine.cluster.x-k8s.io" denied the request: Machine.cluster.x-k8s.io "capz-vhbqic-controlplane-0" is invalid: spec.version: Invalid value: "": must be a valid semantic version
```

which seems related to https://github.com/kubernetes-sigs/cluster-api/pull/2674 
even though we are using the capi framework default K8s version from the default config: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0dfe4ebd993fd97bf2a49c7b83339ff250dbadc9/test/e2e/resource_generators.go#L193
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0dfe4ebd993fd97bf2a49c7b83339ff250dbadc9/test/e2e/resource_generators.go#L218
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0dfe4ebd993fd97bf2a49c7b83339ff250dbadc9/test/e2e/resource_generators.go#L409

Any ideas?

**Comment by detiber** [comment]
@CecileRobertMichon looking at https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/config.go#L283-L295 and https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/config_constants.go#L19-L62, it looks like the default configuration does not set the KubernetesVersion by default unless you call the .Defaults() method on the config resource (which doesn't appear to be done when calling `framework.DefaultConfig()`.

**Comment by cpanato** [comment]
we have this PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/457 which one we will move forward?

**Pull request merged**
