### PR TITLE
Test if GPU resources are available before scheduling e2e job

### LINKED ISSUE #1354: GPU test is failing consistently on release-0.4 branch
/kind failing-test

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-full-release-0-4

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:314
Timed out after 300.046s.
Job default/cuda-vector-add failed
```

It might be an issue with the job, or with the GPU nodes themselves. #1344 recently updated the job image in the main branch, backporting the change might be enough to fix it (or it might be a bigger issue). Note that the GPU template is different in release-0.4 as it does not use the nvidia operator.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Hopefully fixes (one of) the problems causing the GPU-enabled cluster tests to fail in [testgrid e2e](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-full-release-0-4) for the release-0.4 branch, by waiting for the GPU resources to be exposed before running the cuda-vector Job.

**Which issue(s) this PR fixes**:

Fixes #1354

**Special notes for your reviewer**:

See #1693

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@mboersma we might also want to backport https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1571 to release-0.4

**Comment by mboersma** [comment]
/test pull-cluster-api-provider-azure-e2e-full-release-0-4

I rebased this off #1705. 🤞🏻

**Comment by mboersma** [comment]
/retest

Last run failed in the `Creating a cluster using a different SP identity` spec, which this change should not have affected.

**Comment by CecileRobertMichon** [comment]
@mboersma it passed 👏  🏅 

/lgtm
/approve

**Pull request merged**
