### PR TITLE
add 1.14 release to metadata

### PR DESCRIPTION
**Pull request by dtzar**
Signed-off-by: David Tesar <david.tesar@microsoft.com>

**Release note**:

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
```
ERROR: 2 dead links found!
[✖] https://github.com/Azure/azure-sdk-for-go/compare/sdk/resourcemanager/compute/armcompute/v5/v5.4.0...sdk/resourcemanager/compute/armcompute/v5/v5.5.0 → Status: 404
[✖] https://github.com/Azure/azure-sdk-for-go/compare/sdk/resourcemanager/containerservice/armcontainerservice/v4/v4.6.0...sdk/resourcemanager/containerservice/armcontainerservice/v4/v4.7.0 → Status: 404
```
https://github.com/Azure/azure-sdk-for-go/compare/sdk/resourcemanager/compute/armcompute/v5/v5.4.0...sdk/resourcemanager/compute/armcompute/v5/v5.5.0
https://github.com/Azure/azure-sdk-for-go/compare/sdk/resourcemanager/containerservice/armcontainerservice/v4/v4.6.0...sdk/resourcemanager/containerservice/armcontainerservice/v4/v4.7.0

Those links seem to work for me... Maybe a transient error?

**Comment by dtzar** [comment]
@mboersma fixed

**Review by mboersma — APPROVED** [review]
/lgtm
/assign @Jont828 @nojnhuh

**Comment by willie-yao** [comment]
> Those links seem to work for me... Maybe a transient error?

I think that the latest update to the kubernetes release tool should fix this. I can bump it in a separate PR.

**Pull request merged**
