### PR TITLE
[release-1.0] Fix outbound lb conversion for v1alpha3 clusters

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Backports #2176 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix outbound lb conversion for v1alpha3 clusters
```

### CODE REVIEW

**Comment by shysank** [comment]
The test failures are because I set the base branch as main by mistake initially.

**Comment by shysank** [comment]
cc @CecileRobertMichon

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by shysank** [comment]
closing this because of test failures preventing from merge.

**Pull request closed without merging**
