### PR TITLE
dump resources on delete timeout

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This PR takes advantage of https://github.com/kubernetes-sigs/cluster-api/pull/10961 new in CAPI 1.8 to dump resources when a delete operation times out like we've been seeing with AKS clusters recently.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
The most recent e2e test failure shows this is working as expected.

/retitle dump resources on delete timeout

**Review by willie-yao — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
