### PR TITLE
Fixing Windows machine-pools in cluster-template-custom-builds-machine-pool.yaml

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixing Windows machine-pools in cluster-template-custom-builds-machine-pool.yaml

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixing Windows machine-pools in cluster-template-custom-builds-machine-pool.yaml
```

### CODE REVIEW

**Comment by marosset** [comment]
@jackfrancis @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
were you able to test this locally?

**Comment by marosset** [comment]
> were you able to test this locally?

Running tests now

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
