### PR TITLE
Revert "Pin Azure disk CSI driver Helm chart to v1.29.0"

### LINKED ISSUE #4251: Revert Azure Disk CSI driver Helm chart pin
#4247 pins the version of the Azure Disk CSI driver Helm chart to v1.29.0 because v1.29.1 results in failures that we haven't yet figured out. This issue tracks following up to find a fix and revert the pin.

/kind cleanup

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
This reverts commit 5b00ff831d894915947c0c5020f7d8175b3f892c.

 

 
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: [fix: v1.29.1.1-windows-hp image by andyzhangx · Pull Request #2060 · kubernetes-sigs/azuredisk-csi-driver (github.com)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2060) fixed the issue

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4251 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

to make sure https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4155 merges first

**Comment by troy0820** [comment]
#4155 merged @CecileRobertMichon hold cancel?

/hold cancel

**Comment by CecileRobertMichon** [comment]
yes thanks! 

/assign @willie-yao @jackfrancis

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
