### PR TITLE
Add nojnhuh to maintainers

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

@nojnhuh has developed a deep knowledge of the CAPZ codebase and has been making quality contributions both as an author and a reviewer for almost a year now. This PR proposes promoting Jon to a maintainer of the project.

Thanks for all your contributions @nojnhuh!

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
Thanks @mboersma! I'm happy to jump onboard!

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

@nojnhuh well deserved!!

/hold for consensus

**Comment by sonasingh46** [comment]
/lgtm

+1 Thanks for all the contributions.

**Comment by nawazkh** [comment]
Awaited and well deserved! 🚀 
Thanks for all your great work @nojnhuh !
/lgtm

**Comment by willie-yao** [comment]
/lgtm

+1 Thank you so much for all of your great work and contributions to CAPZ. Well-deserved!

**Pull request merged**
