### PR TITLE
💎  rename feature_gate_machine_pool to exp_machine_pool to match capi

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
rename `feature_gate_machine_pool` to `exp_machine_pool` to match cluster-api
 

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Rename FEATURE_GATE_MACHINE_POOL to EXP_MACHINE_POOL so its matches cluster-api
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
> this also requires an update to test-infra configs https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/test-infra%24%40master+machine_pool&patternType=literal

only the cluster-api-provider-azure file? https://github.com/kubernetes/test-infra/blob/cdd7104bacdd76cb5134c05875fa5fcabd4058ed/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits.yaml#L275

**Comment by CecileRobertMichon** [comment]
> only the cluster-api-provider-azure file?
All the files that reference it in sig-cloud-provider/azure as well.

**Comment by nader-ziada** [comment]
updates to test infra jobs here https://github.com/kubernetes/test-infra/pull/18280

**Pull request merged**
