### PR TITLE
Pin k8s e2e version to v1.25.11

### LINKED ISSUE #3754: Calico failing for ipv6 and dual stack clusters with k8s v1.25.12
**Which jobs are failing:**

[capz-periodic-e2e-main](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main) (and others)

**Which tests are failing:**

`Creating a dual-stack cluster [OPTIONAL]`

**Since when has it been failing:**

Since at least 7/23.

**Testgrid link:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main

**Reason for failure (if possible):**

```shell
 INFO: Waiting for the machine pools to be provisioned
  [1mSTEP:[0m Waiting for the machine pool workload nodes [38;5;243m@ 07/25/23 07:13:54.148[0m
  INFO: Calling PostMachinesProvisioned
  [1mSTEP:[0m Waiting for all DaemonSet Pods to be Running [38;5;243m@ 07/25/23 07:13:54.181[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:13:54.695[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:14:04.813[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:14:14.854[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:14:24.895[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:14:35.005[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:14:45.048[0m
...
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:28:38.529[0m
  [1mSTEP:[0m waiting for 5 daemonset calico-system/calico-node pods to be Running [38;5;243m@ 07/25/23 07:28:48.57[0m
  [38;5;9m[FAILED][0m in [It] - /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:287 [38;5;243m@ 07/25/23 07:28:54.704[0m
  Jul 25 07:28:54.705: INFO: FAILED!
  Jul 25 07:28:54.705: INFO: Cleaning up after "Workload cluster creation Creating a dual-stack cluster [OPTIONAL] With dual-stack worker node" spec
```

**Anything else we need to know:**

/kind failing-test

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: Trying to see if this fixes #3754 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
mitigates #3754 

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
This looks to be mitigating the issue (e2e test passed on first try), started the optional test to run the dual stack test as well

/assign @nojnhuh

**Comment by CecileRobertMichon** [comment]
/hold 

for optional test

**Comment by CecileRobertMichon** [comment]
AKS autoscaler flake

/test pull-cluster-api-provider-azure-e2e-aks

**Comment by CecileRobertMichon** [comment]
@mboersma @nojnhuh thoughts on overriding the aks test here? this is fixing #3754 (or at least getting us unblocked for now) but it can't merge because the aks test is broken in main (tracked by #3763) which is unrelated to this PR (the k8s version change doesn't affect AKS) and @nojnhuh is looking into it separately.

**Comment by nojnhuh** [comment]
+1 to overriding AKS test here

**Comment by CecileRobertMichon** [comment]
/cherry-pick release-1.10
/cherry-pick release-1.9 

since this seems to be affecting both

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
