### PR TITLE
update kcp templates used by capi e2e

### PR DESCRIPTION
**Pull request by nader-ziada**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- remove location field that got removed from templates used by e2e
- 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shysank** [comment]
is this related to the deprecated variables cleanup pr? Not sure why the tests didn't fail

**Comment by nader-ziada** [comment]
> is this related to the deprecated variables cleanup pr? Not sure why the tests didn't fail

the `capi` tests are not run by default and were failing for a different reason

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
