### PR TITLE
Don't reuse windows cnm image if it has os.version set

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4890 updated this script to build the windows cloud-node-manger image as a host-process container.

This PR updates the logic used to determine if we need to rebuild the cloud-node-manager image because we started running into some issues in CI where some test passes were building the image as host-process containers and some weren't.
This causes issues because if the image was build as a non-hpc image for Windows Server 2019 (because that test pass was using an older version of this script), and then we run a test pass against Windows Server 2022 that build the image as a host-process container, the image pull will fail because the `os.version` from the older / non-hpc image will cause some image-version checks to fail in contianerd.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
/test pull-cluster-api-provider-azure-windows-with-ci-artifacts
This cluster came up and all but one test passed hitting one of the known flakes, running it again for good measure

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
