### PR TITLE
lint: gofmt -s lots of files

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Every time I run `make lint` I get complaints about `gofmt`. Perhaps that is because my local environment is golang v1.19. 

In any event, this PR is the result of `gofmt -s -w` across the set of files that are not `gofmt -s`-approved.

Thanks in advance for reviewing this PR. 📿

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/lgtm

I'm surprised any linter would complain about this, but :shrug:. Seems fine with Go 1.18:

```shell
% go version
go version go1.18.5 darwin/arm64
% git fetch jack lint-gofmt && git checkout -b lint-gofmt jack/lint-gofmt && make lint
% echo $?
0
```

**Comment by jackfrancis** [comment]
@mboersma I would guess that `gofmt` is more opinionated starting in 1.19 about those generated code-informing comment pragma blocks (those are the bulk of the errors).

**Comment by jackfrancis** [comment]
I think this set of changes won't materially harm smooth backports of future commits into release branches.

/approve

**Pull request merged**
