### PR TITLE
Fix race condition when creating resource group with custom user tags

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Fixes a race condition with custom user-defined tags. Currently, if a user defines custom tags, the group is first created with the default set of tags and then the custom tags are added in the tags service. This can cause issues if the subscription has automation running that checks for certain tags to perform automated cleanup or apply policies. This makes sure the tags are added right away when the group is first created, then updated separately by the tags service as needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Ensure additional tags are added right away when the group is created
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by jackfrancis** [comment]
looks like there are some spec_test.go UT in other services, we should probably spike on standardizing UT for all of these at some point

**Review by sonasingh46 — APPROVED** [review]

**Comment by CecileRobertMichon** [comment]
@jackfrancis could I please get a /lgtm on this one?

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
