### PR TITLE
Add a subnet role for bastions and enum validation

### LINKED ISSUE #2000: Add a role for bastion subnets
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Every subnet requires a role to be set, but if you pass an empty AzureBastion spec, it creates a subnet with no role which is defaulted to an empty string. This can be seen in the private cluster e2e test. However, it would make sense to add a role for bastion subnets.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**

**What this PR does / why we need it**: Currently there is no role for AzureBastions. It would make sense to define a role similar to how it's done for node and control plane subnets.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2000 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Add a subnet role for bastions
```

### CODE REVIEW

**Comment by Jont828** [comment]
@CecileRobertMichon Any thoughts?

**Comment by CecileRobertMichon** [comment]
@Jont828 looks good. If this is ready please add a release note, rebase and remove the WIP tag.

**Comment by Jont828** [comment]
Sounds good, I'll rebase and it should be ready for review!

**Comment by CecileRobertMichon** [comment]
/retest

looking into the LB flake, it does not related to this PR

**Review by shysank — COMMENTED** [review]
Should we set bastion subnet in the defaults? Also, we are using a different constant for bastion role in [cluster.go](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/bc44584aa2c2ff6bd1612e5671f4c2f6c4a8a3b0/azure/scope/cluster.go#L312). Should we refactor this as well?

**Comment by Jont828** [comment]
@shysank It looks like the role in cluster.go is the isn't a constant but role that the user specifies. I'll add a default role in the webhook though. Thanks for the catch!

**Comment by CecileRobertMichon** [comment]
lgtm

@Jont828 please squash

**Pull request merged**
