### PR TITLE
Update opentelemetry-go to v1.2.0

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates opentelemetry-go to v1.2.0, and its unstable packages to v0.25.0. Also updates the otel helm chart to v0.8.1 and adjusts a few values to match.

See https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.2.0

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

I've tested this locally and metrics and traces (to App Insights and to Jaeger) work fine.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> I've tested this locally and metrics and traces (to App Insights and to Jaeger) work fine.

not going to test this locally given ^, code changes lgtm

/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
