### PR TITLE
Update AAD Pod Identity to v1.8.6

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: v1.8.6 should fix intermittent `MSI not available` issues https://github.com/Azure/aad-pod-identity/issues/1207#issuecomment-1004384569

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update AAD Pod Identity to v1.8.6
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

this is going to require a bit more work...

because https://github.com/Azure/aad-pod-identity/commit/e7cda9a9467de00e851eb305176d193b4a8f5ef7  upgraded the go-logr to v1, we can't upgrade aad pod identity to 1.8.6 without bumping go-logr, which has a bunch of breaking changes, and also requires bumping controller runtime https://github.com/kubernetes-sigs/controller-runtime/issues/1607

**Comment by CecileRobertMichon** [comment]
this requires #1951 to merge first

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
