### PR TITLE
 🐛 fix typo in cloud-env default

### PR DESCRIPTION
**Pull request by alexeldeib**
**What this PR does / why we need it**:
🐛 fix typo in cloud-env default

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
n/a

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alexeldeib** [comment]
no release note since we haven't tagged a release between this and https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/dadb939702a37a20b30a67c532dbec8f150e0105 ?

**Comment by CecileRobertMichon** [comment]
@alexeldeib do I need to retag the release for this?

**Comment by nader-ziada** [comment]
doesn't :- and := both work?

**Comment by alexeldeib** [comment]
user error ☹️ I keep getting confused by the defaulting because every time it changes it breaks upstream capi tilt experience. https://github.com/kubernetes-sigs/cluster-api/issues/3326

I guess I'll try to fix that instead

/close

**Pull request closed without merging**
