### PR TITLE
[release-1.14] Bump CAPI to v1.6.7

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI to [v1.6.7](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.7). Also bumps cert-manager to v1.15.1 to stay in sync with CAPI.

**Which issue(s) this PR fixes**:

N/A, but see #4916 for prior art.

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.6.7
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
> This is panicking with a nil pointer when running `controller-gen`, and I can reproduce it locally. It’s unclear to me what change triggered this bug.
> 
> Updating to `controller-gen` v0.14.0 seems to fix the problem, and that’s what we’re using in the newer release branch, so I’ll try that.

@sbueringer [mentioned on Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1719379544466209) that the kubekins CI images got bumped to Go 1.22 which controller-gen 0.13 had panic issues with, so I'm assuming this is that same issue. Looks like what they did in CAPI was bump to (use but not require) Go 1.22: https://github.com/kubernetes-sigs/cluster-api/pull/10802

**Comment by mboersma** [comment]
> Looks like what they did in CAPI was bump to (use but not require) Go 1.22

We could do that, although it would be strange to do so just in the release branch IMHO. I'd feel more comfortable making that change in `main` and then cherry-picking (so my workaround seems simpler for now). I'll try that approach soon.

**Comment by sbueringer** [comment]
You can also just continue to compile controller-gen with Go 1.21, less churn: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3077/files

**Comment by mboersma** [comment]
```
info - 2024-07-10 21:33:17,198 -- ci service found: github-actions
Error: Codecov token not found. Please provide Codecov token with -t flag.
```

@nojnhuh I admit not to understanding how codecov works now. Any ideas how I can fix or work around it?

**Comment by nojnhuh** [comment]
> ```
> info - 2024-07-10 21:33:17,198 -- ci service found: github-actions
> Error: Codecov token not found. Please provide Codecov token with -t flag.
> ```
> 
> @nojnhuh I admit not to understanding how codecov works now. Any ideas how I can fix or work around it?

That makes two of us. I think cherry-picking this change into this PR would fix it: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4952

I had originally closed that because of the controller-gen panic thing, but if that's fixed here too then I think it would work. Both changes probably have to land at the same time though.

**Comment by nojnhuh** [comment]
I also wouldn't totally rule out skipping this entirely if we're going to stop supporting v1.14 next week. No changes have been merged since v1.14.6 and the couple of backports I've closed since then aren't user-facing.

**Comment by mboersma** [comment]
@nojnhuh this is green and ready for re-review. 😄

**Review by nojnhuh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
