### PR TITLE
Correcting reference to kops

### PR DESCRIPTION
**Pull request by paulbouwer**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Corrects a reference to `kops` in the README.

**TODOs**:

- [ ] squashed commits
- [X] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by paulbouwer** [comment]
As per our conversation @craiglpeters.

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
