### PR TITLE
Update Kustomize to v5.4.1

### PR DESCRIPTION
**Pull request by RadekManak**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updates Kustomize binary to v5 and converts all deprecated functions to alternatives.

There is no change to generated output.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
Thanks for working on this @RadekManak 
+1 from me.
/lgtm

**Comment by damdo** [comment]
@RadekManak verification is failing, could you PTAL?

**Comment by mboersma** [comment]
@RadekManak you need to run `make generate` (be patient, it takes a long time) and then commit the changes it creates.

**Review by damdo — COMMENTED** [review]
/lgtm

/assign @mboersma

**Comment by jackfrancis** [comment]
/hold
/approve

Feel free to remove hold when sufficient green test signal is achieved

**Comment by jackfrancis** [comment]
/retest

for realz

**Comment by jackfrancis** [comment]
Thank you @RadekManak for this!!!

**Pull request merged**
