### PR TITLE
Move CecileRobertMichon to emeritus

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Moving myself to emeritus. After 6+ years at Microsoft and the last 3+ years spent working with the Cluster API community, I've decided to try something new which means I'll have less time to dedicate to this project going forward. I am removing myself as an approver to make room for future approvers. I've learned so much from the folks in this community and am proud to see how far the project has come. I will still be around in the k8s slack, feel free to reach out! 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
/lgtm 

Thank you for all you've done and good luck on your next adventure.  It has been a pleasure working with you and I've learned a ton from you too!

**Comment by jackfrancis** [comment]
What @jsturtevant said.

**Comment by mboersma** [comment]
/lgtm

Best of luck @CecileRobertMichon! It's been wonderful to work with you. I'm sure you'll be amazing at your next thing. Au revoir !

**Comment by willie-yao** [comment]
/lgtm

Thank you for everything you've done for this team and community! It was an honor working with you. I won't be where I am today without your help and guidance and I wish you the best of luck with your future endeavors! ❤️

**Comment by nojnhuh** [comment]
\*happysad `/lgtm` noises\*
/lgtm

**Comment by nawazkh** [comment]
/lgtm

Thank you for everything you have done @CecileRobertMichon , It has been an absolute pleasure working with you! Wish you the best !

**Comment by sonasingh46** [comment]
/lgtm

Thank you Cecile for all the awesome contributions and impact. All the best.

**Comment by jackfrancis** [comment]
/approve

🍾 to a wonderful future for Cecile working on bigger and better things! ❤️

**Pull request merged**
