### PR TITLE
remove unneeded embedded interfaces from ASO services

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: This PR removes the `azure.ClusterScoper` interface from a few of the ASO services' `Scope` types since it's not needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm
/assign @CecileRobertMichon

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by nawazkh** [comment]
Nice find Jon. Just to understand it right, we are removing `azure.ClusterScoper` because `aso.Scope` and other interfaces implemented by the ASO services already provide the access to the methods `azure.ClusterScoper` provided ?

**Comment by nojnhuh** [comment]
> Nice find Jon. Just to understand it right, we are removing `azure.ClusterScoper` because `aso.Scope` and other interfaces implemented by the ASO services already provide the access to the methods `azure.ClusterScoper` provided ?

`ClusterScoper` provided a different set of methods, but none of them were ever called on instances of these Scope types.

**Pull request merged**
