### PR TITLE
[release-1.8] fix some variables in ci-build-azure-ccm.sh

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: This is a manual cherry-pick PR to workaround https://github.com/communitybridge/easycla/issues/3884. It cherry-picks a couple of recent commits in the ci-build-azure-ccm.sh script, notably fixing the IMAGE_TAG variable reuse across scripts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
/hold

need to check something

**Comment by CecileRobertMichon** [comment]
/hold cancel

all good

**Pull request merged**
