### PR TITLE
[release-0.5] update capi references to v0.4.7

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

This PR updates the release-0.5 branch to refer to a new v0.4 release of capi, enabling us to continue testing the 0.5 release branch of capz

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
we can ignore the exp test until #2028 merges but ci-entrypoint should pass

/retest

**Comment by CecileRobertMichon** [comment]
private cluster flake, everything else looks good

/retest

**Pull request merged**
