### PR TITLE
Upgrade to calico 3.23.0

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind failing-test
/kind cleanup
/kind bug

**What this PR does / why we need it**:

Kubernetes 1.25 has [dropped support for discovery.k8s.io/v1beta1](https://github.com/kubernetes/kubernetes/pull/108797) which is causing all the [CI jobs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/capz-conformance-master/1524844475128483840) that run against the kubernetes main branch to fail.  Calico 3.23.0 upgraded to the [discovery.k8s.io/v1 api](https://github.com/projectcalico/calico/pull/5466/files#diff-5e8415203d263cc585330c58d0f6eba88c9db13633095076adc53017b6479571 ) which fixes this issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Windows images where updated in https://github.com/kubernetes-sigs/sig-windows-tools/pull/219.  Will be a follow on pr to move to the calico produced images for Windows.

found in https://github.com/kubernetes/kubernetes/pull/110013#issuecomment-1125431119 by @marosset 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade to Calico 3.23.0
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
lgtm pending tests

**Comment by marosset** [comment]
LGTM

**Comment by marosset** [comment]
PR title should be `3.23.` instead of `1.23.0`

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

conformance cluster built successfully, tests are still running

**Pull request merged**
