### PR TITLE
[WIP] Increase parallelism for e2e tests

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by shysank** [comment]
Two of the tests that failed in the last run didn't get reconciled at all in `AzureCluster` and remains in provisioning state. This has been a somewhat consistent failure in most of the runs.

**Comment by shysank** [comment]
Run https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1816/pull-cluster-api-provider-azure-capi-e2e/1456472033914261504 passed in 1hr 29 min! Was it luck? Try again.
/test pull-cluster-api-provider-azure-capi-e2e

**Comment by shysank** [comment]
One more pass https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1816/pull-cluster-api-provider-azure-capi-e2e/1456648404498124800 in  ~1hr30 mins. 2/3 passed. Cautiously optimistic. Try again.

/test pull-cluster-api-provider-azure-capi-e2e

**Comment by shysank** [comment]
uh oh it failed again https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1816/pull-cluster-api-provider-azure-capi-e2e/1456676924385398784. Again, not reconciling azure cluster objects. Perhaps the bootstrap cluster is overloaded with watches?

**Comment by shysank** [comment]
4 out of the last 5 tests passed. The one failure was due to a mhc flake. Looks like increasing the concurrency has resolved the AzureCluster reconciliation issue. Going to revert other hacks, and properly set concurrency in test, and try again for a few times.

**Comment by shysank** [comment]
Ginkgo node is not responding sometimes https://github.com/onsi/ginkgo/issues/206 and times out after 4 hours. This is happening for quick start spec mostly. Going to add `-debug` and try again to find the cause as suggested in the issue.

**Comment by shysank** [comment]
`Message: "admission webhook \"validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io\" denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io \"kcp-upgrade-9hh6vc-control-plane\" is invalid: spec.kubeadmConfigSpec.clusterConfiguration.etcd.local.extraArgs: Forbidden: cannot be modified",` This error is back again :(

**Comment by CecileRobertMichon** [comment]
I think we can close this now that we somewhat solved our problem by removing upgrade from spec

Still something that might be worth revisiting later but for now

/close

**Pull request closed without merging**
