### PR TITLE
Refactor infrastructure-azure templates required by CAPI tests to match CAPD

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Instead of having static templates for capi e2e tests with lots of duplicated yaml, use kustomize to generate the required templates for the CAPI e2e suite. The templates were added to gitignore so they are not checked into code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
2 questions;
- what is the empty file used for? `templates/test/dev/cluster-template-v1alpha4.yaml`
- Do you think there is value in also checking in the generated yaml templates files like we do with the `/templates` folder?

**Comment by CecileRobertMichon** [comment]
> what is the empty file used for? templates/test/dev/cluster-template-v1alpha4.yaml

removed, it was pushed by mistake

> Do you think there is value in also checking in the generated yaml templates files like we do with the /templates folder?

for now I added them to .gitignore (same as CAPI docker e2e templates). No strong opinion here but I was thinking it doesn't really make sense to check them in since they are only used by e2e and get generated when e2e runs.

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/4830 should help with the drain timeout test (VM deletion is timing out), will disable it until we can pull it in

**Comment by CecileRobertMichon** [comment]
@nader-ziada this is ready besides the fact that I'm running into the same flake as described in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1440

/retest

**Comment by nader-ziada** [comment]
/lgtm

will check back in a bit on the e2e run

**Comment by CecileRobertMichon** [comment]
looks like that one passed, will monitor the health of the periodic job 

/approve

**Pull request merged**
