### PR TITLE
Add *.yaml *.sh as LF to .gitattributes and Fix Some YAML EOLs

### PR DESCRIPTION
**Pull request by luthermonson**
**What type of PR is this?**
Utility PR to fix CRLF on yaml files in the repo, when you run `make generate` in WSL from a windows checkout these files will get remade with LF as the line endings and make horrendous diffs so you dont know if it was actually updated. This PR adds *.yaml to always be LF and fixes the index for the yaml files that were checked in as CRLF.

To check this you can do something like this

```powershell
~\kube\cluster-api-provider-azure [main] > git ls-files --eol test/e2e/workloads/policies/backend-policy-deny-ingress.yaml
i/crlf  w/crlf  attr/                   test/e2e/workloads/policies/backend-policy-deny-ingress.yaml
```

which shows that both the index upstream and the current working directory have CRLF while the rest of the yaml files are `i/lf`

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
the only actual change is adding the .gitattributes line, the yaml files should be identical just with new line endings, you can confirm the line endings by opening the github.dev for each file and see CRLF in the bottom right.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
pro tip for reviewers append `?w=1` to the diff presentation in the "Files changed" tab to validate that the modified files have non-significant whitespace changes only

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by luthermonson** [comment]
fyi i had a typo in the *.sh https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/3d7fd23818d78544a9fca9876e06a6cc0d4305b9..8838a7cb2f2e43ac35754bf107caf2ee9ba9623b

fixed it but will need to retest and confirm approval pls

**Pull request merged**
