### PR TITLE
improve formatted output of `make` or `make help`

### LINKED ISSUE #2073: Improve readability of Makefile
/kind feature
^ minor readability improvement tbh

**Describe the solution you'd like**

Running `make` could display better _help_ with segregated targets like CAPI does. 
Ex:
```
Targets:
  help                                           Display this help

test:
  test                                           Run generate lint and tests
  go-test                                        Run go tests
  ...

binaries:
  binaries                                       Builds and installs all binaries
...

tooling binaries
  conversion-verifier                            fetch CAPI's conversion verifier

linting:
  lint                                           Lint codebase
  ...

generate:
  modules                                        Runs go mod to ensure proper vendoring.
  ...

docker:
  docker-build                                   Build the docker image for controller-manager
   ...

docker all ARCH:
  docker-push-manifest                           Push the fat manifest docker image.

release:
  release                                        Builds and push container images using the latest git tag for the commit.
   ...
```

**Anything else you would like to add:**

- None

**Environment:**

- cluster-api-provider-azure version: latest
- Kubernetes version: (use `kubectl version`): v1.23.3
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Targets/Recipes in the makefile can be grouped as per their goal, improving user's readability.
With this PR, running `make` will output
```
Usage:
  make <target>

help:
  help                       Display this help

test:
  test                       Run generate lint and tests
  go-test                    Run go tests
  test-cover                 Run tests with code coverage and code generate reports
  test-conformance           Run conformance test on workload cluster.
  test-conformance-fast      Run conformance test on workload cluster using a subset of the conformance suite in parallel.
  test-windows-upstream      Run windows upstream tests on workload cluster.
  env-info                   Temporary target to get additional logs in prow tests

binaries:
  binaries                   Builds and installs all binaries
  manager                    Build manager binary.

tooling binaries:
  conversion-verifier        Fetch CAPI's conversion verifier

linting:
  lint                       Lint codebase
  lint-fix                   Lint the codebase and run auto-fixers if supported by the linter
  lint-full                  Run slower linters to detect possible issues

generate:
  modules                    Runs go mod to ensure proper vendoring.
  generate                   Generate code
  generate-go                Runs Go related generate targets
  generate-manifests         Generate manifests e.g. CRD, RBAC etc.
  generate-addons            Generate metric-server, calico calico-ipv6 addons
  . 
  .
  .
```

**Which issue(s) this PR fixes** 
Fixes #2073 

**Special notes for your reviewer**:
- There are few recipes with no description (##) to them (for ex: `release-binary`, `release-notes`, `promote-images`). Shall I add more descriptions or keep them as is? 

 
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
- No changes to image versions

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
This does improve organization (organized groupings vs a flat structure), though I'm concerned this output might confuse folks about what the actual make target values are.

@mboersma do you have any thoughts?

**Comment by mboersma** [comment]
> I'm concerned this output might confuse folks about what the actual make target values are

I can see that. For example, you might think the section headers are actual make targets (and some of them do agree).

When you actually run `make help` in a shell on this branch, you get ANSI coloring that clarifies targets and headers enough, I think.
make-help

Using just colors isn't ideal accessible UI design, but we're also using bold here. I think it's a nice improvement. I would be curious what other users think too.

**Comment by sonasingh46** [comment]
One good thing about this grouping is -- it help onboard a contributor very quickly. The value increases more for developers when we have more granular make targets and they know what to run at that point and not the entire subsets. For instance running an entire conversion targets take quite some time and I may want to run  a conversion sub target only and the help command should be useful here.
So in case I want to run couple of targets -- if `make help` is not there I need to go back and forth to `Makefile` and read the comments, code etc which can be hectic. This grouping also prompts us(definitely not enforce) to put description around the targets which is a good thing.

May be I am overlooking the cons but @jackfrancis can you please explain a bit on this: 
```
though I'm concerned this output might confuse folks about what the actual make target values are.
```

**Comment by sonasingh46** [comment]
I am pasting similar grouping from CAPI if that helps you @nawazkh to put the description and all. 
But in any case, let us see what people have to say about getting this in.

```
Usage:
  make <target>

Targets:

generate:
  generate                                       Run all generate-manifests-*, generate-go-deepcopy-* and generate-go-conversions-* targets
  generate-manifests                             Run all generate-manifests-* targets
  generate-manifests-core                        Generate manifests e.g. CRD, RBAC etc. for core
  generate-manifests-kubeadm-bootstrap           Generate manifests e.g. CRD, RBAC etc. for kubeadm bootstrap
  generate-manifests-kubeadm-control-plane       Generate manifests e.g. CRD, RBAC etc. for kubeadm control plane
  generate-go-deepcopy                           Run all generate-go-deepcopy-* targets
  generate-go-deepcopy-core                      Generate deepcopy go code for core
  generate-go-deepcopy-kubeadm-bootstrap         Generate deepcopy go code for kubeadm bootstrap
  generate-go-deepcopy-kubeadm-control-plane     Generate deepcopy go code for kubeadm control plane
  generate-go-conversions                        Run all generate-go-conversions-* targets
  generate-go-conversions-core                   Generate conversions go code for core
  generate-go-conversions-kubeadm-bootstrap      Generate conversions go code for kubeadm bootstrap
  generate-go-conversions-kubeadm-control-plane  Generate conversions go code for kubeadm control plane
  diagrams                                       Generate diagrams for *.plantuml files

lint and verify:
  modules                                        Run go mod tidy to ensure modules are up to date
  lint                                           Lint the codebase
  lint-fix                                       Lint the codebase and run auto-fixers if supported by the linter
  apidiff                                        Check for API differences
  format-tiltfile                                Format the Tiltfile
  verify                                         Run all verify-* targets
  verify-modules                                 Verify go modules are up to date
  verify-gen                                     Verfiy go generated files are up to date
  verify-conversions                             Verifies expected API conversion are in place
  verify-boilerplate                             Verify boilerplate text exists in each file
  verify-shellcheck                              Verify shell files
  verify-tiltfile                                Verify Tiltfile format
  verify-book-links                              Verify book links

build:
  clusterctl                                     Build the clusterctl binary
  managers                                       Run all manager-* targets
  manager-core                                   Build the core manager binary into the ./bin folder
  manager-kubeadm-bootstrap                      Build the kubeadm bootstrap manager binary into the ./bin folder
  manager-kubeadm-control-plane                  Build the kubeadm control plane manager binary into the ./bin folder
  docker-build                                   Run all docker-build-* targets
  docker-build-core                              Build the docker image for core controller manager
  docker-build-kubeadm-bootstrap                 Build the docker image for kubeadm bootstrap controller manager
  docker-build-kubeadm-control-plane             Build the docker image for kubeadm control plane controller manager
  e2e-framework                                  Builds the CAPI e2e framework

test:
  test                                           Run unit and integration tests
  test-e2e                                       Run the e2e tests
  test-junit                                     Run tests with verbose setting and generate a junit report
  test-cover                                     Run tests with code coverage and code generate reports
  test-verbose                                   Run tests with verbose settings
  serve-book                                     Build and serve the book with live-reloading enabled
  kind-cluster                                   Create a new kind cluster designed for testing with Tilt
  docker-build-e2e                               Rebuild all Cluster API provider images to be used in the e2e tests

release:
  release                                        Build and push container images using the latest git tag for the commit
  release-manifests                              Build the manifests to publish with a release
  release-manifests-dev                          Build the development manifests and copies them in the release folder
  release-binaries                               Build the binaries to publish with a release
  release-staging                                Build and push container images to the staging bucket
  release-staging-nightly                        Tag and push container images to the staging bucket. Example image tag: cluster-api-controller:nightly_main_20210121
  release-alias-tag                              Add the release alias tag to the last build tag
  docker-build-all                               Build all the architecture docker images
  docker-push                                    Push the docker images
  docker-push-all                                Push all the architecture docker images
  docker-push-manifest-core                      Push the multiarch manifest for the core docker images
  docker-push-manifest-kubeadm-bootstrap         Push the multiarch manifest for the the kubeadm bootstrap docker images
  docker-push-manifest-kubeadm-control-plane     Push the multiarch manifest for the the kubeadm control plane docker images

clean:
  clean                                          Remove all generated files
  clean-bin                                      Remove all generated binaries
  clean-book                                     Remove all generated GitBook files
  clean-release                                  Remove the release folder
  clean-release-git                              Restores the git files usually modified during a release
  clean-generated-conversions                    Remove files generated by conversion-gen from the mentioned dirs. Example SRC_DIRS="./api/v1alpha4"

hack/tools:
  controller-gen                                 Build a local copy of controller-gen
  conversion-gen                                 Build a local copy of conversion-gen
  conversion-verifier                            Build a local copy of conversion-verifier
  gotestsum                                      Build a local copy of gotestsum
  go-apidiff                                     Build a local copy of apidiff
  golangci-lint                                  Build a local copy of golangci-lint
  envsubst                                       Build a local copy of envsubst
  kustomize                                      Build a local copy of kustomize
  setup-envtest                                  Build a local copy of setup-envtest
  tilt-prepare                                   Build a local copy of tilt-prepare
  kpromo                                         Build a local copy of kpromo
  ```

**Comment by CecileRobertMichon** [comment]
I'm +1 on this change, as the number of make targets grows it becomes harder to find what you're looking for in a flat structure.

**Comment by nawazkh** [comment]
Thank you for the reference @sonasingh46 , I've made the targets a little more descriptive and added the missing ones. 

- Commits 703900e001980e6d95d0416eb0835ab0c5d6193a, 5f371948fae7249f1ead08398020123230e74c3d, ea723a282205a906796cef4d465fa6c428638748, 9b3651075fbde0fd1e70a3101f87a54507387a8c, 060c8e07824c496eea709f534979372657c546f0, aefb5b12a7d4ee05daeb4271a8508b6fcf44339f, 8f6770430c2de5208aed10062cad6a57e5c8b68b, 2957550700dccfb9d2bc9ebcb4a0971a7e4668f6, f807905428332036226cc4059d70b8795624d54e, 3d81467429e679069548e61107a05cee2fc5dcfc, 3c3f284e498ef1c314ab70e7b6ea4c285b001367 update the description of the targets/rules in the `Makefile`
- Commit d0e6b75d262197b9a0f26e2d9fe653df145fa69e capitalizes group headers.
- Commit c0ca4897af41ffea69d8eedb85edae10226070e2 sorts group headers for better readability. 

---
Running `make` with the above changes gives the below output (color scheme may differs per user)
What do you all, @CecileRobertMichon @sonasingh46 @mboersma @jackfrancis, think ?
Screen Shot 2022-02-15 at 1 43 01 AM

**Comment by jackfrancis** [comment]
@nawazkh can you kindly squash commits?

thanks!

**Comment by CecileRobertMichon** [comment]
flake 

/retest

**Comment by CecileRobertMichon** [comment]
I'm not sure why the test keeps failing, nothing in this PR should impact it. Will look into the flakes. 

/retest

This should be good to go pending review.

/assign @sonasingh46 @jackfrancis @mboersma

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
