### PR TITLE
version-update

### LINKED ISSUE #1656: Migrate codecov action to v2
https://github.com/codecov/codecov-action

v1 is being depracated, we should use v2 instead in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/cover.yaml.

This might require changing some of the parameters to work with v2.

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Migrate codecov action to v2

 

 
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1656

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by sayantani11** [comment]
Add NONE to release note if it doesn't have one
like:
release notes
``` 
NONE
```

**Comment by nader-ziada** [comment]
@himanshu007-creator there is already another PR making the same change #1661 

would you mind closing this one?

**Comment by sayantani11** [comment]
@nader-ziada I guess @himanshu007-creator took the issue first but then the other contributor made the PR 😐

**Comment by mboersma** [comment]
@himanshu007-creator did you determine that nothing else needs to be changed here? In the codecov-action v1 -> v2 migration document,  it says:

> Multiple fields have not been transferred from the bash uploader or have been deprecated. Notably many of the `functionalities` and `gcov_` arguments have been removed. Please check [the documentation below](https://github.com/codecov/codecov-action#migration-from-v1-to-v2) for the full list.

**Comment by mboersma** [comment]
/close

@himanshu007-creator it was a bit of a coin toss, but I'm trying to clean up the PR queue and let's go with #1661 as @nader-ziada suggested.

 We appreciate your help! Please let us know if you're looking for more "help wanted" or "good first issues" to tackle.

**Pull request closed without merging**
