### PR TITLE
Fix issue for Windows Flannel deployments when packet size is over 1400 MTU

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind failing-test
/kind bug

**What this PR does / why we need it**:

Flannel is being used as the default CNI.  An important note for Flannel vxlan deployments is that the MTU for the linux nodes must be set to 1400.  
This is because [Azure's VNET MTU is 1400](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tcpip-performance-tuning#azure-and-vm-mtu) which can cause fragmentation on packets sent from the Linux node to Windows node resulting in dropped packets. 
To mitigate this we set the Linux eth0 port match 1400 and Flannel will automatically pick this up and [subtract 50](https://github.com/flannel-io/flannel/issues/1011) for the flannel network created.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Found issues during testing of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1119

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [X] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Use MTU of 1400 on linux nodes when including Windows deployments using vxlan
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
linux nodes are getting the correct config:

```
capi@testmtu-md-0-7rk8c:~$ ifconfig
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1350
        inet 10.244.1.1  netmask 255.255.255.0  broadcast 10.244.1.255
        inet6 fe80::54e1:1cff:fee9:470c  prefixlen 64  scopeid 0x20<link>
        ether 56:e1:1c:e9:47:0c  txqueuelen 1000  (Ethernet)
        RX packets 57  bytes 5891 (5.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54  bytes 16244 (16.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet 10.1.0.4  netmask 255.255.0.0  broadcast 10.1.255.255
        inet6 fe80::20d:3aff:fe6f:26f7  prefixlen 64  scopeid 0x20<link>
        ether 00:0d:3a:6f:26:f7  txqueuelen 1000  (Ethernet)
        RX packets 16760  bytes 19577003 (19.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3676  bytes 591586 (591.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.4096: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1350
        inet 10.244.1.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::1002:53ff:fe0b:dcd8  prefixlen 64  scopeid 0x20<link>
        ether 12:02:53:0b:dc:d8  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 7 overruns 0  carrier 0  collisions 0
```

and the test was failing are passing:

```
{"msg":"PASSED [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource [Conformance]","total":1,"completed":1,"skipped":3537,"failed":0}
```

**Comment by jsturtevant** [comment]
/hold
learned that `ifconfig eth0 mtu 1400 up` doesn't persist across reboots.  

I also found out this could be an issue in Linux only vxlan deployments. Linux doesn't crash when reassembling the packets but it will affect throughput (possibly significantly).  I will open a separate PR for that update.

**Comment by jsturtevant** [comment]
I've updated to use persist across reboots.  Unfortunately netplan has a bug that requires an extra few steps to register the mtu properly

/unhold

**Comment by jsturtevant** [comment]
flake was https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1328

/retest

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by jsturtevant** [comment]
flake was #1328. I've started to address this by working on the log collection to have better insight into what is happening

/retest

**Comment by jsturtevant** [comment]
@nader-ziada @CecileRobertMichon I noticed my commits were not squashed so I push again.  could I get lgtm again?

**Pull request merged**
