### PR TITLE
Update opentelemetry-go to v1.9.0

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates opentelemetry-go to v1.6.1, and its unstable packages to v0.28.0. Also updates the otel helm chart to v0.12.1.

See https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.6.1

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

I've tested this locally and metrics and traces to Jaeger work fine, but I can't see things in App Insights. Then I backed up to the main branch and tried there but also couldn't see them in App Insights. So...I think this PR is sane but I'm unable to verify  yet and will continue testing.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

I haven't been able to verify that traces to App Insights are still working, so let's keep this from merging until I can figure that out.

**Comment by mboersma** [comment]
/hold

I'm still trying to verify that this works with App Insights.

**Comment by CecileRobertMichon** [comment]
@mboersma can we close this and reopen when it's ready for review?

/remove-lifecycle active

**Comment by mboersma** [comment]
/close

I'll reopen when time permits to revisit this. At this point, I think we should remove App Insights support in order to stay current with otel.

**Pull request closed without merging**
