### PR TITLE
remove CSI migration test for EOL'd k8s v1.22

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR removes the test scenario for k8s v1.22-->v1.23 upgrade, including migration to CSI, now that 1.22 is EOL.

Thank you @sonasingh46!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Addresses #3055

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Review by sonasingh46 — APPROVED** [review]
/lgtm

**Pull request merged**
