### PR TITLE
clean up kind with local registry and remove kind ingress

### PR DESCRIPTION
**Pull request by devigned**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I recently picked up a new OSX machine and was setting up CAPZ development. I was surprised to see that when I ran `make tilt-up` there was already a service running on localhost 5000, AirTunes. Since others might run into this kind of situation, I wanted to introduce a env var to help out with configuring the port the kind local registry runs on.

Since I was already in the kind setup script, I also took a little time to reduce the things going on in the script to the bare minimum. I removed the ingress setup that was used for metrics and tracing. The Tilt link for metrics and tracing works without ingress, so it was no longer needed.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

Much simpler. I tested this locally and didn't see any problems using the registry it creates with `make tilt-up`.

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Pull request merged**
