### PR TITLE
🌱Remove redundant length check for error in webhooks

### PR DESCRIPTION
**Pull request by arghya88**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

`kerrors.NewAggregate` internally does length check so it's not necessary to do the check again.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [X] squashed commits
- [X] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by devigned** [comment]
Hmm... That really strikes me as odd from a Go dev standpoint. Non-nil error returns are a pretty fundamental thing. I'm not saying these changes are wrong, but just feels non-idiomatic.

**Comment by CecileRobertMichon** [comment]
Agreed it's non-obvious but that is indeed what `NewAggregate` does so this change lgtm

**Comment by arghya88** [comment]
Also I have seen many examples of using `NewAggregate` this way in the `kubernetes` repo.

**Review by devigned — APPROVED** [review]
> Also I have seen many examples of using NewAggregate this way in the kubernetes repo.

Agreed, but I hesitate to make that a litmus test for what qualifies for best practices in Go.

My weak protest is noted.

/lgtm
/approve

**Comment by devigned** [comment]
Thank you for the PR, @arghya88!

**Pull request merged**
