### PR TITLE
 :gem: dedupe tag reconciliation on machine pool

### LINKED ISSUE #817: de-dupe tag reconciliation on machinepool
**What steps did you take and what happened:**
We duplicate tag reconciliation on machine pools right now

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/06649e1090c393e38462c8513b62226c918717cf/exp/controllers/azuremachinepool_controller.go#L287-L291

The code above is unnecessary because this code already reconciles all tags: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/scalesets/vmss.go#L118

we also already do a GET inside scalset service so we could move this logic there, if it's even necessary still https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/exp/controllers/azuremachinepool_controller.go#L407

**What did you expect to happen:**

we only reconcile tags once

**Anything else you would like to add:**

/kind cleanup 
/good-first-issue
/help-wanted

### PR DESCRIPTION
**Pull request by Deeps-1989**
**What this PR does / why we need it**:
We duplicate tag reconciliation on machine pools right now. So with this PR we only reconcile tags once

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #817

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
dedupe tag reconciliation on machine pool 
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@Deeps-1989 please add a release note in the PR description (can be the same as your commit message), this is what helps us give you credit in the release notes

**Comment by Deeps-1989** [comment]
@CecileRobertMichon Thanks, added release notes.

**Pull request merged**
