### PR TITLE
:book: update tilt docs

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: improve the Tilt doc.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
looks good, will just wait for the other PR to fix the e2e tests

**Comment by CecileRobertMichon** [comment]
I probably need to rebase first

**Comment by nader-ziada** [comment]
I thought the prow bot would rebase on latest from master before running the tests

**Comment by CecileRobertMichon** [comment]
> I thought the prow bot would rebase on latest from master before running the tests

If that's the case then it should pass, let's see what happens I'll hold off on rebasing until this run finishes

**Comment by nader-ziada** [comment]
@CecileRobertMichon it worked :D

**Pull request merged**
