### PR TITLE
[release-1.10] Fix AKS reconciliation of taints

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
This is a manual cherry-pick of #4066 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix AKS reconciliation of taints
```

### CODE REVIEW

**Comment by willie-yao** [comment]
/assign @nojnhuh 

Looks like codespell is complaining about files I didn't change?

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Comment by nawazkh** [comment]
We do not have `codespell.yml` maintained on `main`, that's why.

**Comment by nawazkh** [comment]
PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4136 now also adds `codespell.yml`.

**Comment by nawazkh** [comment]
We need this merged before https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4122 can be cherry-picked onto `release-1.10`.

**Comment by CecileRobertMichon** [comment]
> PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4136 should fix the codespell errors you see on this PR.

That PR is targetting main, will it need to be cherry-picked to fix the errors on the release-1.10 branch?

I don't fully understand how codespell broke in the release branch, shouldn't the action catch any spelling errors merged in cherry pick PRs?  Is it because the new version that was released introduces new spelling errors and the github action is using latest?

**Comment by CecileRobertMichon** [comment]
> release-1.10 seem to be using [codespell@master github action](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/a5988177fe8aa8f50816aa2466dcf08f85ff3f75/.github/workflows/codespell.yml#L9).
Whereas release-1.11 and main are using [codespell v2.2.5 make target](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1c580ceffdf033924ae20aecf1472c102fd7ff0d/Makefile#L128).

this explains it, thanks!

I remember this was a limitation of the githhub action, it just pulls codespell @ HEAD so it could break overnight.

> This makes me wonder if we were better off maintaining codespell as a github action than having it maintained via a make target.

IMO the Makefile target is still an improvement because 1) developers can run it locally 2) we control the version bumps

We could try to backport the Makefile target switch to release-1.10 to make development easier, or just backport the typo fixes for this one time. release-1.10 branch will fall out of support in less than a month with 1.12 comes out and it's unlikely there will be another codespell release by then.

**Comment by nawazkh** [comment]
Could a rebase help ?

**Comment by nojnhuh** [comment]
Thank you for the rebase!

/remove-label needs-rebase

**Pull request merged**
