### PR TITLE
Fix AzureClusterIdentity conversion and add missing webhook

### LINKED ISSUE #1634: Missing conversion webhook for AzureClusterIdentity
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

Yes.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Deployed CAPZ via Tilt from the current main branch.
- Ran the following check to see if `AzureClusterIdentity` has a conversion webhook.

```
$ kubectl get crd azureclusteridentities.infrastructure.cluster.x-k8s.io -o json | jq ".spec.conversion"
{
  "strategy": "None"
}
```

According to the above result there is no conversion webhook for `AzureClusterIdentity`.

- Checked CAPZ source code, which confirmed that there is no conversion webhook for `AzureClusterIdentity`.

**What did you expect to happen:**

Conversion webhook is configured and it can be confirmed with the following command and result similar to the one below:

```
$ k get crd azureclusteridentities.infrastructure.cluster.x-k8s.io -o json | jq ".spec.conversion"         
{
  "strategy": "Webhook",
  "webhook": {
    "clientConfig": {
      "caBundle": "<truncated>",
      "service": {
        "name": "capz-webhook-service",
        "namespace": "capz-system",
        "path": "/convert",
        "port": 443
      }
    },
    "conversionReviewVersions": [
      "v1",
      "v1beta1"
    ]
  }
}
```

**Environment:**

- cluster-api-provider-azure version: `main` branch commit `7bf041ea093f6fc0630561a2452e17d9bdceca41`
- Kubernetes version: (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```
$ cat /etc/os-release
NAME="KDE neon"
VERSION="5.22"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.22"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### PR DESCRIPTION
**Pull request by nprokopic**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

AzureClusterIdentity conversion webhook is currently missing. Also when adding a unit test for the existing conversion, the unit test fails.

This PR fixes the AzureClusterIdentity conversion implementation, adds the unit test and adds conversion webhook.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1634

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Fix AzureClusterIdentity conversion and add missing webhook
```

### CODE REVIEW

**Comment by nprokopic** [comment]
cc @fiunchinho

**Review by mboersma — APPROVED** [review]
/lgtm

This looks solid to me, but let's get some other eyes on it before merging.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
