### PR TITLE
Add Flatcar Container Linux sysext  templates 

### PR DESCRIPTION
**Pull request by sayanchowdhury**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

This PR adds a new cluster template for Flatcar based on systemd-sysexts. The advantages of the implementation is that the clusters can directly consume the vanilla Flatcar SIG images, instead of the Flatcar-K8S images built through image-builder.

The PR is currently in draft stage, as I'm looking into adding the tests for the PR but opening it for early comments.

cc @pothos

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Add new flavor `flatcar-sysext` for Flatcar Container Linux cluster deployments.
```

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
@tormath1 We should do a rebase, and run the tests. The setup was good, but we had CI failures which needs fixing.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
cc @mboersma @nojnhuh @nawazkh @willie-yao @Jont828 we have another test scenario in our optional job, if we get flakes for this flatcar test, please file an issue and reach out to @t-lo and @sayanchowdhury and @tormath1 for triage and debugging.

Thank you for the contribution!

/assign @mboersma

**Review by mboersma — COMMENTED** [review]
I can see the flatcar-sysext spec passed in the optional CI. 🚀 

Looks great overall, I just had some small doc comments.

**Comment by t-lo** [comment]
> we have another test scenario in our optional job, if we get flakes for this flatcar test, please file an issue and reach out to @t-lo and @sayanchowdhury and @tormath1 for triage and debugging.
> 
> Thank you for the contribution!

@jackfrancis  While I do see OWNERS information in the repository would it maybe make sense to start a separate CODEOWNERS document to make it clear who to reach out to regarding individual sub-systems (Ignition / Flatcar support in the case at hand)? I believe this would be helpful for users and even for new contributors.

**Review by mboersma — APPROVED** [review]
/lgtm
/retest
/assign @jackfrancis

**Comment by jackfrancis** [comment]
apiversion upgrade test seems to be complaining about 1.27.16, is there some CI version or image promotion housekeeping we need to do to get that test passing?

cc @mboersma

**Comment by mboersma** [comment]
/retest
v1.28.10 is in use too, populated now.

**Comment by jackfrancis** [comment]
/approve

apiversion-upgrade is a non-optional test so if it passes we're g2g

**Comment by mboersma** [comment]
It looks like the switch to community gallery images somehow broke the CAPI upgrade test:

```
{Machines should remain the same after the upgrade
Expected
    <bool>: false
to be true failed [FAILED] Machines should remain the same after the upgrade
Expected
    <bool>: false
to be true
In [It] at: /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.4/e2e/clusterctl_upgrade.go:650 @ 10/31/24 21:32:34.429
}
```

I'm having trouble seeing what's changed from reading the logs. 

Sorry @sayanchowdhury, this doesn't have anything to do with your PR, we'll get it worked out ASAP.

**Comment by jackfrancis** [comment]
@willie-yao worked on this test recently, he might be able to help

**Comment by willie-yao** [comment]
Looking into it now. I remember seeing a similar error when implementing the test.

**Comment by willie-yao** [comment]
@mboersma The only difference I see between the [failed Machine](https://[storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4575/pull-cluster-api-provider-azure-apiversion-upgrade/1852088664037789696/artifacts/clusters/clusterctl-upgrade-management-3gmtng/resources/clusterctl-upgrade/Machine/clusterctl-upgrade-workload-vtcdqj-mp-0-1.yaml](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4575/pull-cluster-api-provider-azure-apiversion-upgrade/1852088664037789696/artifacts/clusters/clusterctl-upgrade-management-3gmtng/resources/clusterctl-upgrade/Machine/clusterctl-upgrade-workload-vtcdqj-mp-0-1.yaml)) and a [passed test](https://[storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/5209/pull-cluster-api-provider-azure-apiversion-upgrade/1851325469652160512/artifacts/clusters/clusterctl-upgrade-management-61a43u/resources/clusterctl-upgrade/Machine/clusterctl-upgrade-workload-ntngzc-mp-0-0.yaml](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/5209/pull-cluster-api-provider-azure-apiversion-upgrade/1851325469652160512/artifacts/clusters/clusterctl-upgrade-management-61a43u/resources/clusterctl-upgrade/Machine/clusterctl-upgrade-workload-ntngzc-mp-0-0.yaml)) is that the Machines seem to be failing on Ubuntu 24.04. The Machines are 22.04 post-upgrade in a passed test.

**Comment by willie-yao** [comment]
The test is also upgrading from 22.04 to 24.04 now in the failed test. It looks like the old Machine comes up, then gets replaced by one with Ubuntu 24.04. Do you know why this may be happening? @mboersma @jackfrancis

**Comment by nojnhuh** [comment]
The new community gallery images are based on Ubuntu 24.04 while the old Marketplace images are based on 22.04.

I'm reasonably confident the failure isn't related to this PR, so I opened a new issue:  #5229

**Comment by willie-yao** [comment]
This PR looks good, should we just admin-merge it? @nojnhuh

**Comment by nojnhuh** [comment]
> This PR looks good, should we just admin-merge it? @nojnhuh

SGTM

/override pull-cluster-api-provider-azure-apiversion-upgrade

**Pull request merged**
