### PR TITLE
📖 Fix few typos in docs under /topics folder

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fix some typos in various documents under /topics folder
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [X] squashed commits
- [X] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks for your PR!
/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/approve

Thank you!

**Pull request merged**
