### PR TITLE
Adding *.sh eol=lf to make working in WSL Easier

### PR DESCRIPTION
**Pull request by luthermonson**
**What type of PR is this?**
Utility PR to help WSL developers with autocrlf turned on. For anyone that wants to apply this PR after it's merged you can pull in the change and run the following for git to switch all *.sh files to LF.

```
git rm --cached -r .
git reset --hard
```

/kind feature

**What this PR does / why we need it**:
Adds a .gitattribute for *.sh to force LF so when you run make commands in WSL the shell scripts will run without having to convert them by hand.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/shrug
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/ok-to-test

@nawazkh @jsturtevant could one of you review this since I know you both use WSL?

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Comment by jsturtevant** [comment]
> /ok-to-test
> 
> @nawazkh @jsturtevant could one of you review this since I know you both use WSL?

I synced with @luthermonson and these changes will really help new folks who are using windows and wsl. Specifically when the files are checked out to the windows file system and they try to run make commands from WSL.  Shouldn't affect Linux/Mac users.

To make it easier, going to move this to https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2417#issuecomment-1165479594

**Comment by luthermonson** [comment]
closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2417 which will have both the *.sh and *.yaml fix in it so we dont merge conflict the two branches when merged independently.

**Pull request closed without merging**
