### PR TITLE
Allow parallel flavor resources in Tilt

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: Allows building more than one flavor in Tilt at the same time. Since the flavors have no dependencies on each other this should be fine.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by willie-yao — COMMENTED** [review]
This works on my end! I'll add the lgtm once the test failure is fixed.

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by nawazkh** [comment]
Oh nice! \lgtm+

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
