### PR TITLE
Bump Calico to v3.26.1

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Bumps Calico to the latest version. Calico v3.26.0 had an issue with permissions which caused conformance to fail (see https://github.com/projectcalico/calico/issues/7751). This was fixed by https://github.com/tigera/operator/commit/792df2fa5bd996188f9adb8dd76dad55fa52c271.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump Calico to v3.26.1
```

### CODE REVIEW

**Comment by marosset** [comment]
The v3.26.1 windows calico images are built

https://hub.docker.com/layers/sigwindowstools/calico-node/v3.26.1-hostprocess/images/sha256-faeac084cc2955990f4d9c005c9e2299296d8ada6fe87338db761db11b6e91db?context=explore

**Review by marosset — APPROVED** [review]
/lgtm
(pending tests)

**Comment by mboersma** [comment]
It looks like we still have failures reported as successes in pull-cluster-api-provider-azure-capi-e2e:


capz-e2e: [It] Running the Cluster API E2E tests Should successfully exercise machine pools Should successfully create a cluster with machine pool machines expand_more44m22s | capz-e2e: [It] Running the Cluster API E2E tests Should successfully exercise machine pools Should successfully create a cluster with machine pool machines expand_more | 44m22s

**Comment by CecileRobertMichon** [comment]
Let me rerun all the tests now that that should be fixed.

/test all

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
