### PR TITLE
📖  Update release documentation

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Updates release documentation with small fixes found during latest release.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

need to change something

**Comment by CecileRobertMichon** [comment]
/hold cancel

the release-notes changes haven't been released yet, will update once they have

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
