### PR TITLE
Add timestamp log to e2e waiting for deployment helper

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**: Add more debug output for #1284 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
```
Mar 30 18:09:49.521: INFO: starting to wait for deployment to become available
Mar 30 18:10:09.743: INFO: Deployment default/web is now available
```

```
Mar 30 18:11:51.173: INFO: starting to wait for deployment to become available
Mar 30 18:12:51.451: INFO: Deployment default/web-windows is now available
```

```
Mar 30 18:05:39.087: INFO: starting to wait for deployment to become available
Mar 30 18:05:59.199: INFO: Deployment default/web is now available
```

**Comment by CecileRobertMichon** [comment]
/hold cancel

let's merge this so we can use it to investigate the flakes. Looks like the deployments are only taking ~1 minute to become available to unclear why some take 5+ minutes.

**Pull request merged**
