### PR TITLE
[release-1.8] Allow feature gates to be passed through for Windows

### PR DESCRIPTION
**Pull request by marosset**
Allow feature gates to be passed through for Windows CI

 

 
**What type of PR is this?**

**What this PR does / why we need it**:
Cherry-pick of #3388 into release-1.8

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Adding support for specifying kubelet feature gates with $NODE_FEATURE_GATE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@marosset is it possible to cherry-pick the actual commit instead of the merge commit?

**Comment by marosset** [comment]
> Reference in ne

I cherry-picked ` 0ea686706109a8f5f56e8516a8f60c3a0618773f` and force pushed to the same PR branch

**Comment by CecileRobertMichon** [comment]
/retitle Allow feature gates to be passed through for Windows

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
