### PR TITLE
Bump controller-runtime to v0.15.1

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates controller-runtime to [v0.15.1](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.1), which includes several bug fixes.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

CAPI has also bumped up to this version in `main`:

https://github.com/kubernetes-sigs/cluster-api/blob/7c06531b178110c8d25fe149566ddb6e8cc686be/go.mod#L45

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/retest 

[Flake](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3848/pull-cluster-api-provider-azure-e2e/1691581230161596416) looks like #3842.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
