### PR TITLE
Add release notes for v1.11.8

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adds release notes for the v1.11.8 patch release.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
Release notes are empty although there were several commits:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/v1.11.7...release-1.11

I'm not sure why. Some of those PRs did have release notes.

**Comment by CecileRobertMichon** [comment]
@mboersma file is empty, that's not expected

**Comment by mboersma** [comment]
> file is empty, that's not expected

Fixed. I had a local v1.11.8 tag by virtue of accidentally starting the old release process.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
/hold
/lgtm cancel

this should be against the main branch

**Comment by mboersma** [comment]
/close

This should have been opened against the `main` branch.

**Pull request closed without merging**
