### PR TITLE
🌱  remove extra spaces in MHC prow cluster template

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Fixes conformance tests https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-conformance-v1alpha3

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/envsubst-drone < /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/templates/test/cluster-template-prow.yaml | kubectl apply -f -
2020/09/01 11:11:57 Error while envsubst: bad substitution
cluster.cluster.x-k8s.io/capz-8mrp9o created
azurecluster.infrastructure.cluster.x-k8s.io/capz-8mrp9o created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capz-8mrp9o-control-plane created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-8mrp9o-control-plane created
machinedeployment.cluster.x-k8s.io/capz-8mrp9o-md-0 created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-8mrp9o-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capz-8mrp9o-md-0 created
The MachineHealthCheck "capz-8mrp9o-mhc-0" is invalid: 
* spec.clusterName: Invalid value: "": spec.clusterName in body should be at least 1 chars long
* spec.unhealthyConditions: Invalid value: "null": spec.unhealthyConditions in body must be of type array: "null"
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
test looks good
```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/envsubst-drone < /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/templates/test/cluster-template-prow.yaml | kubectl apply -f -
cluster.cluster.x-k8s.io/capz-izva01 created
azurecluster.infrastructure.cluster.x-k8s.io/capz-izva01 created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capz-izva01-control-plane created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-izva01-control-plane created
machinedeployment.cluster.x-k8s.io/capz-izva01-md-0 created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-izva01-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capz-izva01-md-0 created
machinehealthcheck.cluster.x-k8s.io/capz-izva01-mhc-0 created
```

/hold cancel

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
