### PR TITLE
[WIP] Enable 3 nodes e2e test 

### LINKED ISSUE #409: Re-enable multi control-plane E2E
3 control plane E2E has been broken since v1alpha3 was introduced and it got temporarily disabled in https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/28c3bb5997227b60f4c2813b0dcaa0b901cee310 to unblock other PRs. We need to investigate the cause of the failure and re-enable it.

/assign 
/assign @nader-ziada

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- refactor resource generators 
- enable e2e 3nodes test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #409 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@nader-ziada try fixing the merge conflicting and rerunning the test, #431 might have helped

**Comment by CecileRobertMichon** [comment]
seeing `I0311 20:20:48.731165       1 kubeadmconfig_controller.go:267] controllers/KubeadmConfig "msg"="ConfigOwner is not a control plane Machine. If it should be a control plane, add the label `cluster.x-k8s.io/control-plane: \"\"` to the Machine" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capz-k5rh4b-0-nwhfq"} "name"="capz-k5rh4b-0-84fcb66b68-4jblp" "version"="6175" ` in logs

**Comment by nader-ziada** [comment]
this PR has been around for too long and I think something broke in the rebase, will close it and create a new one

**Pull request closed without merging**
