### PR TITLE
Minor update to v1.14.0 CHANGELOG

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

This is a trivial change to the v1.14.0 CHANGELOG, in order to trigger the release action that wasn't triggered by #4627.

The current logic only fires if there is literally one CHANGELOG/<name>.md file in the commit. We're exploring how to make that more flexible in #4631.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/approve

**Pull request merged**
