### PR TITLE
E2E test error when collecting logs after deleting

### LINKED ISSUE #2617: E2E Test failed to watch v1.Event for public custom vnet
/kind failing-test

**What steps did you take and what happened:**
Every run of the E2E test displays a series of errors like this:

```
Failed to watch *v1.Event: failed to list *v1.Event: Get "https://capz-e2e-3ctj2p-public-custom-vnet-f90fe7cb.westus2.cloudapp.azure.com:6443/api/v1/namespaces/capz-e2e-3ctj2p/events?resourceVersion=8198": dial tcp: lookup capz-e2e-3ctj2p-public-custom-vnet-f90fe7cb.westus2.cloudapp.azure.com on 10.63.240.10:53: no such host
```

**What did you expect to happen:**
We should not be seeing this error happen on every single run of the test.

**Anything else you would like to add:**

**Environment:**

Test-infra

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Every run of the E2E test results in failures collecting logs and events for the private cluster test because the cluster is already in the process of deletion

**Which issue(s) this PR fixes**:
Fixes #2617

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
I'm comparing the e2e output from this PR against others...and I'm not seeing all that spew about `reflector.go: failed to list *v1.Event` in the private cluster test in particular.

I'm also not seeing it elsewhere in the test suite, but this fix looks like it should only relevant for the private cluster test. But the PR description also makes it sound like a general fix, so maybe I'm confused.

**Comment by willie-yao** [comment]
@mboersma The `reflector.go: failed to list *v1.Event` error only happened for the private cluster test. If you look at the e2e output for other PRs, all of the errors originate from this line:
```
failed to list *v1.Event: Get "https://capz-e2e-wjb56n-public-custom-vnet-fe741ffb.eastus2.cloudapp.azure.com:6443/api/v1/namespaces/capz-e2e-wjb56n/events?resourceVersion=7628": dial tcp 20.96.156.198:6443: i/o timeout
```
The error happened because we were passing the wrong `cancelFunc` into the cleanup function, causing the log watcher to not be cancelled before deleting logs.

**Comment by willie-yao** [comment]
I should've been more clear in the PR description. I was actually investigating a different error where there were failures to get logs for every test, but that was somehow fixed indirectly by removing the cordon and drain test.

**Comment by mboersma** [comment]
/lgtm

Thanks for the explanation--I was confused because of the interleaved log output, but I get it now.

This is a relief--I was starting just to ignore the `reflector.go` errors, I'd seen them so many times. Thank you for tracking this one down!

**Comment by willie-yao** [comment]
Yup no problem! I'm happy to track down this fix and make the test output a lot less cluttered!

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
