### PR TITLE
bump ASO to v2.8.0

### LINKED ISSUE #4957: Update ASO dep to 2.8.0
/kind feature

**Describe the solution you'd like**
Bump [ASO to 2.8.0 ](https://github.com/Azure/azure-service-operator/releases/tag/v2.8.0) dep so we can use all the latest AKS preview features such as AKS automatic.

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Bumps to ASO v2.8. Also removes some workarounds needed in older versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4957

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
CAPZ now installs Azure Service Operator v2.8.0.
Go 1.22 is required to build CAPZ.
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
This should be ready for review.

/retitle bump ASO to v2.8.0

/release-note-edit
```release-note
CAPZ now installs Azure Service Operator v2.8.0.
Go 1.22 is required to build CAPZ
```

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by dtzar** [comment]
LGTM, just needs to have merge conflicts resolved?

**Comment by nojnhuh** [comment]
dependency review should be fixed by #4981

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
