### PR TITLE
updated link to the k8s bot page

### PR DESCRIPTION
**Pull request by opowbow**
**What this PR does / why we need it**:

link on README.md to kubernetes bot commands was broken

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Just an error on the docs
**Special notes for your reviewer**:

nothing other than doc change here ; but this is new for me so please check it over

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Thanks for the fix, @opowbow! :)
/lgtm
/approve
/ok-to-test
/check-cla

**Comment by justaugustus** [comment]
Can you update the release note in the description to `NONE`?

**Comment by opowbow** [comment]
done

**Comment by justaugustus** [comment]
Yayyy!

**Pull request merged**
