### PR TITLE
[release-1.15] Bump CAPI to v1.7.3

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Manual cherry-pick of #4915

Updates CAPI to [v1.7.3](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.3). Also bumps cert-manager to v1.15.0 to stay in sync with CAPI.

**Which issue(s) this PR fixes**:

N/A, but see #4858 for prior art.

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.7.3
```

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
I updated this to remove my (incomplete) change to `OLD_PROVIDER_UPGRADE_VERSION`: apparently we haven't been updating those versions in release branches, just in `main`. :shrug:

**Comment by nojnhuh** [comment]
unlucky region roulette on this PR...
/retest

**Pull request merged**
