### PR TITLE
Skip optional GPU-enabled test since sub has no quota

### PR DESCRIPTION
**Pull request by mboersma**
/kind failing-test

**What this PR does / why we need it**:

Disables the optional GPU-based test, as the new community subscription has no quota for these SKUs and it will fail.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
It's about to fail again. I think in this case we should `/override pull-cluster-api-provider-azure-e2e`, since this PR couldn't be affecting that outcome.

**Comment by mboersma** [comment]
/retest 

```
	--------------------------------------------------------------------------------
	RESPONSE 400: 400 Bad Request
	ERROR CODE: SkuNotAvailable
	--------------------------------------------------------------------------------
	{
	  "code": "SkuNotAvailable",
```

Sigh.

**Comment by nojnhuh** [comment]
dreams do come true
Screen Shot 2024-07-24 at 20 24 19

**Pull request merged**
