### PR TITLE
Set default outbound lb for v1alpha3 clusters

### LINKED ISSUE #1622: Set default outbound load balancers for v1alpha3 clusters
/kind bug

**Describe the solution you'd like**
v1alpha3 clusters have node outbound and control plane outbound load balancers created by default. To preserve backwards compatibility, we'll need to set default values for `NodeOutboundLB` and `ControlPlaneOutboundLB` when converting from v1alpha3 to v1alpha4.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1622 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Assign default outbound load balancers for v1alpha3 clusters
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
This should have a release note, it's fixing a bug

**Comment by shysank** [comment]
> This should have a release note, it's fixing a bug
done, Thanks! Unfortunately, I also didn't do it for the other pr for setting outbound lb name. Maybe we can update that manually when creating the release?

**Review by devigned — APPROVED** [review]
/lgtm

**Pull request merged**
