### PR TITLE
added unit Test for exported functions

### PR DESCRIPTION
**Pull request by swastik959**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**: *added unit Test for exported functions*

**Which issue(s) this PR fixes** :
Fixes ##2078

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/ok-to-test

**Comment by nawazkh** [comment]
@swastik959 looks like the implemented file has some errors to be addressed. Did you get a chance to check the `link` under `Details` column in the comment posted by k8s-ci-robot ?

**Comment by willie-yao** [comment]
@swastik959 Are you still working on this? Unit tests for AzureManagedMachinePool controller were added in #3195. Is this adding the same test?

**Comment by swastik959** [comment]
@willie-yao no I am not working on it . I will close it

**Pull request closed without merging**
