### PR TITLE
added crud test for loadbalancerprofile

### LINKED ISSUE #2871: AzureManagedCluster E2E: LoadBalancerProfile CRUD tests
/kind feature
/area managedclusters

**Describe the solution you'd like**
Create new AzureManagedCluster E2E: LoadBalancerProfile CRUD tests

### PR DESCRIPTION
**Pull request by swastik959**
**What type of PR is this?**  /feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:adds crud test for loadbalancerprofile
Fixes #2871

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by Jont828 — COMMENTED** [review]
Thanks for the contribution! Could you explain a bit about what you're trying to set up here? If you want to add or modify an e2e test, I believe you'd need to put this under `package e2e` and use the specs in `azure_test.go` instead.

**Comment by nawazkh** [comment]
Hey @swastik959 , How is this PR coming along ?

**Comment by Jont828** [comment]
@swastik959 Sorry for the late response, and thank you for clarifying! I think in our tests, we don't need to set up another `main()` function. Instead, we can refactor it using the `testing` package into a function that would look something like this. If you'd like some help, I'm happy to explain more/help you refactor.

```
func TestMyFunction(t *testing.T) {
	g := NewWithT(t)
        g.Expect(...)
}
```

**Comment by willie-yao** [comment]
Hey @swastik959, thanks so much for your work so far! Are you still planning to work on this issue?

**Comment by nojnhuh** [comment]
@swastik959 Feel free to reopen this PR if you plan to pick back up on this.

**Pull request closed without merging**
