### PR TITLE
ci: add build provenance tags to E2E-created clusters

### LINKED ISSUE #1189: Add a resource group tag for PR number on E2E jobs
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

It would be useful to be able to tell which PR/branch created a cluster when looking at E2E resource groups. This can be done by adding a new tag to the RG, just like we add the creationTimestamp and jobName tags already. 
When running in Prow, the tag value should use the available environment variables:
https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables 

We should default the vars to something static when running locally in ci-e2e.sh.

For example:

export PULL_NUMBER="${PULL_NUMBER:-"local"}"

We should add at least PR number, but as a stretch would be great to add other info like branch name, commit, repo name, etc.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind other

(PS requesting we add a `/kind` value of "E2E" and/or "CI" and/or "test")

**What this PR does / why we need it**:

This PR adds a standard `buildProvenance` tag to the AzureCluster resource created by E2E tests. If it's possible to compose a string from the concatenation of `REPO_OWNER` + `REPO_NAME` + `PULL_BASE_SHA`, then we do. If not, then we simply add a value of "canary" to indicate that the cluster was built from source via our standard E2E tooling ( traversing through `scripts/ci-e2e.sh`).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1189

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ x ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> (PS requesting we add a /kind value of "E2E" and/or "CI" and/or "test")

yes please! Labels can be added here: https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml#L1557

And then if we want release-notes to be able to use the kind as a category for release notes it needs to be added to https://github.com/kubernetes/release/tree/master/cmd/release-notes

**Comment by CecileRobertMichon** [comment]
/lgtm

thanks!

**Comment by CecileRobertMichon** [comment]
/lgtm cancel

looks like you need to run `make generate-flavors` 

The templates/ dir uses kustomize to generate the template so you should only have to modify the tags patch and run make generate to apply it to all generated test templates

**Comment by jackfrancis** [comment]
@CecileRobertMichon done

**Comment by CecileRobertMichon** [comment]
@jackfrancis you might have the rebase and generate again as #1216 added a new test template

**Review by devigned — APPROVED** [review]
lgtm

**Pull request merged**
