### PR TITLE
AzureMachinePool windows template fixes 

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
 AzureMachinePool windows fixes to
-  to set disk size to 128gb
- honor WINDOWS_SERVER_VERSION
- use newer pause image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixes for AzureMachinePool running Windows
```

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by CecileRobertMichon** [comment]
@marosset should we cherry-pick this as well?

**Comment by marosset** [comment]
Do we want this in 1.7 too or just 1.8?

**Comment by CecileRobertMichon** [comment]
both since both have active PR tests for cherry-picks, if this fixes stuff

although you'll probably have to do a manual cherry-pick for 1.7 since there will likely be some yaml conflicts

but worth trying

/cherry-pick release-1.7

**Comment by marosset** [comment]
I'll manually cherry-pick into 1.7

**Pull request merged**
