### PR TITLE
Upgrade job should upgrade from 1.20

### PR DESCRIPTION
**Pull request by Rahul-D78**
**What type of PR is this?**

changing the KUBERNETES_VERSION_UPGRADE_FROM variable default
in https://github.com/nader-ziada/cluster-api-provider-azure/blob/08f456963fb47f801e75eae730837e3cffe57bfc/test/e2e/config/azure-dev.yaml to v1.20.9 which is the latest 1.20 patch.

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Thanks for the PR @Rahul-D78!

/test ls

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-capi-e2e

testing the upgrade job

**Comment by Rahul-D78** [comment]
@CecileRobertMichon always looking for new opportunities thanks for opening such good-first-issue

**Comment by Rahul-D78** [comment]
I think I have accidentally pushed it to master branch can I close it and make another one

**Pull request closed without merging**
