### PR TITLE
ci: add `$(KUBECTL)` as a dependency of `make kind-create`

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

 

 
**What type of PR is this?**

**What this PR does / why we need it**:

/kind failing-test

Fixes test failure in https://testgrid.k8s.io/provider-azure-master-signal#capz-azure-disk-machinepool

```log
./scripts/kind-with-registry.sh: line 80: ./scripts/../hack/tools/bin/kubectl: No such file or directory
make[2]: *** [Makefile:535: kind-create] Error 127
make[2]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure'
make[1]: *** [Makefile:443: create-management-cluster] Error 2
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure'
make: *** [Makefile:518: create-cluster] Error 2
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by devigned — CHANGES_REQUESTED** [review]
Perhaps, the change should be made in `kind-create` where that task should depend on `$(KUBECTL)`.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/ab4702448d3afeebf41e7464190b9660ad3905f5/Makefile#L533-L535

@jackfrancis I think this is something you ran into the other day too.

**Review by devigned — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
good suggestion @devigned, thanks

/approve

**Pull request merged**
