### PR TITLE
update azure-sdk-for-go to v66.0.0

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

This is a housekeeping PR to pull in the latest azure-sdk-for-go version so that we can evaluate whether or not our existing API usage patterns continue to be functional, and to ensure that the latest AKS API interfaces are available to capz.

- https://github.com/Azure/azure-sdk-for-go/releases/tag/v66.0.0

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update azure-sdk-for-go to v66.0.0
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Fun!

https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

**Comment by CecileRobertMichon** [comment]
@jackfrancis filed an issue https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2670

**Pull request closed without merging**
