### PR TITLE
Bump e2e test k8s versions

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates Kubernetes versions under test to newer versions.

~~I bumped Flatcar too, hopefully that works!~~ Nope, reverted.

**Which issue(s) this PR fixes**:

See #4434 for the previous time these were bumped.

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
@mboersma In case you haven't tracked it down yet, I think the test is failing because the KubeadmControlPlane resource specifies `feature-gates: WindowsHostProcessContainers=true` for the API server and it looks like that feature flag is no longer valid in Kubernetes v1.28 because it went GA: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

**Comment by nojnhuh** [comment]
Kubebuilder is migrating their domain and causing the link checker to fail in the meantime:
https://kubernetes.slack.com/archives/CAR30FCJZ/p1716281938319289

**Comment by mboersma** [comment]
/test pull-cluster-api-provider-azure-e2e-optional
(for Flatcar)

**Review by nojnhuh — APPROVED** [review]
Thank you for also updating docs!

/lgtm
/approve
/hold for optional tests

**Comment by mboersma** [comment]
Newer Flatcar image was located, so something else must have gone wrong:
```
  May 21 21:26:55.087: INFO: Resolved FLATCAR_KUBERNETES_VERSION (set to stable-1.27) to v1.27.8
  May 21 21:26:55.087: INFO: Finding Flatcar versions in community gallery "flatcar4capi-742ef0cb-dcaa-4ecb-9cb0-bfd2e43dccc0" in location "westus2" for image "flatcar-stable-amd64-capi-v1.27.8"
  May 21 21:26:55.516: INFO: Resolved FLATCAR_VERSION (set to latest) to 3602.2.2
```
I think I'll just revert the Flatcar bump for now.

**Comment by nojnhuh** [comment]
/test pull-cluster-api-provider-azure-e2e-optional
just for the sanity check on the flatcar test

/lgtm
keeping the hold for the optional test

**Comment by mboersma** [comment]
After reverting Flatcar to a known working version of Kubernetes (1.26 😞), the Workload ID optional test is still failing. Not sure why bumping the k8s version would affect this, but the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4865/pull-cluster-api-provider-azure-e2e-optional/1793064361657372672/artifacts/clusters/capz-e2e-ap6m2l-azwi/machines/capz-e2e-ap6m2l-azwi-control-plane-stsgr/kubelet.log) shows things aren't happy.

**Comment by nojnhuh** [comment]
Looks like yet another newly-GA feature gate:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e0af1aeb03468f47bf5216a1e7e0cc7e0a9ac5ec/templates/test/ci/cluster-template-prow-workload-identity.yaml#L60

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

**Comment by mboersma** [comment]
You rock @nojnhuh, I was just starting to dig deeper but that looks like the culprit. `MixedProtocolLBService` was removed in 1.28, so I'll remove it as well from this PR.

For my edification, where did you find this in the logs? Was I just not looking closely enough?

**Comment by nojnhuh** [comment]
> For my edification, where did you find this in the logs? Was I just not looking closely enough?

I'm not sure I've seen things like this spelled out in the logs. I think I hit a weird AKS thing once out of the blue and the issue was a removed feature gate, so that kind of thing has been on my radar recently. Not sure if there's much more we can even collect to help here if it's the API server that's failing to start.

**Comment by nojnhuh** [comment]
/lgtm

Reminder there's still a hold on this for the optional tests which have passed before, so feel free to remove that whenever. I'm not too worried about the rebase affecting the optional tests.

**Comment by mboersma** [comment]
I'll run the -optional tests again before we merge it. Currently I'm more concerned with the -ci-artifacts failures that seem not to be flakes...

**Review by nojnhuh — APPROVED** [review]
/lgtm

I expect the MEC/edge zone test in the optional job to still fail, but I don't think we should block this PR on that.

@mboersma Feel free to drop the hold when the optional job finishes and the commit history here looks however you want.

**Comment by mboersma** [comment]
/cherry-pick release-1.15
/cherry-pick release-1.14
/hold cancel

As expected, the MEC e2e test failed, but everything else is green.

**Pull request merged**
