### PR TITLE
Revert "Make scaleset service async"

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

This works around #3875 to get the workload upgrade tests passing.

This reverts commit 373518e3c79e76d0edd8ddd84679203fd5548f01.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
fyi @Jont828

**Comment by CecileRobertMichon** [comment]
/close

@nojnhuh @willie-yao and I were able to fix the issue in #3901

**Pull request closed without merging**
