### PR TITLE
Delete long running operation state when resource is not found

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Fixing an edge case scenario where a resource is deleted after being created, before the CAPZ controller has a chance to fetch the result. In that case, `Result()` would return `404` and the controller would be stuck in a bad loop. If the resource was somehow deleted by an external process (eg. human or automated cleanup job) we should recreate it. Deleting the long-running state when the error is "not found" will make sure we don't get infinitely stuck trying to get a resource that doesn't exist and instead trying creating the resource again on the next loop.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Delete long running operation state when resource is not found
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @Jont828 @jackfrancis

**Comment by CecileRobertMichon** [comment]
tests passed

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
