### PR TITLE
add AGE column to custom printcolumn

### PR DESCRIPTION
**Pull request by bavarianbidi**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

On all CRDs where custom printcolumns are defined, the AGE column is missing. CAPI core CRDs already have the AGE column in place.

For all CRDs where custom build-colums are defined, the `AGE` column will be introduced. 

```
k get azurecluster
NAME      CLUSTER   READY   REASON   AGE
marioc1   marioc1   True             3d23h
```

Beside the `AGE` column, for `azureclusteridentities`, the `type` will also be a separate column.

```
k get azureclusteridentities
NAME               TYPE                     AGE
cluster-identity   ManualServicePrincipal   14d
```

Signed-off-by: Mario Constanti <mario@constanti.de>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
* The age of all Azureresources is now printed by running `kubectl get` (e.g. `kubectl get azurecluster`)
* `kubectl get azureclusteridentity` now prints the `type` of the Azure Identity.
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by bavarianbidi** [comment]
/test pull-cluster-api-provider-azure-verify

i guess it's a flaky test:

```
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.2/components.yaml': URL is a git repository': evalsymlink failure on '/tmp/kustomize-3768561019/releases/download/v0.5.2/components.yaml' : lstat /tmp/kustomize-3768561019/releases: no such file or directory
```

**Comment by CecileRobertMichon** [comment]
@bavarianbidi thanks for the PR!

Verify job is failing with:

```
--- a/config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
+++ b/config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
@@ -320,7 +320,7 @@ spec:
       jsonPath: .spec.type
       name: Type
       type: string
-    - description: Time duration since creation of this AzureMachine
+    - description: Time duration since creation of this AzureClusterIdentity
       jsonPath: .metadata.creationTimestamp
       name: Age
       type: date
generated files are out of date, run make generate
```

In order to make these changes you should only have to change the files in `api/` then run `make generate` to auto-generate the files in `config/`. Please let us know if you run into any trouble!

**Comment by bavarianbidi** [comment]
> In order to make these changes you should only have to change the files in `api/` then run `make generate` to auto-generate the files in `config/`. Please let us know if you run into any trouble!

:see_no_evil: thanks for pointing this out. Forgot the `make generate-manifest` run this morning when i fixed the finding from the PR.

Should be fine now.

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by mboersma** [comment]
I verified this is working locally:

```shell
% k get cluster-api
NAME                                                            AGE
clusterresourceset.addons.cluster.x-k8s.io/crs-calico-windows   17m
clusterresourceset.addons.cluster.x-k8s.io/csi-proxy            17m

NAME                                                                            CLUSTER            AGE
kubeadmconfig.bootstrap.cluster.x-k8s.io/machinepool-4932-control-plane-mddzr   machinepool-4932   10m
kubeadmconfig.bootstrap.cluster.x-k8s.io/machinepool-4932-mp-0                  machinepool-4932   12m

NAME                                                            CLUSTER            NODENAME                               PROVIDERID                                                                                                                                                                     PHASE     AGE   VERSION
machine.cluster.x-k8s.io/machinepool-4932-control-plane-rzwzh   machinepool-4932   machinepool-4932-control-plane-8d6wf   azure:///subscriptions/e240e532-1923-4fe0-86da-28abc43fc4c7/resourceGroups/machinepool-4932/providers/Microsoft.Compute/virtualMachines/machinepool-4932-control-plane-8d6wf   Running   10m   v1.26.0

NAME                                                 CLUSTER            REPLICAS   PHASE     AGE   VERSION
machinepool.cluster.x-k8s.io/machinepool-4932-mp-0   machinepool-4932   2          Running   12m   v1.26.0

NAME                                        PHASE         AGE   VERSION
cluster.cluster.x-k8s.io/machinepool-4932   Provisioned   12m   

NAME                                                                               CLUSTER            INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE   VERSION
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/machinepool-4932-control-plane   machinepool-4932   true          true                   1          1       1         0             12m   v1.26.0

NAME                                                                              VERSION   READY   STATE       AGE
azuremachinepoolmachine.infrastructure.cluster.x-k8s.io/machinepool-4932-mp-0-0   v1.26.0   true    Succeeded   7m6s
azuremachinepoolmachine.infrastructure.cluster.x-k8s.io/machinepool-4932-mp-0-1   v1.26.0   true    Succeeded   7m6s

NAME                                                                     REPLICAS   READY   STATE       AGE
azuremachinepool.infrastructure.cluster.x-k8s.io/machinepool-4932-mp-0   2          true    Succeeded   12m

NAME                                                            CLUSTER            READY   REASON   AGE
azurecluster.infrastructure.cluster.x-k8s.io/machinepool-4932   machinepool-4932   True             12m

NAME                                                                                  AGE
azuremachinetemplate.infrastructure.cluster.x-k8s.io/machinepool-4932-control-plane   12m

NAME                                                                                READY   REASON   STATE       AGE
azuremachine.infrastructure.cluster.x-k8s.io/machinepool-4932-control-plane-8d6wf   True             Succeeded   10m

NAME                                                                    TYPE               AGE
azureclusteridentity.infrastructure.cluster.x-k8s.io/cluster-identity   ServicePrincipal   12m
```

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
