### PR TITLE
Place Holder PR for testing all the WI tests

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
This PR will not bring any changes to the codebase and is been created as a place holder to tests all the CAPZ test jobs being migrated to use WI. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
As part of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4976

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nawazkh** [comment]
We dont plan on merging this. Created here to validate CAPZ tests
/hold

**Comment by jsturtevant** [comment]
oh this might need a rebase on #4980 for those two tests to pass

**Comment by jsturtevant** [comment]
with https://github.com/kubernetes/test-infra/pull/32974 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4978 we can close this.  can always re-open if need a testing spot
/close

**Pull request closed without merging**
