### PR TITLE
Fix case of userAssignedIdentityID in JSON serialization

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**:

/kind bug

**What this PR does / why we need it**:

This extracts an uncontroversial fix from #2214 so it can be merged separately.

**Which issue(s) this PR fixes**:

Refs #2164
See also kubernetes-sigs/cloud-provider-azure#1290

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Fix case of userAssignedIdentityID in JSON serialization
```

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
lgtm

I assume this is safe to do in a breaking way because the current implementation doesn't actually (and never did) work?

**Comment by mboersma** [comment]
> I assume this is safe to do in a breaking way because the current implementation doesn't actually (and never did) work?

Sadly, yes. Here are the documented fields, and CAPZ just had it wrong: https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/

Secondarily, there is an issue where CAPZ populating this field with the user-assigned ID's "providerID" (URL) wouldn't work with cloud-provider-azure. #2214 addresses that from the CAPZ side, and https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1290 from cloud-provider-azure's side. (I know you know this @jackfrancis, just recapping here.)

That latter fix is being backported to previous releases thanks to your nudging them. Thanks again!

**Comment by mboersma** [comment]
/retest

VMSS provisioning timeout, which I don't think this affects.

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/approve

@jackfrancis feel free to use your "/lgtm" label reviewer powers now that you are officially a reviewer :)

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
