### PR TITLE
remove as azure cloud provider config is auto-generated

### PR DESCRIPTION
**Pull request by thiDucTran**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**: removing statement regarding editing content of `azure.json`

```release-note
Remove outdated statement in custom vnet doc
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/ok-to-test

Thank you for for opening this PR!

**Comment by CecileRobertMichon** [comment]
/release-note-edit ```release-note Remove outdated statement in custom vnet doc```

**Review by mboersma — COMMENTED** [review]
/lgtm

Thanks for catching this!

**Pull request merged**
