### PR TITLE
Add changelog for v1.16.1

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adds a changelog file for the impending CAPZ v1.16.1 patch release.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by willie-yao** [comment]
Gonna open a separate PR to fix hard-coded links to capz.sigs.k8s.io instead of using local files https://github.com/kubernetes-sigs/cluster-api-provider-azure/actions/runs/10797918901/job/29950239288?pr=5122

**Comment by willie-yao** [comment]
/hold
@nojnhuh Will need to fix the links in the docs. I'll just do it in this PR and then fix it upstream if that's okay!

**Comment by nojnhuh** [comment]
@willie-yao Do we also need the link updates on the release branch?

**Comment by willie-yao** [comment]
> @willie-yao Do we also need the link updates on the release branch?

Yes I think so. I'll create a separate PR to main with the link fix commit and then backport it to 1.16

**Comment by willie-yao** [comment]
Opened #5123 PTAL @nojnhuh

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Pull request merged**
