### PR TITLE
Update PR template to assist reviewers

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Adds a list of common TODOs that each PR usually follows to remind both the author and the reviewer to make sure the PR meets all requirements. This is what it will look like:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@justaugustus the reason I prefer adding this directly to the PR template is that it forces people to acknowledge that they have done these 3 things and serves as a reminder. We can also add a link to  CONTRIBUTING.md  (I don't think they are mutually exclusive) but only adding the link isn't efficient enough IMO, people won't clink on the link and read it most of the time. Having the checkboxes there is also helpful for reviewers to remember to check for those 3 things and quickly know if the author has already done them.

**Comment by CecileRobertMichon** [comment]
/hold

working on updating contributing.md

**Comment by CecileRobertMichon** [comment]
/hold cancel

I updated the contributing guidelines and linked them in the PR template @justaugustus

**Comment by justaugustus** [comment]
/lgtm
/approve

Thanks again, @CecileRobertMichon!

**Pull request merged**
