### PR TITLE
Update CAPI to v0.4.0-rc.0

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Updates Cluster API dependencies to the release candidate release for v0.4.0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
the controller unit tests is failing because of a couple of extra `log.EXPECT()` statements. seems like updating the version of gmock caused some different behaviour

**Comment by sedefsavas** [comment]
We had the same problem in CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2506#issuecomment-862838147

**Comment by CecileRobertMichon** [comment]
/retest

aks flake

**Pull request merged**
