### PR TITLE
create AKS with all node pools at creation time

### PR DESCRIPTION
**Pull request by meixingdb**
/kind bug

 
**What type of PR is this?**

Fixing issue
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1743

CAPZ will launch AKS with all the node pools defined.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
CAPZ will launch AKS with all the node pools defined including both system and user node pools.
```

### CODE REVIEW

**Comment by alexeldeib** [comment]
@LochanRn take a look at the artifacts here: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1741/pull-cluster-api-provider-azure-e2e-exp/1443598168640983040/artifacts/clusters/

this is the issue I mentioned to you. all the nodes are ready, AKS is running all pods successfully, but MP and AMMP are still transitioning to ready due to a missed watch. 

I don't think it's related to this PR, will rerun.

/test pull-cluster-api-provider-azure-e2e-exp

**Comment by shysank** [comment]
@alexeldeib Is this related to `agentpool0` not getting created error that I'm seeing in my other pr https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1740/pull-cluster-api-provider-azure-e2e-exp/1443591427559788544/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-7874bc775d-mnrcv/manager.log ?

**Comment by alexeldeib** [comment]
I think that’s actually related to the issue this PR intends to fix (or bandaid until aks fixes)

**Comment by alexeldeib** [comment]
/lgtm
/approve

Let’s get some mileage on this in main. 21min is pretty good time too.

**Comment by alexeldeib** [comment]
/hold

sorry, one sec

**Comment by alexeldeib** [comment]
/hold-cancel

Ah, the apidiff failures from scope changes threw me off. Maybe we should limit that to the api + exp/api dirs.

**Comment by alexeldeib** [comment]
@meixingdb could you add a release note please?

**Comment by meixingdb** [comment]
> @meixingdb could you add a release note please?

added. Thanks

**Comment by CecileRobertMichon** [comment]
@meixingdb @alexeldeib can you please make sure the commit message is more descriptive next time around? Thanks!

**Comment by alexeldeib** [comment]
Yeah, sorry :( I already discussed this with @devigned offline

**Pull request merged**
