### PR TITLE
Move AKS config from reference to test template

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR moves the various `AzureManagedMachinePool` configurations that we use to validate via E2E into the test template, and cleans up the reference AKS template under `templates/` so that it delivers a "default" configuration.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm
/assign @nojnhuh

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Pull request merged**
