### PR TITLE
Refactor repeated code in E2E test specs to helper functions

### LINKED ISSUE #2997: Refactor repeated code in E2E test specs to helper functions
/kind cleanup

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, there is a lot of repeated code in our E2E test files, such as the multiple calls to the [applyClusterTemplateAndWait](https://github.com/willie-yao/cluster-api-provider-azure/blob/528b3706f6e04408184e121a20ffbbfc408a25e0/test/e2e/azure_test.go#L167) function. It would make our tests files much cleaner to encapsulate these calls in a helper function.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Currently, there is a lot of repeated code in our E2E test files, such as the multiple calls to the [applyClusterTemplateAndWait](https://github.com/willie-yao/cluster-api-provider-azure/blob/528b3706f6e04408184e121a20ffbbfc408a25e0/test/e2e/azure_test.go#L167) function. This PR fixes the issue by creating a helper function for repeated calls to `applyClusterTemplateAndWait`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2997

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by willie-yao** [comment]
@CecileRobertMichon I'm re-evaluating my current changes to the code. Looks like the intervals are different for each e2e test spec as well, so the really long input to the helper function would essentially be as complicated as just calling `ApplyClusterTemplateAndWait` directly. I'll think about a better way to approach this.

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-e2e-optional

This looks great @willie-yao 💎

**Comment by nawazkh** [comment]
Great work @willie-yao !

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-e2e-optional

@willie-yao make sure you comment ^ every time you push again as it won't get automatically triggered (and this PR touches those tests so we want to make sure we run them)

**Comment by willie-yao** [comment]
Not sure why I'm seeing so many timeouts on the optional tests. Something might've been messed up on one of the rebases. Will be looking into this! @nawazkh @CecileRobertMichon

**Comment by willie-yao** [comment]
E2E test creating a cluster using an external cloud provider and machine pools is failing 100% on main. This may be related to the VMSS Flex api change. The issue is being tracked here: #3162

**Pull request merged**
