### PR TITLE
Update E2E Kubernetes versions

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Update create version to latest (1.19.3), upgrade from 1.18.10 to 1.19.3.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #998 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update E2E Kubernetes versions
```

### CODE REVIEW

**Review by devigned — COMMENTED** [review]
What do you think about expanding this to tilt as well?

**Comment by nader-ziada** [comment]
lgtm pending adding to [tiltfile](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Tiltfile#L17)

**Comment by CecileRobertMichon** [comment]
not sure if these versions are making the tests more flaky or ...? 

/retest
/hold

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by devigned — APPROVED** [review]
/lgtm
/appove

**Pull request merged**
