### PR TITLE
[WIP] Update Cluster API to v0.3.1

### PR DESCRIPTION
**Pull request by justaugustus**
**What this PR does / why we need it**:
Update Cluster API to v0.3.1

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:
```release-note
Update Cluster API to v0.3.1
```

### CODE REVIEW

**Comment by detiber** [comment]
These changes lgtm, but it looks like the e2e tests need to be updated for the new semantic version validation that is in place with cluster-api v0.3.1

**Comment by nader-ziada** [comment]
i think this line here https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/529a7e4667a9ccf822e13a7125d504ebdfbc28f2/hack/tools/go.mod#L10 needs to be removed, it picking up the older version of the test framework

**Comment by CecileRobertMichon** [comment]
@justaugustus will close this in favor of #464 

/close

**Pull request closed without merging**
