### PR TITLE
include IPAMConfig CRD w/ ClusterResourceSets

### LINKED ISSUE #3227: Windows pod error: failed to setup network for sandbox
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Our VMSS tests include a step to validate a LoadBalancer that sits in front of a Windows pod. Those tests occasionally fail because that pod reports:

```
  Warning  FailedCreatePodSandBox  24m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6587e3b5ab2f01bbc40aef99de40539a4b7c77e9579efcdec323a404ce7baafc": plugin type="calico" failed (add): global strict affinity should not be false for Windows node
  Warning  FailedCreatePodSandBox  63s (x103 over 24m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1794612b2e974afa3866f41153f7e104c0fbc9bfd16951c00ac77fd8c703e9a2": plugin type="calico" failed (add): global strict affinity should not be false for Windows node
```

Node metadata for the Windows node that the pod was scheduled onto does not report anything that suggests root cause:

https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1631536507762249728/artifacts/clusters/capz-e2e-0wup7c-vmss/nodes/win-p-win000001/node-describe.txt

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR adds the crd.projectcalico.org definition for `IPAMConfig` to the `ClusterResourceSet` definitions we include for test templates that require them (test templates with Windows node pools).

We already include via a `ClusterResourceSet` resource a `kind: IPAMConfig` resource in order to fulfill the required calico configuration `strictAffinity: true`. Not including the reference CRD resource has the effect of forcing the CAPI controller-manager runtime to continually retry the application of the `ClusterResourceSet` payload of `kind: IPAMConfig`, and may have the side-effect of disrupting the `strictAffinity: true` configuration during helm installation of calico.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3227

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/assign @CecileRobertMichon @marosset 

This has now passed the VMSS test 4 times in a row (5th attempt in progress).

It has also never repro'd locally for me after a similar number of E2E runs. Let's get a few more runs documented in the PR to account for the fact that we don't fully understand *why* not shipping the CRD definition w/ the CRD resource causes unexpected data values later on, but from our statistical observations over the past week we seem to have crossed the boundary of any other possible explanation for VMSS E2E test success other than "this change is one of the possible changes that fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3227".

**Review by marosset — APPROVED** [review]
/lgtm

thanks @jackfrancis!

**Comment by jackfrancis** [comment]
I'm going to merge and then cherry-pick this into release-1.7 and release-1.8.

Here is an example of this failure in release-1.7:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-7/1633472207365607424

Here is an example of this failure in release-1.8:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-8/1636534251157458944

**Comment by CecileRobertMichon** [comment]
great work investigating and root causing this one!

/lgtm

**Comment by CecileRobertMichon** [comment]
/retest

optional job failed with #3313

**Pull request merged**
