### PR TITLE
Add pod describe to e2e logger

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Adds the `kubectl describe pod` output for every pod in the workload cluster in artifacts. Not that this replaces pod-events.txt (pod describe contains pod events)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
This seems to be working as expected, see https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3097/pull-cluster-api-provider-azure-ci-entrypoint/1618362549466566656/artifacts/clusters/capz-osvzo6/kube-system/kube-apiserver-capz-osvzo6-control-plane-zv5n7/ for an example output

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

2 for the price of 1!

**Comment by CecileRobertMichon** [comment]
I propose we cherry-pick this so we can start using it today for all the jobs that use the release-1.7 branch

/cherry-pick release-1.7

**Comment by jackfrancis** [comment]
> I propose we cherry-pick this so we can start using it today for all the jobs that use the release-1.7 branch
> 
> /cherry-pick release-1.7

+1

**Comment by CecileRobertMichon** [comment]
/hold

to give others a chance to review

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

I see lots of pod-describe.txt artifacts after the e2e job finished. 👍🏻

**Pull request merged**
