### PR TITLE
Update GPU test job image

### LINKED ISSUE #1354: GPU test is failing consistently on release-0.4 branch
/kind failing-test

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-full-release-0-4

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:314
Timed out after 300.046s.
Job default/cuda-vector-add failed
```

It might be an issue with the job, or with the GPU nodes themselves. #1344 recently updated the job image in the main branch, backporting the change might be enough to fix it (or it might be a bigger issue). Note that the GPU template is different in release-0.4 as it does not use the nvidia operator.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

**What this PR does / why we need it**: Backports #1344 to release-0.4.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1354 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
will give it another try

/test pull-cluster-api-provider-azure-e2e-full-release-0-4

**Comment by CecileRobertMichon** [comment]
I don't think the image is going to be enough to fix the test, will have to dig in more

**Pull request closed without merging**
