### PR TITLE
🐛 delete data disks when deleting azure machine

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- when deleting a cluster in an unmanaged resource group, any data disks were not deleted with the azure machines

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Include data disks as part of disks of an Azure machine 
```

### CODE REVIEW

**Review by CecileRobertMichon — APPROVED** [review]
lgtm

@devigned I noticed we're not deleting disks for scale sets while reviewing this, are disks automatically deleted as part of a VMSS delete? if not that's another bug to fix

**Comment by devigned** [comment]
> I noticed we're not deleting disks for scale sets while reviewing this, are disks automatically deleted as part of a VMSS delete?

Hmm... I'm not sure. Need to look into that. I lean toward no.

There might be another angle on this too. Are we worried about deleting data disks folks might want to keep around?

**Comment by CecileRobertMichon** [comment]
> There might be another angle on this too. Are we worried about deleting data disks folks might want to keep around?

I think disks that were created by capz should also be deleted by capz when the cluster is deleted. We don't support BYO data disk currently.

**Comment by nader-ziada** [comment]
> > There might be another angle on this too. Are we worried about deleting data disks folks might want to keep around?
> 
> I think disks that were created by capz should also be deleted by capz when the cluster is deleted. We don't support BYO data disk currently.

should that be included in this PR?

**Comment by CecileRobertMichon** [comment]
> should that be included in this PR?

No, let's do azuremachinepool separately, this PR lgtm as-is. 

/assign @mboersma 
for an additional review

**Review by mboersma — APPROVED** [review]
lgtm

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm

**Pull request merged**
