### PR TITLE
🔧 events for azurecluster_controller

### LINKED ISSUE #562: Add events for Azure Cluster services errors
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Building on what was described in #519 described, we should leverage k8s resource events to bubble up Azure cloud errors to the user. For example, if a network interface fails to create, the error message is currently printed in the capz manager logs but we should also add an event in the azurecluster resource.

/good-first-issue
/help

### PR DESCRIPTION
**Pull request by varunpurohit76**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #562

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Added events data for AzureCluster Controller
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Comment by CecileRobertMichon** [comment]
@varunpurohit76 thanks for the PR! Please add a release note so we can give you credit in the release notes

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/hold for release note
/assign @nader-ziada

**Comment by varunpurohit76** [comment]
@CecileRobertMichon @nader-ziada added release notes.

**Comment by nader-ziada** [comment]
thanks @varunpurohit76 

/approve

**Pull request merged**
