### PR TITLE
[release-1.9] Update Azure documentation links

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Manual cherry-pick of #3702, which works around the link checker linter failing azure.microsoft.com URLs.

**Which issue(s) this PR fixes**:

N/A

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/retest

AKS provisioning flake AFAICT.

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Review by mboersma — COMMENTED** [review]
/approve

**Comment by mboersma** [comment]
Codecov shouldn't be failing based on the content of this PR, but even if it does, it's not intended to block merging PRs. I'm not sure where our configuration is wrong–I thought we had this sorted out.

**Comment by nawazkh** [comment]
We might be missing the patch config for the release-1.9 branch which we have in the main branch.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7659a9fa5a7af3284da0bf609ea770a49dc251c2/.github/codecov.yml#L8-L12

**Comment by nawazkh** [comment]
> We might be missing the patch config for the release-1.9 branch which we have in the main branch.
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7659a9fa5a7af3284da0bf609ea770a49dc251c2/.github/codecov.yml#L8-L12

@willie-yao Do you think adding the patch config to the release branch would solve the problem ?

**Comment by nawazkh** [comment]
> > We might be missing the patch config for the release-1.9 branch which we have in the main branch.
> > https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7659a9fa5a7af3284da0bf609ea770a49dc251c2/.github/codecov.yml#L8-L12
> 
> @willie-yao Do you think adding the patch config to the release branch would solve the problem ?

I created a https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3734 to ublock. Might help?

**Comment by willie-yao** [comment]
> > We might be missing the patch config for the release-1.9 branch which we have in the main branch.
> > https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7659a9fa5a7af3284da0bf609ea770a49dc251c2/.github/codecov.yml#L8-L12
> 
> @willie-yao Do you think adding the patch config to the release branch would solve the problem ?

@nawazkh Yes it will. This should've been backported so that's my bad!

**Comment by mboersma** [comment]
Could someone (re-)review this? I rebased it after the codecov change was merged to release-1.9.

**Pull request merged**
