### PR TITLE
tests for conversion from previous API versions

### LINKED ISSUE #1365: Add tests for conversion from previous API versions
We should add similar tests for conversion webhooks than https://github.com/kubernetes-sigs/cluster-api/pull/4417 to make sure that v1alpha3 --> v1alpha4 conversion actually works for each CRD.

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1365

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Test for conversion from API versions
```

### CODE REVIEW

**Comment by sayantani11** [comment]
> Thanks @sayantani11! Looks like you need to run `make modules` before `make verify` and `make test` could pass.
> 
> CAPZ stopped testing v1alpha3 in testgrid because it's no longer supported in general by Cluster API. What's the motivation in adding this test coverage?

It was just there in the backlog, so decided to just make the PR for it. I was thinking if we can have one for v1aplha4 -> v1beta1 but I guess CAPZ already has that if I am not wrong.

**Comment by sayantani11** [comment]
It wasn't discouraging at all🙌🏻

**Comment by CecileRobertMichon** [comment]
Even though we no longer support creating new v1alpha3 clusters, I still think it'd be valuable to have integration test coverage for v1alpha3 -> v1beta and v1alpha4 -> v1beta1 conversion since there could still be existing alpha clusters out there and we want to make sure we don't break conversion in the current releases. 

It would be valuable to also add the same test to v1alpha4, even though it looks like CAPI never added one for v1alpha4 https://github.com/prksu/cluster-api/tree/main/api/v1alpha4

**Comment by sayantani11** [comment]
> Even though we no longer support creating new v1alpha3 clusters, I still think it'd be valuable to have integration test coverage for v1alpha3 -> v1beta and v1alpha4 -> v1beta1 conversion since there could still be existing alpha clusters out there and we want to make sure we don't break conversion in the current releases.
> 
> It would be valuable to also add the same test to v1alpha4, even though it looks like CAPI never added one for v1alpha4 https://github.com/prksu/cluster-api/tree/main/api/v1alpha4

Should I try adding the ones for v1Alpha3=>v1beta1 and v1Alpha4=>v1beta1?

**Comment by mboersma** [comment]
> Should I try adding the ones for v1Alpha3=>v1beta1 and v1Alpha4=>v1beta1?

@sayantani11 if you're up for that, apparently it would be valuable. Could be a separate PR.

**Comment by sayantani11** [comment]
> > Should I try adding the ones for v1Alpha3=>v1beta1 and v1Alpha4=>v1beta1?
> 
> @sayantani11 if you're up for that, apparently it would be valuable. Could be a separate PR.

Sure!!!

**Comment by CecileRobertMichon** [comment]
/close

Doing some PR queue cleanup 🧹, please feel free to reopen when this is ready for review

**Pull request closed without merging**
