### PR TITLE
Dont add 127.0.0.1 entry for private dns for private clusters

### LINKED ISSUE #2047: Remove /etc/hosts workaround for private clusters
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
In private clusters, there are `preKubeAdm` and `postKubeAdm` commands to add an entry for private dns mapping to `127.0.0.1`. This is done to circumvent azure lb [haipin](https://github.com/microsoft/Azure-ILB-hairpin) issue.

[kubeadm 1.20.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200) added a fix to use LocalApiEndpoint instead of ControlPlaneEndpoint for interactions within the control plane. This means we won't need the workaround of add a hosts entry for private dns. 

**What did you expect to happen:**

Remove /etc/hosts workaround for private clusters

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

[kubeadm 1.20.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200) added a fix to use `LocalApiEndpoint` instead of `ControlPlaneEndpoint` for interactions within the control plane. This means we won't need the workaround of add a hosts entry for private dns. This PR removes `preKubeadm` and `postKubeAdm` commands that added a `127.0.0.1` entry for private dns in `/etc/hosts`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2047 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Don't add 127.0.0.1 entry for private dns in /etc/hosts for private clusters
```

### CODE REVIEW

**Comment by shysank** [comment]
kubeadm init is failing because kubeconfig that the kubelet uses `/etc/kubernetes/kubelet.conf` points to the cluster's dns name which is causing node registration to fail.

**Comment by shysank** [comment]
kubeadm issue https://github.com/kubernetes/kubeadm/issues/2271

**Comment by CecileRobertMichon** [comment]
Given that this is blocked on https://github.com/kubernetes/kubeadm/issues/2271, let's close for now and open an issue to track doing this later

/close

**Pull request closed without merging**
