### PR TITLE
Update CAPI to v0.3.12

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind dependency

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v0.3.12
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Looks like a lot of retests but the CAPI v0.3.12 wasn't available when I first started testing so that's why it was failing... It's fixed now

**Review by devigned — APPROVED** [review]
lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
