### PR TITLE
[managedcluster] should check provisioning status before attempting changes

### LINKED ISSUE #622: [managedcluster] should check provisioning status before attempting changes
/kind bug

**Describe the solution you'd like**
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/4b049939e18f0ba735735c41ac3fa9f828cd5236/cloud/services/managedclusters/managedclusters.go#L181

This code unconditionally sends the cluster to Azure for updates. We need to do a Get() first on the cluster and ensure the provisioning state is in a terminal mode (succeeded, failed, etc -- NOT updating, deleting, or otherwise in progress).

The field is ProvisioningState in this struct from the response: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2019-10-01/containerservice#ManagedClusterProperties

agentpools client does the get(), but doesn't check provisioning state: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/4b049939e18f0ba735735c41ac3fa9f828cd5236/cloud/services/agentpools/agentpools.go#L67-L70

- [ ] fix agent pools
- [ ] fix managed clusters

cc @serbrech 

/help-wanted
/good-first-issue

### PR DESCRIPTION
**Pull request by jroden**
**What this PR does / why we need it**:
agentpools and managedclusters will now ensure [cluster provisioning status](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.provisioningstate?view=azure-dotnet) is in a terminal state before issuing updates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #622 

**Special notes for your reviewer**:
thanks for the help :smile: 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
agentpools and managedclusters will now ensure cluster provisioning status is in a terminal state before issuing updates (Succeeded, Failed, Canceled).  If the cluster is in a non-terminal state then no update call will be made (function will write info log & return).
```

### CODE REVIEW

**Comment by jroden** [comment]
Thanks for the help reviewing this one! :smile:

**Comment by CecileRobertMichon** [comment]
@jroden please squash the commits
/hold
/approve

**Comment by jroden** [comment]
Just squashed the commits!  Thanks for the help!

**Pull request merged**
