### PR TITLE
test: enable ilb e2e with IPv6

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**What this PR does / why we need it**:
IPv6 internal load balancer support was added in [PR](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/703). Enabling the e2e validation for this scenario. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by CecileRobertMichon** [comment]
/retest

flake in cluster delete

**Comment by CecileRobertMichon** [comment]
I looked into the delete that timed out and the specific error was:

```
"message\":\"A retryable error occurred.\",\"details\":[{\"code\":\"ReferencedResourceNotProvisioned\",\"message\":\"Cannot proceed with operation because resource /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/capz-e2e-6lfpfd-ha/providers/Microsoft.Network/networkInterfaces/capz-e2e-5286f-nic/ipConfigurations/pipConfig used by resource /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/capz-e2e-6lfpfd-ha/providers/Microsoft.Network/loadBalancers/capz-e2e-6lfpfd-ha-internal is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutNicOperation.
```

while trying to delete the load balancer. 

@aramase is there any way this could have anything to do with ipv6? I haven't seen that before and since it's related to the internal load balancer...

/hold

**Comment by aramase** [comment]
> @aramase is there any way this could have anything to do with ipv6? I haven't seen that before and since it's related to the internal load balancer...

@CecileRobertMichon I don't think so! I see these 2 tests passed:
```bash
capz-e2e: Workload cluster creation Creating a ipv6 control-plane cluster [REQUIRED] With ipv6 worker node | 19m53s
capz-e2e: Workload cluster creation Creating a private cluster [REQUIRED] Creates a public management cluster in a custom vnet | 45m9s
```

If it does fail again, we can check

**Comment by aramase** [comment]
Had to rebase PR to resolve merge conflict!

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

thanks for fixing this 🎉

**Pull request merged**
