### PR TITLE
WIP: [DO_NOT_MERGE] Change 2404 to 2204

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This PR is for running the upgrade test and figuring out issues found in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4575#issuecomment-2450898339

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
We haven't actually published 22.04 images, so this will 404. But I will do so now and we can see if this is the fix.

**Comment by mboersma** [comment]
Even with Ubuntu 22.04, we're still spinning up new machines.

Does the upgrade test actually use an earlier version of CAPZ that still defaults to Marketplace images, then move to `main` where we default to the community gallery? Something like that would certainly cause a diff.

Maybe we should see if it's possible to skip this spec from the apiversion upgrade test. Or do we consider not rolling the machines on an upgrade to be core functionality here?

**Comment by willie-yao** [comment]
I think the CAPI test it considers any rollouts as a failure of upgrade so there's really no way around that. I guess we'll just have to disable the test in the meantime? Or is there a way to set the image of just this test to the Azure Marketplace image.

**Comment by mboersma** [comment]
/close

I think #5266 made this change not necessary any more. (@willie-yao please re-open if I'm wrong!)

**Pull request closed without merging**
