### PR TITLE
🌱  Change default NSG rule priorities

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Follow up from https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/830#discussion_r461671624, increases the default rules priority to allow adding higher priority custom rules.
SSH inbound allow is now 2200 (was 100), API Server inbound allow is now 2201 (was 101).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Change default NSG rule priorities: SSH inbound allow is now 2200 (was 100), API Server inbound allow is now 2201 (was 101).
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold 

testing back compat

**Comment by CecileRobertMichon** [comment]
/hold cancel

as expected, this change won't affect existing clusters

**Review by devigned — APPROVED** [review]
/lgtm

**Pull request merged**
