### PR TITLE
e2e tests: phase 1

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Add e2e tests
```

### CODE REVIEW

**Comment by justaugustus** [comment]
This is not ready for review yet; it's just a copy/paste, search/replace of the capa e2e tests, that I need to iterate over.
/hold
/milestone v1alpha1
/priority important-soon
/kind feature

**Comment by justaugustus** [comment]
I've added two PRs (#213, #214) which will trim down the size of this change.
I'll rebase on those once they're reviewed and merged.

**Comment by soggiest** [comment]
@justaugustus Is this ready to be merged? It looks good to me

**Comment by justaugustus** [comment]
Still WIP at the moment. I have to clean up the templates and auth

**Pull request merged**
