### PR TITLE
ensure cluster is populated during a failed e2e test

### PR DESCRIPTION
**Pull request by devigned**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
During an e2e test where the cluster fails to provision the control plane, the cluster is nil since the ptr to the cluster will never be set. This PR fixes this by setting up the `clusterctl.ApplyClusterTemplateAndWaitResult` at a higher scope so that the `result.Cluster` field will be non-nil when trying to dump resource definitions at the end of the test.

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/lgtm

thank you 🙏

**Comment by nader-ziada** [comment]
you will have to wait for #1260 and rebase to get this in

**Pull request merged**
